### ISSUE TITLE
Meet and greet thread

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#1]
Hi everyone!

Your first task in this class is:

1.    [sign up for github](https://github.com/join) (if you don't already have an account)
1.    press the "watch" button at the top of this page
1.    reply to this post telling us what tv show you've been binge watching over summer (or what books you've been reading)

All class communication will go through github, and watching this repo will cause you to get email notifications about everything.

**Comment by mikeizbicki** [comment]
Hi everyone, this is Mike Izbicki :)

I've been watching *The Expanse* on Amazon Prime, and I reread Patrick Rothfuss's *Name of the Wind* books. (Gah!!! release the third book already Patrick!)

**Comment by tkapoor22** [comment]
Hi everyone, I'm Tanya!

I've been watching Suits and The Crown over the summer :)

**Comment by refe22** [comment]
Hi everyone, my name is Ruth.

I watched Avatar: The Last Airbender (ahh the nostalgia!) and Haikyuu season 1 and 2 on Netflix this summer

**Comment by samcbogen** [comment]
Hey y'all, I'm Sam. I got caught up on a bunch of Crime shows, and I started watching Ozark on Netflix recently!

**Comment by mel088** [comment]
Hi guys, I'm Melanie!

I've been watching Avatar: The Last Airbender and Scissor Seven this summer  B:) B)

**Comment by ymacias-1** [comment]
Hello everyone, I'm Yvonne! 

Over the summer, I watched Insecure on HBO.

**Comment by ZacDavis0-159910538** [comment]
Hi everyone, I'm Zac!
I've been watching Avatar: The Last Airbender and Tower of God this summer.

**Comment by valerialoria** [comment]
Hi everyone! My name is Valeria, most people call me Vale. 

This summer I started to rewatch How I Met Your Mother and I read a great book called The Choice by Dr. Edith Eva Eger.

**Comment by NilsSkattum** [comment]
Hi everyone! My name is Nils. I've been watching Shameless and I read an interesting book called Richard Holbrooke: The End of the American Century.

**Comment by yilinli-debug** [comment]
Hi everyone! I'm Yilin!
Over the summer, I've been watching several Netflix shows including Stranger Things and Saikiku.

**Comment by TuckHarris** [comment]
Hi everyone! My name is Tucker. I binge watched Avatar the Last Airbender and Umbrella Academy

**Comment by rmagill22** [comment]
Hi everyone! I'm Rachael. I watched a few different shows including The Politician and Criminal Minds.

**Comment by mariagerges** [comment]
Hi everyone!! I am Maria. I binge-watched How I met your mother , some episodes of Rick & Morty, and Lucifer.

**Comment by ktzchen** [comment]
Hi everyone! My name is Katie. I watched 3% and rewatched Person of Interest this summer.

**Comment by Dorcas-Saka** [comment]
Hi, y'all! My name is Dorcas and this summer I watched a lot of Chopped!

**Comment by sophiedecastro** [comment]
Hey everyone! My name is Sophie, and I recently watched Netflix's Street Food: Latin America!

**Comment by Yugi00** [comment]
Hey guys! My name is Jacob Yep and I watched The Last Dance this summer.

**Comment by marielacenteno** [comment]
Hi! My name is Mariela. This summer, I watched Money Heist

**Comment by brandonsrho57** [comment]
Hey Everyone! My name is Brandon. This summer, I watched a bunch of sports-comedy movies like Benchwarmer, Happy Gilmore, etc.

**Comment by iamclassycain** [comment]
Hey! My name is Robert, and I have been binging Game of Thrones. I am currently on Season 7.

**Comment by HoangChu-Claremont** [comment]
Hi! My name is Hoang Chu, and during summer I read Peter Singer's Practical Ethics!

**Comment by joellemin** [comment]
Hi! My name is Joelle. This summer I have been binging Ari Aster movies and Avatar!

**Comment by smcann11** [comment]
Hi all, I'm Spencer McCann... watched Narcos for the first time this summer and read a couple Malcolm Gladwell books

**Comment by sarahfreeman-star** [comment]
Hi! My name is Sarah. This summer I have been binge watching Sherlock and Peaky Blinders!

**Comment by ohorban** [comment]
Hey I'm Alex. I watched a looooot of shows and my favorite was Travelers

**Comment by saneenkhan** [comment]
Hey everyone! My name is Saneen. This summer I watched Money Heist!

**Comment by willwaaang** [comment]
Hey everyone, I'm Will. I've been watching the Umbrella Academy!

**Comment by Skyler-Bradley** [comment]
Hello everyone! My name is Skyler and this summer I binged the Harry Potter series for the first time.

**Comment by Hamadalq181** [comment]
Hi everyone! I'm Hamad. This summer I've been binge watching Dirk Gently's Holistic Detective Agency

**Comment by nickwilson3** [comment]
Hey everyone I am Nick. This summer I binge-watched all of the mcu movies.

**Comment by NHendelman** [comment]
Hi everyone, I'm Noah! I've been mostly watching the Olympics this summer.
