### ISSUE TITLE
Lab #3 Question

### ISSUE THREAD

**Issue by qchen2323** [mikeizbicki/cmc-csci040#100]
Hi Mike,

For some reason, $ python3 -m doctest --verbose lab.py did not produce an output for me.

Can I just submit my completed file to Sakai?

**Comment by mikeizbicki** [comment]
No.  Your submission must be the output of running the doctests.  If you can't get that to work, you'll have to visit the student tutors.

**Comment by jennifersjlim** [comment]
Hi Mike, this is Jen. 
I'm also struggling on running the tests as last time I had to add something before the given (-m doctest --verbose lab.py) to run it, but now, as my python terminal got refreshed, I'm having difficulty figuring out what it was.

**Comment by mikeizbicki** [comment]
@jennifersjlim This type of problem will be difficult to diagnose over github.  Any of the students TAs should be able to help you out pretty quickly though if you see them in person.

Sorry I can't be more helpful.

**Comment by sophiahuangg** [comment]
Hi Professor Izbicki,

Does the order of the test cases in the output matter? Or can we do any order as long as we don't change what's inside of the doctest?

**Comment by Jblachman** [comment]
Hi Mike,

Sorry for previously commented under the wrong section.  Sorry for not finding you today during office hours, had a busy schedule.  I will be there at lab tomorrow to troubleshoot this with you.  Tried working on it today, but just can't seem to get a fix.  Thanks for the reply.

Best,
Justin
