### ISSUE TITLE
Lab Question: Num Digits

### ISSUE THREAD

**Issue by jsilva22** [mikeizbicki/cmc-csci040#101]
Hey Mike this is Joe.
For the Num Digits function you gave us a hint to use a while loop. Is it okay if we use the len and str functions instead?
Joe

**Comment by mikeizbicki** [comment]
Yes. I recommend that you understand how you would use the while loop, but in general with this class, you may use whatever techniques you want as long as they get the right answer.

**Comment by jsilva22** [comment]
Great, thank you! And just to confirm, it says on sakai that the assignment is due at 3pm today. Is that correct or do we have until 11:59pm?

**Comment by mikeizbicki** [comment]
Whoops, that was a typo in the sakai submission.  The lab was due at midnight, and no one will receive late penalties if you submitted it after 3pm.  Thanks for pointing that out so I can correct it.
