### ISSUE TITLE
Natalie Phillips

### ISSUE THREAD

**Issue by nataliephillips** [mikeizbicki/cmc-csci040#108]
This is my practice of markdown...
while I retrieve anything I can from my brain about __*econ50:*__
> My favorite site about Econ50 is: [awesome notes on the textbook] (https://www.studocu.com/en-us/user/2554649/uploads)

My Midterm is on Chapters:
1. Ten Principles of Economics
*People Face Tradeoffs 
*Opportunity Cost
*Rational People Think at the Margin
*Responding to Incentives
*Trade Makes People Better Off
*Markets are Usually a Good Way to Organize Economic Activity
*Governments can Sometimes Improve Market Outcomes
*Standard of Living Depends on a Country's Production
*Prices Rises When Gov Prints Too Much Money
*Society Faces Short Run Tradeoffs Between Inflation and Unemployment
2. Thinking like an Economist
3. Interdependence and the Gains from Trade
4. The Market Forces of Supply and Demand

hey this is inline `Array.prototype.map()`!

```
var add2 = function(number) {
  return number + 2;
}
```
```
<html>
<body>
<b>this is some random code block!</b>
</body>
</html>
```

Back to the ~~<i>important</I>~~ stuff:
![photo of the determinants of demand](https://lh3.googleusercontent.com/proxy/757evEAmIafG-DgcYB4X2UoEtOPXS8r26qOXiuDAImFdWp6h_GcRdhnOpvGLRig1JYywOIwjAG3W69T7Ix8-qR5e1hkGRdNIM3YnAifPcU5FBxywotAzuVR7-vB7Y3JD8Ksabiht_Rs8plZLzZMKnUJUzhq-ozO713EiGtuMQeY5l_huiwKU_7g)

Supply | Demand
------------ | -------------
number of sellers | number of buyers
expectations (taxes) | tastes and preferences
resource prices | price of substitute goods?

**Comment by mikeizbicki** [comment]
This needs to be a reply to #104.
