### ISSUE TITLE
Post twitter screenshots here

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#11]
Reply to this comment with your twitter screenshot.  You can include images in your comments by dragging and dropping.

**Comment by adien43** [comment]
<img width="895" alt="Screen Shot 2020-09-03 at 7 38 26 AM" src="https://user-images.githubusercontent.com/70254408/92185501-177ca480-ee8f-11ea-9f13-dc3577811219.png">

**Comment by samcbogen** [comment]
<img width="1440" alt="Screen Shot 2020-09-03 at 5 14 37 PM" src="https://user-images.githubusercontent.com/70249466/92185533-0d17c780-ee09-11ea-97db-5b7fad105008.png">

**Comment by adien43** [comment]
<img width="1271" alt="Screen Shot 2020-09-04 at 3 38 04 AM" src="https://user-images.githubusercontent.com/70254408/92185600-54489b80-ee8f-11ea-9b92-9ac6ee23aa52.png">

**Comment by samcbogen** [comment]
<img width="1440" alt="Screen Shot 2020-09-03 at 5 14 17 PM" src="https://user-images.githubusercontent.com/70249466/92185674-67b12380-ee09-11ea-8934-7cc5c2058b9c.png">

**Comment by sophiedecastro** [comment]
<img width="748" alt="Sophie de Castro Tweet Edit final" src="https://user-images.githubusercontent.com/70183987/92186192-fe8ad980-ee23-11ea-963d-4758f4b75a04.png">

**Comment by HoangChu-Claremont** [comment]
![Edited tweet](https://user-images.githubusercontent.com/65592963/92187340-a97eb000-ee83-11ea-99df-6fff5da41c47.jpg)

**Comment by valerialoria** [comment]
<img width="591" alt="Screen Shot 2020-09-03 at 7 53 58 PM" src="https://user-images.githubusercontent.com/70248124/92187408-4f4c0380-ee1f-11ea-8afc-dbd34c80820f.png">

**Comment by refe22** [comment]
<img width="1440" alt="Screen Shot 2020-09-03 at 6 58 36 PM" src="https://user-images.githubusercontent.com/70185541/92187674-aa79f800-ee17-11ea-9183-7fb6d2e2ad66.png">

**Comment by NilsSkattum** [comment]
<img width="746" alt="Screen Shot 2020-09-02 at 11 04 38 PM" src="https://user-images.githubusercontent.com/70278877/92187677-6fcc8b80-ee28-11ea-8bdc-28784adc6890.png">

**Comment by ktzchen** [comment]
<img width="1440" alt="Screen Shot 2020-09-03 at 5 18 00 PM" src="https://user-images.githubusercontent.com/70239415/92188012-338d3100-ee10-11ea-8dc9-1b6317ae864f.png">

**Comment by nickwilson3** [comment]
<img width="1440" alt="Screen Shot 2020-09-03 at 6 05 06 PM" src="https://user-images.githubusercontent.com/70651858/92188011-32f49a80-ee10-11ea-8c7a-f6ac964e755b.png">

**Comment by marielacenteno** [comment]
<img width="598" alt="Screen Shot 2020-09-03 at 6 01 23 PM" src="https://user-images.githubusercontent.com/70251451/92187999-2a03c900-ee10-11ea-8868-2bd22d442cc1.png">

**Comment by ohorban** [comment]
<img width="1680" alt="Screen Shot 2020-09-03 at 6 06 32 PM" src="https://user-images.githubusercontent.com/70180882/92188067-633c3900-ee10-11ea-848b-674085b95e50.png">

**Comment by ZacDavis0-159910538** [comment]
![Twitter assignment Comp Sci Lab](https://user-images.githubusercontent.com/70255063/92188163-ae564c00-ee10-11ea-9a61-2e0bac2eec55.PNG)

**Comment by Yugi00** [comment]
![fake-meat-is-fake](https://user-images.githubusercontent.com/65512544/92188188-c037ef00-ee10-11ea-92fe-76f7973b7d8c.JPG)

**Comment by iamclassycain** [comment]
<img width="605" alt="Screen Shot 2020-09-03 at 6 06 52 PM" src="https://user-images.githubusercontent.com/70175867/92188222-db0a6380-ee10-11ea-8e25-84fa30c1789d.png">

**Comment by brandonsrho57** [comment]
![Screen Shot 2020-09-03 at 6 15 00 PM](https://user-images.githubusercontent.com/70169482/92188457-78659780-ee11-11ea-8c34-aa7eecd4b793.png)

**Comment by rmagill22** [comment]
![Screen Shot 2020-09-03 at 6 13 52 PM](https://user-images.githubusercontent.com/70245959/92188531-b2cf3480-ee11-11ea-9a99-6b320d080a4e.png)

**Comment by mel088** [comment]
<img width="706" alt="Screen Shot 2020-09-03 at 6 22 04 PM" src="https://user-images.githubusercontent.com/66801534/92188902-abf4f180-ee12-11ea-8010-45b360fa7609.png">

**Comment by tkapoor22** [comment]
<img width="647" alt="Screen Shot 2020-09-04 at 6 51 58 AM" src="https://user-images.githubusercontent.com/70287764/92188941-910a9780-ee7b-11ea-9d57-c73da06193b4.png">

**Comment by yilinli22** [comment]
![Screen Shot 2020-09-03 at 6 14 43 PM](https://user-images.githubusercontent.com/70351653/92189396-62f16d00-ee13-11ea-852a-54b1a874ae87.png)

**Comment by dorcassaka** [comment]
![Screen Shot 2020-09-03 at 9 30 51 PM](https://user-images.githubusercontent.com/70255375/92189503-cb007d00-ee2c-11ea-8ea5-b7ba6cc9d812.png)

**Comment by joellemin** [comment]
![Screen Shot 2020-09-03 at 6 28 22 PM](https://user-images.githubusercontent.com/70255298/92189384-5cfb8c00-ee13-11ea-9e30-69dbc563c23b.png)

**Comment by ymacias-1** [comment]
![Screen Shot 2020-09-03 at 6 27 21 PM](https://user-images.githubusercontent.com/70245043/92190181-481ff800-ee15-11ea-9650-a863ebb9b694.png)

**Comment by smccann11** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/70291882/92190306-ac42bc00-ee15-11ea-8fa1-9e76fe3bbb9d.png)

**Comment by sarahfreeman-star** [comment]
<img width="603" alt="Hack of Trump's Twitter screenshot " src="https://user-images.githubusercontent.com/70239824/92194828-6e976080-ee20-11ea-821c-95907fef1dfa.png">

**Comment by TuckHarris** [comment]
<img width="1439" alt="Screen Shot 2020-09-04 at 1 28 04 PM" src="https://user-images.githubusercontent.com/70274206/92269637-920aeb80-eeb2-11ea-8998-c658c1afab3f.png">

**Comment by willwaaang** [comment]
<img width="400" alt="Screenshot 2020-09-05 at 10 12 19 PM" src="https://user-images.githubusercontent.com/70219432/92306860-fae28880-efc4-11ea-81c5-37f4023bf6c6.png">

**Comment by saneenkhan** [comment]
<img width="406" alt="Screen Shot 2020-09-05 at 6 12 57 PM" src="https://user-images.githubusercontent.com/70279041/92306866-7f241400-efa3-11ea-9434-a4a7c9f1be7a.png">

**Comment by Skyler-Bradley** [comment]
<img width="584" alt="Screen Shot 2020-09-05 at 1 29 37 PM" src="https://user-images.githubusercontent.com/70355280/92313077-183f3480-ef7c-11ea-8dfd-45fbbb3e4e29.png">

**Comment by mariagerges** [comment]
<img width="668" alt="Twitter Screenshot" src="https://user-images.githubusercontent.com/70242313/92669789-d3682480-f312-11ea-9cc2-d7a5ec19bc26.png">
