### ISSUE TITLE
HW_1 question

### ISSUE THREAD

**Issue by ED-Y-S** [mikeizbicki/cmc-csci040#110]
Professor Mike,

Sorry to bother: may I ask what is the supposed README.md file would be, or should we just make one with our own unique contents ourselves?

**Comment by mikeizbicki** [comment]
If the `README.md` file is blank, then it makes sense that the resulting html file would also be blank.  You need to re-download the `README.md` file so that it's contents match the contents on github.

**Comment by mikeizbicki** [comment]
That's correct.  It's not particularly large.  The download link is here: https://raw.githubusercontent.com/mikeizbicki/cmc-csci040/2021fall/hw_01/README.md
