### ISSUE TITLE
HW_01 Submission Issue

### ISSUE THREAD

**Issue by Eddie-Shi** [mikeizbicki/cmc-csci040#112]
Professor Mike,

Sorry to bother again.

Sakai doesn't seem to allow us to submit pictures through the assignment textbox. Is there an alternative way to do this?

**Comment by mikeizbicki** [comment]
I've just enabled the attachment option on the assignment, so hopefully it should work now.  Thanks for pointing out these sakai issues for me so I can fix them, and sorry it wasn't set up correctly at first.
