### ISSUE TITLE
Lab 5 Code Not Working

### ISSUE THREAD

**Issue by jhwang22** [mikeizbicki/cmc-csci040#119]
Hey @mikeizbicki 

I'm having an issue where I'm getting failed doctests even though all my code is correct. I even checked with Brandon and Nathanael, so I'm not sure what could be wrong. 

I'm specifically getting failures for the grapheme_equality and the character_equality:

2 items had failures:
   4 of   7 in lab#5.character_equality
   1 of   7 in lab#5.grapheme_equality

**Comment by NHendelman** [comment]
I'm struggling with the same issue. I copy and pasted around with the and the same code that got errors for one file that got none for another. It was the same story for ROT13, really weird.

**Comment by jhwang22** [comment]
Update: I used a different, older laptop of mine and the code worked just fine.
