### ISSUE TITLE
Where to post cleaned up webpage

### ISSUE THREAD

**Issue by samcbogen** [mikeizbicki/cmc-csci040#12]
@mikeizbicki - Where on Sakai do we post the cleaned up webpage? There is nothing in assignments yet, and I have the webpage ready to post. Would it be easier to post it in a new Github Issue?

**Comment by mikeizbicki** [comment]
I've just created the lab submission on sakai.

**Comment by samcbogen** [comment]
Thank you @mikeizbicki!
