### ISSUE TITLE
Webpage backlinks

### ISSUE THREAD

**Issue by sophiedecastro** [mikeizbicki/cmc-csci040#13]
Hi all! 

Paste your webpage link, and I'll add it to my site!

Would love if you could add mine to your webpage, as well :) Here's the link to my site: https://sophiedecastro.github.io/

Thanks so much,
Sophie

**Comment by tkapoor22** [comment]
Thanks for creating the issue Sophie! 
 
Here's the link to my webpage: https://tkapoor22.github.io/index.html 

Thank you!

**Comment by brandonsrho57** [comment]
Thanks for this post!

Here's the link to my website: https://brandonsrho57@github.io/

I'll make sure to put you all as my sponsors!

~Brandon

**Comment by dorcassaka** [comment]
Thanks for this!

Here's the link to my webpage: https://dorcassaka.github.io/

I'll add y'all as well!

Thank you!

**Comment by HoangChu-Claremont** [comment]
And here's my link: https://hoangchu-claremont.github.io/ 

Follow my link to become 1 of 2 gold sponsors!

**Comment by ohorban** [comment]
This is mine if you want to check it out

ohorban.github.io

**Comment by ohorban** [comment]
Here's mine if you want to check it out 

https://ohorban.github.io

**Comment by HoangChu-Claremont** [comment]
> Here's mine if you want to check it out
> 
> https://ohorban.github.io
I've followed yours!
Reply to my email if you've follow my link (https://hoangchu-claremont.github.io/) to become a gold Sponsor!

**Comment by ZacDavis0-159910538** [comment]
Thanks, here is mine https://zacdavis0-159910538.github.io/ I'll link you back :).

**Comment by HoangChu-Claremont** [comment]
> 
> 
> Thanks, here is mine https://zacdavis0-159910538.github.io/ I'll link you back :).

Done!

**Comment by HoangChu-Claremont** [comment]
> Thanks for this!
> 
> Here's the link to my webpage: https://dorcassaka.github.io/
> 
> I'll add y'all as well!
> 
> Thank you!

I've follow yours. Please also follow mine (https://hoangchu-claremont.github.io/) and reply to this comment if you've done so.

**Comment by HoangChu-Claremont** [comment]
> Here's mine if you want to check it out
> 
> https://ohorban.github.io

I've follow yours. Please also follow mine (https://hoangchu-claremont.github.io/) and reply to this comment if you've done so.

**Comment by samcbogen** [comment]
Here's Mine! 

https://samcbogen.github.io

Thanks!

**Comment by refe22** [comment]
Hi guys! Here's my link: https://refe22.github.io./
Please comment when you have backlinked my webpage so I can do the same for you. Thanks!

**Comment by HoangChu-Claremont** [comment]
> Hi guys! Here's my link: https://refe22.github.io./
> Please comment when you have backlinked my webpage so I can do the same for you. Thanks!

Done! Please also follow mine (https://hoangchu-claremont.github.io/).

**Comment by refe22** [comment]
> > Hi guys! Here's my link: https://refe22.github.io./
> > Please comment when you have backlinked my webpage so I can do the same for you. Thanks!
> 
> Done! Please also follow mine (https://hoangchu-claremont.github.io/).

Awesome. Thanks! I am adding your link to my code now.

**Comment by refe22** [comment]
> > > Hi guys! Here's my link: https://refe22.github.io./
> > > Please comment when you have backlinked my webpage so I can do the same for you. Thanks!
> > 
> > 
> > Done! Please also follow mine (https://hoangchu-claremont.github.io/).
> 
> Awesome. Thanks! I am adding your link to my code now.

Done!

**Comment by sophiedecastro** [comment]
> Thanks for creating the issue Sophie!
> 
> Here's the link to my webpage: https://tkapoor22.github.io/index.html
> 
> Thank you!

Hey, I just added your site to my code!
Would love if you could add mine to yours: https://sophiedecastro.github.io/
Feel free to like the Facebook buttons while you’re at it :)
Thanks so much,
Sophie

**Comment by sophiedecastro** [comment]
> Thanks for this post!
> 
> Here's the link to my website: https://brandonsrho57@github.io/
> 
> I'll make sure to put you all as my sponsors!
> 
> ~Brandon

Hey, I just added your site to my code!
Would love if you could add mine to yours: https://sophiedecastro.github.io/
Feel free to like the Facebook buttons while you’re at it :)
Thanks so much,
Sophie

**Comment by sophiedecastro** [comment]
> Thanks for this!
> 
> Here's the link to my webpage: https://dorcassaka.github.io/
> 
> I'll add y'all as well!
> 
> Thank you!

Hey, I just added your site to my code!
Would love if you could add mine to yours: https://sophiedecastro.github.io/
Feel free to like the Facebook buttons while you’re at it :)
Thanks so much,
Sophie

**Comment by sophiedecastro** [comment]
> And here's my link: https://hoangchu-claremont.github.io/
> 
> Follow my link to become 1 of 2 gold sponsors!

Hey, I just added your site to my code!
Would love if you could add mine to yours: https://sophiedecastro.github.io/
Feel free to like the Facebook buttons while you’re at it :)
Thanks so much,
Sophie

**Comment by sophiedecastro** [comment]
> Here's mine if you want to check it out
> 
> https://ohorban.github.io

Hey, I just added your site to my code!
Would love if you could add mine to yours: https://sophiedecastro.github.io/
Feel free to like the Facebook buttons while you’re at it :)
Thanks so much,
Sophie

**Comment by sophiedecastro** [comment]
> Thanks, here is mine https://zacdavis0-159910538.github.io/ I'll link you back :).

Hey, I just added your site to my code!
Would love if you could add mine to yours: https://sophiedecastro.github.io/
Feel free to like the Facebook buttons while you’re at it :)
Thanks so much,
Sophie

**Comment by sophiedecastro** [comment]
> Here's Mine!
> 
> https://samcbogen.github.io
> 
> Thanks!

Hey, I just added your site to my code!
Would love if you could add mine to yours: https://sophiedecastro.github.io/
Feel free to like the Facebook buttons while you’re at it :)
Thanks so much,
Sophie

**Comment by sophiedecastro** [comment]
> Hi guys! Here's my link: https://refe22.github.io./
> Please comment when you have backlinked my webpage so I can do the same for you. Thanks!

Hey, I just added your site to my code!
Would love if you could add mine to yours: https://sophiedecastro.github.io/
Feel free to like the Facebook buttons while you’re at it :)
Thanks so much,
Sophie

**Comment by tkapoor22** [comment]
> > Thanks for creating the issue Sophie!
> > Here's the link to my webpage: https://tkapoor22.github.io/index.html
> > Thank you!
> 
> Hey, I just added your site to my code!
> Would love if you could add mine to yours: https://sophiedecastro.github.io/
> Feel free to like the Facebook buttons while you’re at it :)
> Thanks so much,
> Sophie

All done! Thanks so much!!

**Comment by sarahfreeman-star** [comment]
Hey guys! 
Here's my link: https://sarahfreeman-star.github.io/
Please comment when you have backlinked my webpage. BTW, I have already backlinked all of the webpages in this thread! 
Feel free to like the Facebook buttons on my webpage :) 
Thanks so much, 
Sarah

**Comment by adien43** [comment]
Hello! my page is https://adien43.github.io/ 
Would appreciate it if you could backlink my page. 
Will return the favor! Thanks!

**Comment by adien43** [comment]
> Hey guys!
> Here's my link: https://sarahfreeman-star.github.io/
> Please comment when you have backlinked my webpage. BTW, I have already backlinked all of the webpages in this thread!
> Feel free to like the Facebook buttons on my webpage :)
> Thanks so much,
> Sarah

Done!

**Comment by ktzchen** [comment]
Hello everyone! Please add my webpage to your backlinks if you want: https://ktzchen.github.io/
I'll add everyone's backlinks as well :)

**Comment by NilsSkattum** [comment]
Hey everyone! Please add my webpage to your backlinks if you would like: https://nilsskattum.github.io/

I have so far added, @adien43, @ktzchen @sarahfreeman-star @tkapoor22 @sophiedecastro. And will be adding more people soon!

**Comment by NilsSkattum** [comment]
> Hello everyone! Please add my webpage to your backlinks if you want: https://ktzchen.github.io/
> I'll add everyone's backlinks as well :)

Added!

**Comment by NilsSkattum** [comment]
> Hello! my page is https://adien43.github.io/
> Would appreciate it if you could backlink my page.
> Will return the favor! Thanks!

Added!

**Comment by NilsSkattum** [comment]
> Hey guys!
> Here's my link: https://sarahfreeman-star.github.io/
> Please comment when you have backlinked my webpage. BTW, I have already backlinked all of the webpages in this thread!
> Feel free to like the Facebook buttons on my webpage :)
> Thanks so much,
> Sarah

Added!

**Comment by NilsSkattum** [comment]
> Hi all!
> 
> Paste your webpage link, and I'll add it to my site!
> 
> Would love if you could add mine to your webpage, as well :) Here's the link to my site: https://sophiedecastro.github.io/
> 
> Thanks so much,
> Sophie

Added! Please add me back!

**Comment by Yugi00** [comment]
Hey everyone! Please add my webpage to your backlinks if you would like: https://yugi00.github.io/
I'll be adding all the links in this thread to my page!

**Comment by yilinli22** [comment]
Hi! Can anyone add my website to your backlinks? I'll add back! https://yilinli22.github.io/ Thank you so much!

**Comment by yilinli22** [comment]
> Hey everyone! Please add my webpage to your backlinks if you would like: https://yugi00.github.io/
> I'll be adding all the links in this thread to my page!

Added. Would appreciate it if you could add me back. https://yilinli22.github.io/

**Comment by yilinli22** [comment]
> And here's my link: https://hoangchu-claremont.github.io/
> 
> Follow my link to become 1 of 2 gold sponsors!

Added. Could you add me back?

**Comment by yilinli22** [comment]
> Thanks, here is mine https://zacdavis0-159910538.github.io/ I'll link you back :).

Added, @ZacDavis0-159910538 Could you link me back? Thank you!

**Comment by NilsSkattum** [comment]
> Hi! Can anyone add my website to your backlinks? I'll add back! https://yilinli22.github.io/ Thank you so mu

> Hi! Can anyone add my website to your backlinks? I'll add back! https://yilinli22.github.io/ Thank you so much!

I just added you to my website, can you add mine please!

**Comment by ohorban** [comment]
Please add mine.  https://ohorban.github.io
I will add all of yours!!!!

**Comment by NilsSkattum** [comment]
> https://ohorban.github.io

Just added you! @ohorban can you add me please!

**Comment by dorcassaka** [comment]
Please like each page of my webpage, especially the desserts and locations pages, thank you so much!! 

https://dorcassaka.github.io/desserts.html

The like button is at the bottom of each page!

**Comment by brandonsrho57** [comment]
Hey! Please link my website! And like the page if you can! That would be swell! 

https://brandonsrho57.github.io/

**Comment by mariagerges** [comment]
Hello!! I know this is a bit late but I would really appreciate it if you linked and liked my page!! 
Thank you in advance 

here's the link: https://mariagerges.github.io/
