### ISSUE TITLE
10/27 Class Recording

### ISSUE THREAD

**Issue by evankim08** [mikeizbicki/cmc-csci040#135]
Hi @mikeizbicki, I was just wondering if you were planning on posting the class recording from this last Wednesday (10/27) on YouTube? I can't seem to find it as of today. Thank you!

**Comment by mikeizbicki** [comment]
Whoops, looks like accidentally set the video to private when I uploaded it.  I think I've fixed that.  Does it work now?

**Comment by evankim08** [comment]
Yes it works now, thank you!!
