### ISSUE TITLE
Scheduling Conflict Quiz Wednesday

### ISSUE THREAD

**Issue by Jblachman** [mikeizbicki/cmc-csci040#137]
Hi Professor Izbicki,

I emailed you at the start of the year, but I often have a scheduling conflict on Wednesday and can only watch the zoom meetings.   We have our SCIAC Semifinals tonight and I won't be able to make it to class this afternoon.  Is there another time I can take the quiz to make-up this assignment?

Best,
Justin

**Comment by mikeizbicki** [comment]
Let's continue this conversation over email.
