### ISSUE TITLE
Clarifying QCL Hours!

### ISSUE THREAD

**Issue by eburke21** [mikeizbicki/cmc-csci040#141]
It came up in office hours today that not everyone may be familiar with my schedule so just to clarify, every week I have office hours on Tuesdays from 4-5pm and Thursdays from 2-3pm, typically in the QCL but I'll post on here if they'll be on Zoom. I'm also at walk-in hours on Sunday and Thursday nights from 7-9pm!

**Comment by ohorban** [comment]
Hi everyone! I am a new mentor at QCL for CS40. I will be available at QCL for walk-ins **7-9pm on Mondays, Wednesdays, Thursdays, and Sundays** so please come talk to me if you need any help. I will hold office hours on **Thursdays from 5-6pm.** You can also make a 1-on-1 appointments with me [here](https://cmc.mywconline.net/schedule.php)
