### ISSUE TITLE
HW03 Quick Question

### ISSUE THREAD

**Issue by jsilva22** [mikeizbicki/cmc-csci040#146]
Hey Mike, just have a quick question on an error I'm coming across for items_sold. It's getting the correct number of items sold when there is a number and also when there is no number it is putting 0 correctly. However, in examples like the one below where there is Almost gone or Last one, the .s-item__hotness that we used is associated with only these words and the actual number is a different css selector so it puts 0 when there actually might be a number sold. Should we do anything to change this or is it fine for the couple of examples that have these phrases?
![Screen Shot 2021-11-07 at 1 19 09 AM](https://user-images.githubusercontent.com/90739524/140637657-6e45cdcb-a163-4810-a593-a8c92ec05c74.png)

**Comment by mikeizbicki** [comment]
This is a really easy problem to fix.  The css selector that my solution uses looks like 
```
.s-item__hotness, s-item__additionalItemHotness
```
so that it catches both situations.

**Comment by jsilva22** [comment]
Hey Mike, the second s-item should also have a . correct?

**Comment by mikeizbicki** [comment]
Whoops, that's correct!

**Comment by jsilva22** [comment]
Great, thank you!
