### ISSUE TITLE
HW-03 Question regarding CSV

### ISSUE THREAD

**Issue by zealotwithcharge** [mikeizbicki/cmc-csci040#147]
For some reason, when the name contains emojis the cvs writer freaks out and merges the name with price.

Is this something I need to fix or is what I currently have enough for the extra credit?

The parameters are correctly saved in the .json file.

https://github.com/zealotwithcharge/hw_03

**Comment by mikeizbicki** [comment]
This is something that you should fix.  I think this will be easier to fix in person than over github, though.

**Comment by zealotwithcharge** [comment]
Actually, I found out that it's excel that's screwing it up.
The csv file itself contains the data correctly and is accurately displayed on github.
Should I still try to fix the excel version?

**Comment by mikeizbicki** [comment]
No, you don't have to fix bugs in excel :)

**Comment by zealotwithcharge** [comment]
Thank you!
