### ISSUE TITLE
.tex to .py converter

### ISSUE THREAD

**Issue by zealotwithcharge** [mikeizbicki/cmc-csci040#149]
Hi everyone! Not sure if this is worth an issue but I got lazy typing out the code to check the practice quiz answers so I wrote a small program to convert the .tex file Prof Izbicki gives us to a .py file that can be run right away. Hope it helps!

Let me know if there are any bugs/if this is something someone else already posted. I wasn't sure how to upload a file onto an issue so I just pasted the code below.

```
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('name',help = "file name without .tex")
args = parser.parse_args()


with open(args.name+'.tex') as f:
    file = f.read()
    no_begin = file.split('\\begin{lstlisting}')
    no_end=[]
    for chunk in no_begin:
        no_end.append(chunk.split('\\end{lstlisting}'))
    new_file = []
    for i,chunk in enumerate(no_end):
        if i:
            new_file.append(chunk[0])
    new_new_file = '\n'.join(new_file)
    with open(args.name+'.py','w') as f1:
        f1.write(new_new_file)
        f1.close()
    f.close()

```

**Comment by mikeizbicki** [comment]
That's awesome!

I personally find it really annoying that I've been typing stuff out in python and then copy-pasting into latex.  (I think there's been at least once this semester where that's resulted in me making a mistake on a practice quiz.)  And so I've been wanting to set things up to go the other way of creating latex files automatically from python files, but I haven't gotten around to that yet.
