### ISSUE TITLE
HW_03 Number of Pages

### ISSUE THREAD

**Issue by jsilva22** [mikeizbicki/cmc-csci040#151]
Hey Mike, just have a clarifying question. For a while, we were working on just having ```num_pages=1``` but for our final submission, we should have the data for ```num_pages=10``` correct? Not just collecting the info for 1 page of each of our 3 searches.

**Comment by mikeizbicki** [comment]
That's correct.  Ebay will not necessarily give you data for all of those pages, but you must include all the data that ebay gives you for the first 10 pages.
