### ISSUE TITLE
HW3 --csv

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci040#152]
Hi Professor Izbiki,

When I generate the csv file with pandas, the index at position zero is a row of empty cells. Can I just hard code this and do `df.drop([0],inplace=True)`?
Best,
Sophia

**Comment by mikeizbicki** [comment]
I personally don't use pandas, so I can't directly answer your code question, sorry.  But you shouldn't have to do any special transformations on the data for the csv file.  If the first row is wrong on your csv file, it's probably wrong on your json file as well and needs to be modified for both.

**Comment by jsilva22** [comment]
Hey Mike, you mentioned in the eBay hw lecture that it's fine for the first entry in our json and csv files to look different. I have "" for name and then a bunch of nulls followed by free returns having ```false``` . Is this correct or is it considered empty and therefore needs to be changed?
