### ISSUE TITLE
parse price issue

### ISSUE THREAD

**Issue by nataliephillips** [mikeizbicki/cmc-csci040#154]
If ebay doesn't have a price for the item on the front page, what should we write for the price?
For example:
<img width="923" alt="Screen Shot 2021-11-09 at 1 51 12 PM" src="https://user-images.githubusercontent.com/89864023/141010823-6583b1aa-4e8a-4480-bcb1-2103593234df.png">

**Comment by mikeizbicki** [comment]
I believe the following quote from the instructions answers your question:

> Not every item listed on ebay will have an entry for each of the fields in the dictionary above. If there is no entry, then your dictionary must still have the associated key, and the value should be `None`.

PS.  This was a good question to ask, and I'm not trying to be flippant by quoting the instructions.  I'm just following the standard practice in the programming world of answering questions with references whenever possible.
