### ISSUE TITLE
hw03 quick question 

### ISSUE THREAD

**Issue by Vedant11-R** [mikeizbicki/cmc-csci040#155]
Professor for terms which have a space in the middle for example laptop stands, the url in the terminal im getting is `https://www.ebay.com/sch/i.html?_from=R40&_nkw=laptop stand&_sacat=0&LH_TitleDesc=0&_pgn=8&rt=nc` since there is a spce in the middle when i do command and click it opens up only laptop but when I copy paste the whole url mannually it opens up laptop stand. So is that fine or do i need to change something?

**Comment by mikeizbicki** [comment]
I'm not 100% sure about what your question is.  If it's about the behavior of CMD+click vs copy-and-paste, then this doesn't matter for your submission and the behavior will vary from computer to computer.  What matters is that you're able to type the command into the terminal properly and have your python program run correctly.

Does that answer your question?

**Comment by Vedant11-R** [comment]
yes professor, it does answer my question. Thank you
