### ISSUE TITLE
Reddit bot account reminder

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#157]
Tomorrow in class we will start some pretty technical details of working with reddit bots.  In order to follow along in class, you'll need to have followed steps 1-3 of the lab (https://github.com/mikeizbicki/cmc-csci040/tree/2021fall/hw_04/lab-PRAW#lab-instructions) to create an account.

To verify that your account is working correctly, you should create a `praw.ini` file and run the `monday_secX.py` file from class on Monday.  If that works, then you're good to go.

If you have trouble, I'll be available in my office ~30 minutes or so before class.  You can come by and troubleshoot.

**Comment by KaranGoel1** [comment]
Hi Professor,

I am trying to make the bot account on reddit, but it is asking for a "redirect URL". What should I put for that?

**Comment by mikeizbicki** [comment]
Quoting from the PRAW documentation at https://praw.readthedocs.io/en/latest/getting_started/authentication.html

> While script applications do not involve a redirect URI, Reddit still requires that you provide one when registering your script application – http://localhost:8080 is a simple one to use.

PS.  This is a great question, and I'm not trying to be flippant by posting a quote from the documentation.  It's standard practice in the programming world to answer questions with documentation when possible, and so I'm just following that practice.
