### ISSUE TITLE
Monday class

### ISSUE THREAD

**Issue by nataliephillips** [mikeizbicki/cmc-csci040#158]
Is there any chance you can put Monday's class on youtube? Thank you!

**Comment by mikeizbicki** [comment]
Eeek.  Very sorry I forgot to upload it earlier.  It's upload now, youtube is just doing some processing before it will be available.  Link: https://www.youtube.com/watch?v=-9PDy8B06BE&list=PLSNWQVdrBwoYFB5ZjbfBZUYApuvNrZpGL&index=19
