### ISSUE TITLE
Video From Monday Class

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci040#159]
Hi Professor,

I'm trying to watch the Monday lecture video, but there seems to be no audio. I tried watching a different lecture, and the audio was working. I was wondering if this was an uploading error or if it was supposed to get recorded without the audio?

**Comment by mikeizbicki** [comment]
Hmm... I'm very sorry about this.  I'm not sure what happened, but there is no audio and I can't add it back in.  My recommendation is to try watching today's video and if you have questions, we can meet to discuss the details.  All of the material from Monday was also covered today, just much faster.
