### ISSUE TITLE
Python Tutor

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci040#164]
Hi Professor Izbicki,

For 

    xs = [1, 2, 3]
    try:
      result = xs[3]
    except NameError:
      result = -1
    print('result=', result)

this generates an IndexError when I run Python Tutor step by step. But, when I click "Last", it gives me no error issue at the bottom and the output of xs as `[1,2,3]`. For the second scenario, I was wondering if Python Tutor defaults to automatically outputting the original list (in this case, at least) if the `except` is not the correct error?

**Comment by mikeizbicki** [comment]
Python tutor does this for all problems.  The last step discards any exceptions thrown, so you have to go to the next-to-last step(s) to see what the exception actually is.

Personally, I think that's a confusing design choice and I don't know why they did that, but that's the way it is :/
