### ISSUE TITLE
"Fake" top level comment 

### ISSUE THREAD

**Issue by HugoMatousek** [mikeizbicki/cmc-csci040#165]
Hello all, 
this might be a useful insight if you are manually checking your results for the praw lab (I checked this with the folks at the QCL - if there is anything else to it, please correct me, @mikeizbicki).
If you go to the [reddit page](https://old.reddit.com/r/BotTown/comments/qqmr8l/main_discussion_thread/) and collapse all the top level comments, you'll see one more than your script will show you. The reason is that one of the top level comments is not really a top level comment. Rather, it was a reply to another top level comment that was deleted but this reply was left intact. It seems to be a top level comment but it is not. Obviously, you still have to be careful about loading all the comments that are hidden, but this explains the difference of one top level comment that you can encounter. 

![image](https://user-images.githubusercontent.com/63810577/141722550-94783e2d-8a13-4e12-9ef6-71e3737dca06.png) ![image](https://user-images.githubusercontent.com/63810577/141722596-c4cee54d-a20e-471a-8837-ea8fd67ac923.png)

(the first image shows all the top level comments collapsed with the "fake" top level comment's content; the second image shows the top level comments' authors and the first 15 chars of their contents as obtained by the `praw` library - you can see that the "fake" top level comment is missing)

Hope this helps!

**Comment by mikeizbicki** [comment]
Thanks for pointing this out!

I have no idea who /u/cacan2020 is, but they've bad adding comments to the post.  So your numbers in the lab should be different than my example output, since your numbers will include their posts.
