### ISSUE TITLE
Lab Question

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci040#167]
Hi Professor,

I have a quick question. Is the `pprint` library required for this lab or is it ok to not import that and just use `print`? 

Thank you,
Sophia

**Comment by HugoMatousek** [comment]
Hello! 
I do have a similar question. Namely, I formatted my answers nicely using `print` and a `for` loop, so it does something like: `Redditor XXX: YY comment(s)`. Is this acceptable?
Thanks

**Comment by mikeizbicki** [comment]
The formatting of the output is unimportant.  The important thing is the numbers.  Nice formatting will be useful for you in the homework, however, while you're debugging.
