### ISSUE TITLE
HW00 Google Analytics

### ISSUE THREAD

**Issue by ZacDavis0-159910538** [mikeizbicki/cmc-csci040#17]
<img width="766" alt="Today google analytics" src="https://user-images.githubusercontent.com/70255063/92345372-f037fa00-f07d-11ea-932a-d5d5baabdffa.PNG">
<img width="794" alt="Yesterday google analytics" src="https://user-images.githubusercontent.com/70255063/92345378-f201bd80-f07d-11ea-8a15-d629052cb89c.PNG">
Google Analytics 1000+ page views in 48 hours.

**Comment by mikeizbicki** [comment]
Nice!

When you submit the assignment on sakai, can you also include these images.  That'll ensure that I don't forget about them when doing the grading.
