### ISSUE TITLE
HW4: Need to pick a politician?

### ISSUE THREAD

**Issue by wgalbreath** [mikeizbicki/cmc-csci040#174]
Hi Mike,

I know the instructions on the HW4 page say that we need to "create a reddit bot that posts messages about your favorite (or least favorite) politician." I thought I remembered in class you mentioning that it just has to be about politics in general, but do you want our sentences to be about one specific politician instead?

Thanks!

**Comment by mikeizbicki** [comment]
You can make your bot post about whatever you'd like.  The "about your favorite (or least favorite) politician" is just a suggestion.
