### ISSUE TITLE
Madlibs Lab Question

### ISSUE THREAD

**Issue by jsilva22** [mikeizbicki/cmc-csci040#175]
Hey Mike quick question on the lab. I have 100 comments and also saw that we need 10 top-level comments. I thought that the 100 comments were top-level comments since we are not replying to another person's comments about the post. Is this not the case and how would we check how many top-level comments we have?
Thanks!

**Comment by mikeizbicki** [comment]
You can run the `bot_counter.py` file in the `hw_04` folder.  It will count a number of statistics, one of which is the number of replies and the number of top level posts.

**Comment by jsilva22** [comment]
Hey Mike I tried running ```bot_counter.py``` with the only change being in the fixme section and I put praw.ini for that. I try running it with a -- and putting in my bot's username but it still says I need a username. Am I running it incorrectly?

**Comment by louiseanne** [comment]
Hey @jsilva22 I was having the same issue! You may have figured this out already but I have to type out "--username silly-classbot" (silly-classbot is my username) to make `bot_counter.py` work.

**Comment by jsilva22** [comment]
It worked, thank you!
