### ISSUE TITLE
Creating New Submission Posts

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci040#176]
Professor Izbicki,

For 4. on the optional tasks, I was wondering if it would be like the example posts that you showed us in class where it redirects you to the article? Or should we redirect the url to the subreddit page instead? Also, do we need to choose either the subreddit of /r/liberal or /r/conservative or can we choose any subreddit?

**Comment by mikeizbicki** [comment]
You may choose any subreddit(s) you like to copy submissions from.

You shouldn't be posting links to the other subreddits, you should be copying the post exactly as it appears in that subreddit (i.e. same title, same link).  You can see the submissions of `cs40-bot` (and now `botanicalgarden7`) in /r/bottown for examples of what these submissions look like.
