### ISSUE TITLE
Hw4 Question

### ISSUE THREAD

**Issue by nikhilagarwal1111** [mikeizbicki/cmc-csci040#178]
Hey Mike, hope you're having a good weekend. 

For the first task, I copied the code as you'd shown us in the lecture, but i keep getting the following message: AttributeError: 'MoreComments' object has no attribute 'author', for the line in which you specify if comment.author !='username'. It seemed to be working before, but when I try run it now I keep getting that exception. Is there any solution for this? Thanks

**Comment by yeswetran** [comment]
Hey friend! I ran into the same issue, and after [doing some searching](https://stackoverflow.com/questions/39840686/attributeerror-class-praw-objects-morecomments-has-no-attribute-body) as well as referring to our bot_stats project, I figured out that this might do the trick.

![image](https://user-images.githubusercontent.com/4709565/142804316-eb669275-7719-48f9-a02d-e91dd5f321f9.png)

**Comment by yeswetran** [comment]
Update: placed `submissions.comments.replace_more()` under task 5

**Comment by nikhilagarwal1111** [comment]
Thanks Nathan, solved the problem now!
