### ISSUE TITLE
office hours and madlib question

### ISSUE THREAD

**Issue by Vedant11-R** [mikeizbicki/cmc-csci040#182]
1) Will office hours take place tomorrow?
2) On the reddit page all my tweets are coming like `President Obama had a [PEACE_LOVING] [OUTLOOK]. He [HELPED] end war in Iraq. He [FORCED] all the [TROOPS] to leave Iraq` how can I fix this? I have used the replace function in my python file.

**Comment by mikeizbicki** [comment]
1. I will be available during the normal office hours time today.

2. You are using the `replace` function incorrectly.  See the dracula lab for the correct way to use it.
