### ISSUE TITLE
not_my_comments

### ISSUE THREAD

**Issue by nataliephillips** [mikeizbicki/cmc-csci040#184]
Somehow not my comment is not getting the correct numbers. I haven't changed anything from Tuesday's video or the code given to us. Do you have any advice?

**Comment by mikeizbicki** [comment]
Sorry, there's lots of different possible underlying problems here, so I can't say for sure.  My recommendation is to figure out which submission it works/doesn't work for, then try to find a pattern of what's causing it to work/not work.  You could try creating your own submissions with different sets of comments inside of it to nail down the exact pattern.
