### ISSUE TITLE
HW04 url 

### ISSUE THREAD

**Issue by Vedant11-R** [mikeizbicki/cmc-csci040#186]
Professors in the video you use the testing url for all the comments, in the final python file should the url be the testimg subreddit that we make or one pf the subreddits in BOTtown that you created.

**Comment by mikeizbicki** [comment]
The instructions state:
```
# FIXME:
# select a "home" submission in the /r/BotTown subreddit to post to,
# and put the url below
```
and #191 modifies this so that you may use any subreddit that begins with `/r/BotTown`.
