### ISSUE TITLE
class subreddit

### ISSUE THREAD

**Issue by nataliephillips** [mikeizbicki/cmc-csci040#188]
Is the class subreddit the BotTown link that was given to us? https://old.reddit.com/r/BotTown/comments/qr05je/practice_posting_messages_here/

**Comment by HugoMatousek** [comment]
It was the whole /r/BotTown. But it got banned a couple of hours ago (after my 5 bots posted over 500 comments :((). So, you can either use the subreddit /r/BotTown1 that is mentioned in issue #191 or wait for further instructions from Professor Izbicki. Also, for the majority of credit, you don't really need any particular subreddit. You can create your own (or use some playgrounds created by others) to test your code as that's what matter. The biggest problem with the subreddit banned is the optional tasks involving x valid comments (I suppose this will get revisited).

**Comment by mikeizbicki** [comment]
@HugoMatousek I've clarified in #191 that no optional tasks require working directly with the /r/BotTown subreddit.  You can use any subreddit you'd like that is designed for bots.
