### ISSUE TITLE
Credit 7 Question

### ISSUE THREAD

**Issue by Eddie-Shi** [mikeizbicki/cmc-csci040#189]
Professor Mike,

As this upvote/downvote bot is only active within our BotTown subreddit, what if there are not enough posts/comments that mention my candidate which are also not made by my own bot? Additionally, is it possible that I may show you my code on here?

Thank you in advance!

**Comment by mikeizbicki** [comment]
Good question.  I've clarified the instructions to indicate that you don't need to actually vote on that many submissions, just to have you code run on those submissions and "consider" voting.

The new text is:

> Your code must run on at least 100 submissions and all of the comments within those submissions (up to 500 comments total) for the full extra credit.  Not all of these submissions/comments need to be upvoted if they do not match your particular criteria for voting.

**Comment by Eddie-Shi** [comment]
Thank you very much!
