### ISSUE TITLE
New Temporary Subreddit

### ISSUE THREAD

**Issue by brandonsrho57** [mikeizbicki/cmc-csci040#191]
Hello Everyone! Because r/BotTown was just banned, I have created another subreddit for you all to post your comments into for the time being: https://www.reddit.com/r/BotTown1/

There is a 'Main Discussion Thread' for you there.

**Comment by zealotwithcharge** [comment]
I can't restart my bots right now. I did finish everything but i didnt record some stuff. What should I do? Will the deadline be extended?

**Comment by evankim08** [comment]
I believe the new subreddit got banned again.

**Comment by macroanton** [comment]
BotTown1 down

**Comment by Eddie-Shi** [comment]
BotTown1 is down again....

**Comment by brandonsrho57** [comment]
https://www.reddit.com/r/BotTown2/

**Comment by kevinm126** [comment]
Has anybody run their bot_counter.py since the crash. My numbers are significantly down.

**Comment by kyrilus** [comment]
> Has anybody run their bot_counter.py since the crash. My numbers are significantly down.
Yes, bot counter doesn't have a count anymore for me...

**Comment by evankim08** [comment]
Yes, all my comments from the banned subreddits have been wiped, which I believe restarts the comment counts

**Comment by kyrilus** [comment]
you can reset the reddit url code to r0yi9l and that should update your py program to scan the main Bottown2 discussion thread

**Comment by mikeizbicki** [comment]
My comments about the sub's banning:

1. It's not clear why the sub was banned.  Most likely, the sub was caught up in an over aggressive spam filter, but possibly someone's bot was posting inappropriate material.  I've contacted the reddit admins to clarify and get it unbanned, but we may or may not hear back.

1. Thanks, @brandonsrho57 for the new subs!

    Anyone else should feel free to make new subs to post into as well.  The only requirement will be that they start with the `BotTown` prefix.  You can, for example, create a sub just for yourself and your own private bot army to post in, if you'd like.

1. The `bot_counter.py` file will continue to work as before.  It find comments posted anywhere on reddit, and in particular it will count your comments posted into any sub.  Unfortunately, all of your previous comments have been deleted as part of the banning of /r/BotTown, so they won't count.  Maybe the sub will get unbanned, and you'll get those comment counts back, but you shouldn't count on it.

1. At this point, there is no extension on the assignment.  Part of the purpose of this assignment is to adapt to these types of unforeseen circumstances when running/writing your code.  If your code was correct before, it will still be correct now, and it's just a matter of letting it continue to keep running.

**Comment by zealotwithcharge** [comment]
I finished all the tasks but didnt record the output of some of the optional tasks. I don't think the assignment guide states how we should submit these optional tasks. Is it okay if we just give you our code or did we need to save the results of the code that checks if the optional task was completed? Also, i saved the output of my bot_counter.py before the subreddit was banned. Is it okay to submit that?

**Comment by mikeizbicki** [comment]
> I finished all the tasks but didnt record the output of some of the optional tasks. I don't think the assignment guide states how we should submit these optional tasks. Is it okay if we just give you our code or did we need to save the results of the code that checks if the optional task was completed?

Just code is fine.  If I have questions about the code working, I'll take a look at the actual user accounts to verify it worked.

Make sure to state in the README what optional tasks you completed so that I know to check for them when grading.

> Also, i saved the output of my bot_counter.py before the subreddit was banned. Is it okay to submit that?

Yep.  No need to rerun it.

----

PS.  In the future, filenames should be in single backtics like `bot_counter.py`.  Otherwise, you can get weird effects with special characters in the filename (like the `_` causing italics text).
