### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by kevinm126** [mikeizbicki/cmc-csci040#194]
Hi Mike I've had my program running all of today and 3 times I've received a 503 error. It says on the documentation that it may be something on Reddit's end. Is there any solution to this?

**Comment by HugoMatousek** [comment]
I don't think you can do much about it. 503 is generally unavailable service. For this particular task, I would just put the code into a `try except` statement, so it goes on despite the error. However, this might be greatly problematic if your code has other bugs. So I would recommend something like:
```
try:
    <code>
except Exception as e:
    print('Current error code + mesage: ' + str(e))
```
