### ISSUE TITLE
Bot counter/len(comments) issue?

### ISSUE THREAD

**Issue by louiseanne** [mikeizbicki/cmc-csci040#198]
Hi Mike! I seem to be having a problem with my `bot_counter.py` file. First, here's my `bot_counter.py` output, with a timestamp.
<img width="676" alt="Screen Shot 2021-11-26 at 8 23 59 AM" src="https://user-images.githubusercontent.com/89824785/143609908-9686eb27-348b-48d8-a6d7-d4c5580fecd8.png">

Here is my bot posting two valid comments - both of these posted correctly on the BotTown2 subreddit, the first as a TLC and the second as a reply. These are both valid comments that I found and checked on the subreddit to confirm they posted correctly.
<img width="453" alt="Screen Shot 2021-11-26 at 8 27 07 AM" src="https://user-images.githubusercontent.com/89824785/143610175-ed0e9175-6a72-411c-a6a2-0e14be324bc1.png">
<img width="449" alt="Screen Shot 2021-11-26 at 8 27 23 AM" src="https://user-images.githubusercontent.com/89824785/143610178-c98c97e3-72fc-4ac4-a1c8-189e1a69e5a9.png">

And this is what bot_counter.py returned shortly after those comments, and others, were posted. I cannot figure out why my `len(replies)` would have gone down, and even more confusing to me is the fact that the `len(comments)` is still 1000, and the `len(valid_comments)` is still 997.
<img width="743" alt="Screen Shot 2021-11-26 at 9 26 36 AM" src="https://user-images.githubusercontent.com/89824785/143615081-a8e68f76-6e11-4f9d-b9df-2e7c30fe0eab.png">

This is another `bot_counter.py` output that came out around awhile later (~10:30) after also running my bot for a little while longer, so at the very least my len(comments) should have gone up. 
<img width="811" alt="Screen Shot 2021-11-26 at 11 51 00 AM" src="https://user-images.githubusercontent.com/89824785/143625043-0875c783-a26f-4f08-8e1e-1a41f5ca5da3.png">

I don't have screenshots for this, but this is exactly what happened to my bot overnight. I checked the `len(comments)` at around 9pm last night and it was around 1000, ran my bot overnight, and nothing has changed. 

I'm not sure where to go from here - I'm aiming for the 1000 valid comments extra credit, but if `bot_counter.py` is not returning these values correctly I can't check my work. Unless my comments/submissions including my comments are getting deleted from bottown 2 in a perfect way as to make it so my `len(comments)` always stays at 1000, I believe this has to be a `bot_counter.py` problem. Let me know what you think I should do!

**Comment by shreyachatterjee22** [comment]
I'm having a similar issue! I got valid comments to hit 999 but after I ran my bot file for a bit longer my valid comments dropped to 997 and has remained stable since no matter how many comments are posted :/

**Comment by yeswetran** [comment]
I was worrying about this last night, but then I found [this explanation from last year's class!](https://github.com/mikeizbicki/cmc-csci040/issues/53) I would've shared it sooner, but you know, Thanksgiving and all. Hope it clears things up :)

**Comment by yeswetran** [comment]
I was worrying about this last night, but then I found [this explanation from last year's class!](https://github.com/mikeizbicki/cmc-csci040/issues/53)

My suggestion to @louiseanne: figure out which lines of code are causing the invalid replies and debug accordingly, so the invalid replies don't overtake the valid ones and mess up your count. Once you hit 1000, stop the bot and take a deep breath. That's right: you're finally free from Reddit.

I would've shared all this sooner, but you know, Thanksgiving lol. Hope it clears things up :)

**Comment by louiseanne** [comment]
Thank you @yeswetran ! This is really helpful. Clarifying question: I only have 3 invalid replies, so I don't think it's a code thing and instead is a case where someone deleted their comment, and now my past replies are invalid. If I keep running my code, theoretically will my newer valid comments eventually drown out the older ones? 

Thank you again!!

**Comment by kevinm126** [comment]
I'm having the same comment. I don't see any code that would create invalid replies either and my numbers are stagnant/ slowly dropping with each run of  `bot_counter.py`

**Comment by jennifersjlim** [comment]
Hi Mike! I also am having an issue with my comment counts . I've been running the bot.py file for several hours, but the valid_comments have rather gone down. 
I had 962 in total at noon, but now I'm stuck with 893, and it goes down the more I run the program.

**Comment by chatch166** [comment]
I'm also having these concerns... `bot_counter.py`'s output has been steady at 995 for some time, despite having run it well over the time needed to for it to produce five extra comments. I also don't see any place where invalid comments are being produced, and even if I were able to run it constantly between now and the due date tomorrow night to leave the invalid comments behind, there's no guarantee that some new comment wouldn't get deleted to render all those new comments ineffective. What should I do?

**Comment by aaryanb1** [comment]
I'm having this same issue wherein when my bot adds a valid_top_level_comment, its valid_reply count reduces by 1. Thus the valid_comments amount just stabilizes
