### ISSUE TITLE
1000 comment credit

### ISSUE THREAD

**Issue by Eddie-Shi** [mikeizbicki/cmc-csci040#200]
Professor Mike,

Since the r/BotTown was banned, I lost most of my progress in reaching 1000 comments (500 of them) and it seems like that I cannot make it in time. Is it possible you have an extension ONLY on this particular credit? Thank you in advance!

**Comment by derikkk** [comment]
Hi Mike, 

After BotTown got banned I lost about 900 valid comments- would we have to repost them again? And if the next subreddit gets banned again what should we do. Thank you.

**Comment by HugoMatousek** [comment]
Maybe a bit too late, but if you have at least some comments, it's still doable. I created my own subreddit, used one bot to create about 10 submissions, and then used a script controlling 5 bots to comment in those (you need probably at least three to ensure each bot will find a comment without their reply). I shuffled these bots and got down to about 1 comment / 60 seconds / bot (you could probably get even lower, I have not tried). This way you are almost guaranteed that your subreddit won't get banned (you could even make it private for your bots only).

Even if you don't do that, I think you should be able to post about 1 comment each 60 seconds. That would give you about 60 comments an hour, so about 300 till midnight. If you're lucky and your bots have been around for a couple of days and got some karma, then you can probably go to once comment each 30 seconds and easily post 500+ comments till the deadline (assuming, of course, no glitches).
