### ISSUE TITLE
ListingGenerator Error

### ISSUE THREAD

**Issue by chatch166** [mikeizbicki/cmc-csci040#201]
Is anyone else getting an error saying `AttributeError: 'ListingGenerator' object has no attribute 'title'`?

I'm pretty certain the program is selecting some kind of submission called `ListingGenerator`, and running into problems when it tries to comment or reply to comments on this selection, as it's not an actual submission to the subreddit. Is anyone else having this problem? Any ideas what I should do?

**Comment by HugoMatousek** [comment]
Use the listing generator in the `for` loop. Something like this:
```
for each in YourListingGeneratorObject:
    print('titile= ', each.title
```
(if you want to get the title. It's quite stupid, that it doesn't give you a list of submissions/comments, but this thing instead. If you want to turn this into a list where you can call different items by their index, create an empty list instead and use `list.append(each)` in your `for` loop instead.

//There might be a better solution, but that depends on what exactly you are trying to do. This should be fairly universal.
