### ISSUE TITLE
SQL fiddle down

### ISSUE THREAD

**Issue by kevinm126** [mikeizbicki/cmc-csci040#205]
Hi everyone not sure if anyone is studying for the quiz right now but I believe sql fiddle is down as I'm getting an error on all my devices that says this page isn't working.

**Comment by louiseanne** [comment]
@yeswetran found a website that does the same thing as sqlfiddle and it works well! Look here: https://github.com/mikeizbicki/cmc-csci040/issues/204#issuecomment-983342913
