### ISSUE TITLE
Final quiz details

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#206]
According to the syllabus, we are scheduled to have a final quiz next week worth 20 points.  In order to reduce your all's workload/stress, I'm giving you an optional, alternative assignment that you can choose to complete instead of the quiz.

The optional alternative is posted at <https://github.com/mikeizbicki/cmc-csci040/tree/2021fall/lab-wardialing>.  It is a lab-style assignment similar in difficulty and style to the password cracking lab.  The standard lab collaboration policy will apply (so you may work with other students and talk with TAs).  If you complete the assignment, you are basically guaranteed a 20/20 for your final quiz grade.  For most students, I think this lab will take less time than studying for a comprehensive quiz and result in a better grade.

I'm guessing most students will choose to complete this lab instead of doing an in person traditional quiz, and therefore we won't be having a final quiz during our normal class hours.  Instead, if you choose to do the traditional quiz, then you will have to schedule a time with me during finals week to complete it.  (The normal final exam period for our class would be fine.)  The format of the traditional quiz will be 10 questions covering material from all of the previous quizzes we've done in class.

**Comment by HugoMatousek** [comment]
Hello Mike, when is this due?

**Comment by mikeizbicki** [comment]
Due date for either version is the last day of finals week: Friday, 17 December.
