### ISSUE TITLE
War-dialing from lab computers

### ISSUE THREAD

**Issue by louiseanne** [mikeizbicki/cmc-csci040#207]
In the instructions you mention using lab computers for the war-dialing lab. By lab computers are you referring to the lab near your office? Or would any lab/library computer work?

**Comment by mikeizbicki** [comment]
Any lab computer should be fine.

I'm not sure exactly how IP addresses are assigned on other campuses, but it definitely won't be a problem if there's no one else working on it at the same time in the lab, and 99% won't be a problem even if there is.
