### ISSUE TITLE
Tutoring Schedule During Finals Week (Dec 13 - 17th) 

### ISSUE THREAD

**Issue by derikkk** [mikeizbicki/cmc-csci040#212]
Hi Mike, 

Assuming that we still have tutoring, what's the schedule going to look like next week during finals? Thanks. 

Best, 
Derik

**Comment by mikeizbicki** [comment]
Great question.  @eburke21, @joeybodoia, @Tonnpo, @brandonsrho57, and @ohorban can you all chime in with your availability during finals week?

**Comment by ohorban** [comment]
QCL is open for walk ins this week. Starting Sunday there will be no walk ins but you can make a 1on1 appointments with me. Additionally, if many of you still need help i might host some group sessions. Feel free to contact me at ohorban24@cmc.edu

**Comment by brandonsrho57** [comment]
Yes! I will be available during finals week! If I am busy, I will make sure to update everyone on Github or post my availability!

**Comment by eburke21** [comment]
I'm cancelling my office hours for this week and next week but I'll be at walk-in hours on Thursday and Sunday! If anyone has questions that pop up throughout the week, email them to me at eburke21@cmc.edu or post them here.

**Comment by joeybodoia** [comment]
My tentative availability for next Monday will be from 6-7pm instead of 6-8pm. Additionally, the meeting will have to take place via Zoom. I will post a link in this thread prior to the meeting time. If anything changes I will update everyone on Github.

**Comment by Tonnpo** [comment]
I apologize for the late notice. My office hour for this week will change from **Sunday 6-8pm** to **Saturday (Dec. 11th) 9-11am**. If anyone has questions during the final week, please feel free to email me at tpothis@students.pitzer.edu.

**Comment by nrj-demello** [comment]
Hi @joeybodoia, are you still having your office hours between 6-7 pm tonight?

**Comment by joeybodoia** [comment]
@nrj-demello I'm sorry I completely forgot to update this thread. I will not be able to host office hours today due to other obligations. I'm for the inconvenience.
