### ISSUE TITLE
Week_13 lab question

### ISSUE THREAD

**Issue by jennifersjlim** [mikeizbicki/cmc-csci040#213]
![image](https://user-images.githubusercontent.com/89895193/144964899-72d96ecd-96ee-4c96-baae-58b94f2a8570.png)

Hi Mike, 
I'm having this error whenever I execute my lab.py. Is there a way to find out why this might be happening? Thank you

**Comment by Tonnpo** [comment]
I would suggest you check the line 37 in `lab.py`  because of this message
```
return render_template('main.html', messages=messages)
```
and also the line 5 in `main.html` because of this message
```
{% for key, value in result.items() %}
```
Furthermore, the error said that your `result` is undefined. So, I would check this variable as well.
