### ISSUE TITLE
week 13 lab - service error question

### ISSUE THREAD

**Issue by christinakulick** [mikeizbicki/cmc-csci040#215]
Hi, I was curious if anyone has run into the 500 internal service error issue and how they fixed it. I am receiving this error on my lab:

<img width="1045" alt="Screen Shot 2021-12-07 at 10 18 55 PM" src="https://user-images.githubusercontent.com/89888289/145158366-25b89241-3126-4155-b37b-9730b7c0f8de.png">

And my link leads me to this page: 

<img width="1430" alt="Screen Shot 2021-12-07 at 10 19 40 PM" src="https://user-images.githubusercontent.com/89888289/145158466-bc7dd752-010a-450a-b30d-9134628bc1be.png">

Please let me know! thank you :)

**Comment by Tonnpo** [comment]
I believe the error could be related to your `cur` variable according to the message 
```
AttributeError: 'builtin_function_or_method' object has no attribute 'execute'
```
which also could relate to how you connect with database file.

Hope this helps!

**Comment by christinakulick** [comment]
That begins to help! I am also getting this error with the db_create.py file (directly downloaded and not altered): 

<img width="797" alt="Screen Shot 2021-12-07 at 10 50 16 PM" src="https://user-images.githubusercontent.com/89888289/145162022-3cb63a29-f901-4d33-b097-a1e6336f6220.png">

Is there something I need to install in the terminal to make this work?

**Comment by jaceycarter** [comment]
Are you sure all your folder names are correct? That may have something to do with the error you are receiving.

**Comment by Tonnpo** [comment]
> That begins to help! I am also getting this error with the db_create.py file (directly downloaded and not altered):
> 
> <img alt="Screen Shot 2021-12-07 at 10 50 16 PM" width="797" src="https://user-images.githubusercontent.com/89888289/145162022-3cb63a29-f901-4d33-b097-a1e6336f6220.png">
> 
> Is there something I need to install in the terminal to make this work?

Assuming that you ran `db_create.py` before, the error basically tells that you already have the `users` table. So, I believe there is no need to install anything.
