### ISSUE TITLE
Last Lecture Video

### ISSUE THREAD

**Issue by tkapoor22** [mikeizbicki/cmc-csci040#22]
Hi Mike, 

Would you be able to upload the recording for Monday's lecture?

Thank you!

**Comment by HoangChu-Claremont** [comment]
Also @mikeizbicki can you please record Wednesday's lecture this week as well?

**Comment by mikeizbicki** [comment]
See https://github.com/mikeizbicki/cmc-csci040/issues/2#issuecomment-689709758
