### ISSUE TITLE
HTML displaying on the page/9pt extra credit task question

### ISSUE THREAD

**Issue by louiseanne** [mikeizbicki/cmc-csci040#223]
Hi Mike! I'm working on the 9pt extra credit task about accepting markdown formatting in our messages. I'm able to type messages with markdown formatting and they get converted to HTML, as you can see here:

<img width="1371" alt="Screen Shot 2021-12-12 at 11 00 16 AM" src="https://user-images.githubusercontent.com/89824785/145725758-40ad1cfe-cae0-4d27-994b-01e067d04bdc.png">

I'm just a little unsure of where to go from here in terms of getting the html message to display correctly on the page. I can get the html to go back to plain text using BeautifulSoup, but that's not the right next step. I've been trying to google this but am not getting anywhere. Any suggestions/hints/tips on where to go from here?

**Comment by zealotwithcharge** [comment]
1. I don't think the <html><head><body> tags are appropriate for individual messages. From my understanding, those tags are usually used once to denote sections of code.
2. For Jinja2, I think you have to specify that the string you have is safe or else the html tag automatically gets escaped. Try adding the safe filter to the string of the message. (I.E. if your variable for the message looks like `{{message}}` change it to `{{message|safe}}`. Be aware that this means that Jinja2 expects you to both clean `message` and to make sure that it is safe.)

**Comment by louiseanne** [comment]
That worked, thank you so much!
