### ISSUE TITLE
Office Hours During Finals Week

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci040#224]
Hi Mike,

I was wondering if you would be holding your regular office hours during finals week? 

Best,
Sophia

**Comment by nrj-demello** [comment]
Hi Mike,

Does this mean you will be available on Thursday?

Thanks,
Nic

**Comment by mikeizbicki** [comment]
@nrj-demello I'm available for hw demos at 9am Thursday (see https://github.com/mikeizbicki/cmc-csci040/issues/216#issuecomment-995055475), but I'm sorry I won't have time to host a more general office hours session for questions.
