### ISSUE TITLE
War Dialing

### ISSUE THREAD

**Issue by ltgoldberg** [mikeizbicki/cmc-csci040#225]
Hi, when my code reaches 641 out of 1024 it gets a connection error. I tried changing my code and the range but I still get the error. I know my computer isnt sleeping because I am using it when it happens.

Thanks,
LT

**Comment by ltgoldberg** [comment]
Hi, when my code reaches 641 out of 1024 it gets a connection error. I tried changing my code and the range but I still get the error. I know my computer isnt sleeping because I am using it when it happens. 

Thanks, 
LT

**Comment by mikeizbicki** [comment]
It's not clear to me exactly what your question is, but they way to deal with exceptions is to catch the exception with a `try`/`except` block.
