### ISSUE TITLE
War Dialing

### ISSUE THREAD

**Issue by jsilva22** [mikeizbicki/cmc-csci040#226]
Hey Mike, 2 quick questions on the lab. I got 16 ips in separate runs, the first one run stopped around halfway and I continued from where it stopped to get the remaining ips. For submitting, is it fine if I hard code them into a single list since I already know what they are from the for loop I ran? Or can we also just list the ips individually and not create an actual list of them? My second question is can a way of checking also be seeing if we got the same ips as other students or will people have different ips?
Thanks

**Comment by mikeizbicki** [comment]
> is it fine if I hard code them into a single list since I already know what they are from the for loop I ran? Or can we also just list the ips individually and not create an actual list of them?

All I care about are the IPs.  Format them however you'd like.

> My second question is can a way of checking also be seeing if we got the same ips as other students or will people have different ips?

Everyone will get the same IPs because they are universal for everyone on the internet.
