### ISSUE TITLE
Create__user question

### ISSUE THREAD

**Issue by milesba4** [mikeizbicki/cmc-csci040#228]
Hello Professor,

I have two questions:

1. I'm trying to add a created username to the SQL database if the username doesn't exist and am wondering if I am doing it correctly.  is there a way to check if the username is added to the database?  Am I on the right track?
<img width="725" alt="Screen Shot 2021-12-15 at 1 08 13 AM" src="https://user-images.githubusercontent.com/90070112/146157404-1690fe8d-4ffc-462f-83e4-f8c353004ed2.png">

2. every time I type something into the forms on the create user webpage it takes me back to the login webpage, but I'm not sure why this problem is occurring. My render template is connected to my create_user HTML file.

**Comment by milesba4** [comment]
This is my is_valid_user function

<img width="643" alt="Screen Shot 2021-12-15 at 9 17 09 AM" src="https://user-images.githubusercontent.com/90070112/146233860-02302fde-cd9b-46f8-9e6c-4ba6191bee1e.png">

**Comment by mikeizbicki** [comment]
> is there a way to check if the username is added to the database?

There are multiple ways:  First, you can manually inspect the database contents (e.g. using the `sqlite3` command or the `db_access.py` file).  Second, you try logging in with the user that you just created.  The second method is how I will be testing your code.

> every time I type something into the forms on the create user webpage it takes me back to the login webpage

You should review the html form's `action` attribute here: https://www.w3schools.com/tags/att_form_action.asp and make sure it is set correctly.

**Comment by milesba4** [comment]
Thank you, is there a source I can look at for creating a form for the confirm password table?

**Comment by Tonnpo** [comment]
Hi @milesba4 

Could you elaborate more on how you expect the confirm password to work vs what it is currently doing?

Thanks!

**Comment by milesba4** [comment]
Hi Ton,

The confirm password form is put in place so that the user doesn't accidentally create an unintended password in the scenario that they make a typo when creating it. Im trying to make it so that the user must type in the same word in the confirm password form that they typed in the create password form in order to successfully create an account. Once they do that same create_username and create_password is added to the SQL database so that they can login

**Comment by milesba4** [comment]
To specify, my issue is that when the user types something into the confirm_password form, it is returning that they typed nothing in the confirm_password form instead of returning the word that they input.

**Comment by mikeizbicki** [comment]
There's no code provided that has a password confirmation field in the form.  You need to get that part working on your own.

The HTML/python code that you've included above looks fine to me.  So whatever the problem is, I don't think it's in those lines of code.  Sorry I can't be of more help.
