### ISSUE TITLE
Created Messages

### ISSUE THREAD

**Issue by macroanton** [mikeizbicki/cmc-csci040#229]
So created messages do post, only it creates one for every user ever created.
Was wondering if cookie specification could help, or something else?

<img width="845" alt="image" src="https://user-images.githubusercontent.com/89937621/146328578-a5fbb3f9-8047-4223-8a90-5acbd93f8ed9.png">

<img width="233" alt="image" src="https://user-images.githubusercontent.com/89937621/146328721-68950acc-f3f6-4453-ab59-2920c3d261cc.png">

**Comment by mikeizbicki** [comment]
Hmm... I don't see any obvious problems with your code, but you should check the actual contents of the database (using e.g. the `db_access.py`) command to verify that you're actually posting three messages, and not just displaying three messages incorrectly in your root route.

**Comment by macroanton** [comment]
<img width="1300" alt="Screen Shot 2021-12-16 at 12 56 56 PM" src="https://user-images.githubusercontent.com/89937621/146431887-079316b1-3113-4901-9d1d-b6870cf853cf.png">
?
