### ISSUE TITLE
Google analytics using CMC email

### ISSUE THREAD

**Issue by fjennison22** [mikeizbicki/cmc-csci040#238]
I think our ability to set up a Google analytics account may be restricted by the @cmc.edu administrators. When I try to set it up it takes me to a link which produces a blank page

**Comment by mikeizbicki** [comment]
I believe you should be able to do this fine with a cmc email.  I can take a look tomorrow in person during lab.

**Comment by dwalker25** [comment]
Working remotely from Covid isolation housing. I'm having the same problem as @fjennison22. Did this get fixed? Thanks

**Comment by mikeizbicki** [comment]
@dwalker25 It seems that CMC just recently added this restriction to student email accounts for some reason, and so you'll have to use a non-CMC email to setup google analytics.
