### ISSUE TITLE
Lab00 update

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#239]
1. Lab 00 is "nominally" due this Sunday (4 Sep) or Tuesday (6 Sep) if you collaborate.  Since this is the first week, there won't be a late penalty applied if you don't make those deadlines.

2. For those of you who don't have enough stars/likes, feel free to use this github issue to communicate with other students and trade stars/likes.

**Comment by mikeizbicki** [comment]
Also, the lab submission form should be visible on sakai now :)

**Comment by Kevinl0378** [comment]
Can you guys like and star my website and webpage? I'll like and star yours as well. Website: https://kevinl0378.github.io/,  Webpage's repo: https://github.com/Kevinl0378/kevinl0378.github.io

**Comment by jadersaunders** [comment]
Please like and star my website & webpage too! I'll do the same for you! https://jadersaunders.github.io/ and https://github.com/jadersaunders/jadersaunders.github.io .  Thank you!

**Comment by henrylong612** [comment]
Webpage: https://henrylong612.github.io/
Repo: https://github.com/henrylong612/henrylong612.github.io

Thank you!!!

**Comment by AjaiKBan** [comment]
Webpage: https://ajaikban.github.io/
Repo: https://github.com/AjaiKBan/AjaiKBan.github.io

**Comment by adamzterenyi** [comment]
Webpage: [https://adamzterenyi.github.io/] (url)
Repo: [https://github.com/adamzterenyi/adamzterenyi.github.io](url)

**Comment by Stephanie-Espinoza** [comment]
Webpage: https://stephanie-espinoza.github.io/ 
Repo: https://github.com/Stephanie-Espinoza/Stephanie-Espinoza.github.io

Thank you!:)

**Comment by chasekeir** [comment]
Webpage: https://chasekeir.github.io/
Repo: https://github.com/chasekeir/chasekeir.github.io

Please give it a like and I'll do the same!

**Comment by henrylong612** [comment]
My repo is fully starred, but I would appreciate a few more likes on my [webpage](https://henrylong612.github.io/)! Thank y'all in advance!

**Comment by xutimon** [comment]
Webpage: https://xutimon.github.io/
Repo: https://github.com/xutimon/xutimon.github.io

Appreciate yall. I will like and star everyone above and below.

**Comment by adamzterenyi** [comment]
My repo is also sufficiently starred, but I'd be grateful if you guys could **SMASH** that like button on my [webpage](https://adamzterenyi.github.io/). Thank you!

**Comment by davidhlee625** [comment]
same! for the [website](https://davidhlee625.github.io/) please

**Comment by justin-is-away** [comment]
website: https://justin-is-away.github.io/
repo: https://github.com/justin-is-away/justin-is-away.github.io

**Comment by dwalker25** [comment]
Webpage: https://dwalker25.github.io/
Repo: https://github.com/dwalker25/dwalker25.github.io

thanks everyone

**Comment by taylordaetz** [comment]
Website: https://taylordaetz.github.io/
Repo: https://github.com/taylordaetz/taylordaetz.github.io

Thanks!

**Comment by JackPotter7** [comment]
Hey Mike! I received 5 likes on my webpage and submitted via Sakai on Friday. I checked my website again today and it seems I lost a like somehow. Should I resubmit my webpage once I receive a fifth like? @mikeizbicki 

Help with my last like would also be appreciated: https://jackpotter7.github.io/

**Comment by xristinazogopoulou** [comment]
Hi Mike,

I finished my website but the like and confirm shows up in Greek. I don't know how to change that and it makes it harder for people to understand what they should press. Let me know if we can meet anytime on Tuesday or if there is something I can do to fix it.

**Comment by rpassi** [comment]
Hi everyone! 
My website is - https://rpassi.github.io/
and repo is -- https://github.com/rpassi/rpassi.github.io

Appreciate taking the time to like/star!

**Comment by maguizler** [comment]
Hi folks! 

My website is: [https://maguizler.github.io/]

and the repo is: [(https://github.com/maguizler/maguizler.github.io)]

Please like/star my pages and I will make sure to like/star yours as well 👍  Have a good long weekend!

**Comment by Stephanie-Espinoza** [comment]
Hi everyone! I have 5 likes already but would appreciate it if you all could star my repo. Thanks in advance:)

Repo: https://github.com/Stephanie-Espinoza/Stephanie-Espinoza.github.io

**Comment by xristinazogopoulou** [comment]
Hey guys please please like website and star my repooo :)))

My website is: https://xristinazogopoulou.github.io/
Repo: https://github.com/xristinazogopoulou/xristinazogopoulou.github.io

**Comment by Raymond6688** [comment]
Hi guys,
My web: https://raymond6688.github.io/
repo: https://github.com/Raymond6688/Raymond6688.github.io
I really appreciate your help!

**Comment by jasminextan** [comment]
hi 

repo: https://github.com/jasminextan/firstwebpage
web: https://jasminextan.github.io/firstwebpage/home/
