### ISSUE TITLE
Doctest no longer running in terminal

### ISSUE THREAD

**Issue by Yugi00** [mikeizbicki/cmc-csci040#24]
I have now ran into an issue where my doctests aren't running anymore, but instead come up with an error. Any solutions?

PS C:\Users\jyep0> $ python3 -m doctest --verbose lab.py
$ : The term '$' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ $ python3 -m doctest --verbose lab.py
+ ~
    + CategoryInfo          : ObjectNotFound: ($:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mikeizbicki** [comment]
You shouldn't type the `$` as part of the command.  The `$` indicates that everything that is after it gets entered in the terminal.

**Comment by Yugi00** [comment]
I left it out this time, but now it did not give any output.

python3 -m doctest --verbose lab.py is what I put into the terminal.

**Comment by mikeizbicki** [comment]
We should meet during office hours so I can see what's going on.

Also, I've granted everyone a 48 hour grace period to resubmit (#27), so you can submit without a late penalty if you get this fixed.
