### ISSUE TITLE
Week 01 lab

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#242]
Reply to this comment with the twitter screenshot you took for the topic_01 lab. You can include images in your comments by dragging and dropping.

**Comment by fjennison22** [comment]
<img width="607" alt="Screen Shot 2022-09-08 at 7 42 38 PM" src="https://user-images.githubusercontent.com/112418830/189261340-347fb417-02f4-4fbf-b3ae-1f858b4f8ade.png">

**Comment by adamzterenyi** [comment]
<img width="594" alt="Screenshot 2022-09-09 at 9 38 17 AM" src="https://user-images.githubusercontent.com/112423622/189399292-aaa1c564-f0dc-432d-b8ef-6a56d56c9fe7.png">

**Comment by jasminextan** [comment]
<img width="602" alt="Screen Shot 2022-09-09 at 9 43 16 AM" src="https://user-images.githubusercontent.com/112445202/189400074-5fe21f4c-5dac-477b-81a6-b7fa9ec804ed.png">

**Comment by rpassi** [comment]
<img width="717" alt="Screen Shot 2022-09-09 at 10 33 17 AM" src="https://user-images.githubusercontent.com/112538914/189410802-da9ce103-c324-4dfc-9204-e0c80f87c1c7.png">

**Comment by ben-smith23** [comment]
![Screenshot 2022-09-09 093833](https://user-images.githubusercontent.com/112433581/189399500-08f10ad0-c904-481f-93ce-65ae66d0c3bb.png)

**Comment by jadersaunders** [comment]
<img width="589" alt="tweet" src="https://user-images.githubusercontent.com/112446611/189411468-ab8e0591-5ed1-4bc6-89cf-53aa1335cf26.png">

**Comment by davidhlee625** [comment]
<img width="601" alt="Screen Shot 2022-09-09 at 10 38 03 AM" src="https://user-images.githubusercontent.com/112444682/189411809-0ebee44f-3bbc-4aa3-b622-d8172580f9f6.png">

**Comment by Raymond6688** [comment]
<img width="608" alt="Screen Shot 2022-09-09 at 10 42 09 AM" src="https://user-images.githubusercontent.com/112432316/189412204-214ea480-66cf-4832-a026-0d168ea6045e.png">

**Comment by taylordaetz** [comment]
<img width="580" alt="Screen Shot 2022-09-09 at 10 44 37 AM" src="https://user-images.githubusercontent.com/112423048/189412894-7bc6a6b4-f15f-4470-872f-d09e92165bce.png">

**Comment by PArellano02** [comment]
<img width="603" alt="Screen Shot 2022-09-09 at 10 44 35 AM" src="https://user-images.githubusercontent.com/112423121/189413069-7f11a533-595c-434a-bf3b-25393b863e2c.png">

**Comment by JackPotter7** [comment]
<img width="596" alt="Screen Shot 2022-09-09 at 10 47 40 AM" src="https://user-images.githubusercontent.com/112518435/189413109-74ead372-0ba7-44d8-bb2e-7c375871a954.png">

**Comment by henrylong612** [comment]
<img width="603" alt="Screen Shot 2022-09-09 at 10 47 39 AM" src="https://user-images.githubusercontent.com/76542049/189413219-85d7cb99-0ec9-4142-8f0c-0cc39dee8d4e.png">

**Comment by jacksonaldrich** [comment]
<img width="599" alt="Screen Shot 2022-09-09 at 10 50 21 AM" src="https://user-images.githubusercontent.com/112573673/189413529-b42b2042-62f5-4e0d-804b-c23520ef8c98.png">

**Comment by xutimon** [comment]
![jidion](https://user-images.githubusercontent.com/89937813/189413646-d09ab63a-376c-4ea4-bcaf-205d9001c0b0.jpg)

**Comment by AjaiKBan** [comment]
![Intro to Hacking Second Lab](https://user-images.githubusercontent.com/107370922/189414018-5c4bcd75-5c48-4687-8b44-6f30030f98d3.jpg)

**Comment by Kevinl0378** [comment]
![Screen Shot 2022-09-09 at 11 20 06 AM](https://user-images.githubusercontent.com/112463765/189418599-29998647-0503-428e-a974-fee0fb25b66f.png)

**Comment by dwalker25** [comment]
![twitterhack](https://user-images.githubusercontent.com/112443814/189419718-5653abb1-38c3-4703-8659-6e7a753c07b9.jpg)

**Comment by justin-is-away** [comment]
![image](https://user-images.githubusercontent.com/19355638/189439350-ec4fa713-5d4d-47b8-9aa9-bfb79990b811.png)

**Comment by cyrusg645** [comment]
![image](https://user-images.githubusercontent.com/112539442/189440338-60da48a2-c7fa-4559-a66f-977de4fce6f0.png)

**Comment by JustinOngchin** [comment]
<img width="594" alt="Screen Shot 2022-09-09 at 2 40 06 PM" src="https://user-images.githubusercontent.com/112526742/189449759-cf39e337-5870-4c4e-9323-f44b641f0c0e.png">

**Comment by xristinazogopoulou** [comment]
![Screenshot (519)](https://user-images.githubusercontent.com/112522590/189449835-23255f33-ba7f-4402-8769-31c8b052940e.png)

**Comment by Kal2025** [comment]
![Screenshot (59)](https://user-images.githubusercontent.com/112449375/189457007-b63681c2-e618-4d13-8c70-5f15edcc68ad.png)

**Comment by chlol3912** [comment]
`<img width="473" alt="Screen Shot 2022-09-09 at 5 27 43 PM" src="https://user-images.githubusercontent.com/113218935/189461633-068995f6-8398-4904-8944-c0ab356114c4.png" />`

**Comment by Stephanie-Espinoza** [comment]
<img width="590" alt="Screen Shot 2022-09-11 at 6 46 32 PM" src="https://user-images.githubusercontent.com/112435762/189560217-55dff7d3-e9e9-40fb-8a0b-eec17bdaadc2.png">

**Comment by chasekeir** [comment]
<img width="596" alt="Screen Shot 2022-09-12 at 4 30 51 PM" src="https://user-images.githubusercontent.com/112430451/189775923-a683a7ec-0e22-4c06-b17d-25c6963b4bb8.png">

**Comment by salvadorleon123** [comment]
<img width="585" alt="Screen Shot 2022-09-12 at 7 18 12 PM" src="https://user-images.githubusercontent.com/112513834/189792988-a2bdf057-6618-445d-b59a-2ce3e625d9be.png">

**Comment by buffeinstein** [comment]
![Screen Shot 2022-09-14 at 12 24 07 AM](https://user-images.githubusercontent.com/108768418/190088481-506f2293-753c-4c24-86c9-b44a8e92593d.png)

**Comment by maguizler** [comment]
<img width="477" alt="Screen Shot 2022-09-28 at 8 01 41 PM" src="https://user-images.githubusercontent.com/112537518/192929144-5a92111f-e73f-4785-a9c8-c35ef530bdff.png">
