### ISSUE TITLE
project_00

### ISSUE THREAD

**Issue by justin-is-away** [mikeizbicki/cmc-csci040#244]
When you say:

> At least one HTML file must:
- >  be named index.html
- >  contain a "follow" link to the course webpage (https://github.com/mikeizbicki/cmc-csci040) and a "follow" link to Mike Izbicki's personal webpage (https://izbicki.me/)
- > I want that sweet, sweet pagerank...
- >  contain either an unordered or ordered list (<ul> or <ol>) with at least 3 list items (<li>)
- >  contain a table with at least 3 rows and 3 columns

Does this mean that all of these conditions have to be on the same HTML file, or can they be spread out between all of our HTML files?

**Comment by JackPotter7** [comment]
Hi mike, two questions:

What do you mean by this line? 
"have at least two "follow backlinks" from other domains (other student's projects are okay)"

And would inspecting element be considered a black hat technique?

**Comment by mikeizbicki** [comment]
@justin-is-away Those conditions do not have to all be in the same html file, they just have to be in your project somewhere.

@JackPotter7 I've updated the project instructions with a link that explains the details of follow backlinks (and the SEO prelecture videos also cover this term), but it's basically a link from another website to your website.  Google will use those links to determine how important your webpage is and how high in the search rankings it should be.  The more backlinks you have, the higher you will appear in google search results.

**Comment by henrylong612** [comment]
Hi Mike! If we have more than 3 pages in our site, do all of them need to satisfy the "Every HTML file must:" requirements, or just 3?

**Comment by mikeizbicki** [comment]
@henrylong612 Only 3 of them need to satisfy the requirements.  You're welcome to have as many other pages as you like that contain whatever you want, and they don't need to satisfy any requirements.

**Comment by justin-is-away** [comment]
Is Wayback Machine not displaying the FB like count for anyone else? First image is from [my actual website](https://justin-is-away.github.io/), second image is [Wayback Machine's snapshot](https://web.archive.org/web/20220911192653/https://justin-is-away.github.io/).
![image](https://user-images.githubusercontent.com/19355638/189546092-07878294-57ba-415a-b09d-ccd21dfd4731.png)
![image](https://user-images.githubusercontent.com/19355638/189546102-e131c6b6-5186-45b0-8723-44af3a4285fd.png)

**Comment by justin-is-away** [comment]
Is Wayback Machine not displaying the FB like count for anyone else? First image is from [my actual website](https://justin-is-away.github.io/), second image is [Wayback Machine's snapshot](https://web.archive.org/web/20220911192653/https://justin-is-away.github.io/).
![image](https://user-images.githubusercontent.com/19355638/189546092-07878294-57ba-415a-b09d-ccd21dfd4731.png)
![image](https://user-images.githubusercontent.com/19355638/189546102-e131c6b6-5186-45b0-8723-44af3a4285fd.png)

**Comment by xutimon** [comment]
Hi Mike! 

I was just wondering if we should use a distinct google analytics tag for each HTML file we have, as Google mentions that a single web stream would be enough. I was also wondering if the class and id selectors in our CSS external file need to be actually used by any of our HTML files, or is simply identifying them enough. Thanks!

**Comment by xutimon** [comment]
Also if anyone could backlink me I would really appreciate it! My link is xutimon.github.io

I will also help backlink you alls webpage if you guys need it, just write your link below. Thanks!

**Comment by mikeizbicki** [comment]
@xutimon 

1. You should use the same google analytics tag for each HTML file.
1. The CSS selectors' classes/ids should be used somewhere in the HTML.

**Comment by JackPotter7** [comment]
Hi @mikeizbicki,

Do we need to do the internet archive for each html page we have or just the main page? Thanks!

**Comment by mikeizbicki** [comment]
@JackPotter7 You should archive each html file.  You'll only need to submit the archive link to the main page, then I can press the links on the archive to view the other pages.

**Comment by AjaiKBan** [comment]
Good morning @mikeizbicki ,

For the 3 <div> tag requirement on each HTML file, does there need to be three different class or id selectors?

**Comment by AjaiKBan** [comment]
3  div tag requirement

**Comment by mikeizbicki** [comment]
@AjaiKBan There is no requirement that the `div` tags have any class or id attributes.  The requirement for class/id selectors can be met by applying them anywhere.

**Comment by AjaiKBan** [comment]
Thank You @mikeizbicki !

**Comment by dwalker25** [comment]
Hi Mike, I'm not enrolled in the class Sakai -- could you please add me? Thanks, David Walker

**Comment by buffeinstein** [comment]
Hi @mikeizbicki, 

I submitted my github repo to Sakai, following the instructions that were listed in Sakai. I can't edit that submission, so I'll paste the 2 links here:

link to my website: https://buffeinstein.github.io/

link to the internet archive: https://web.archive.org/web/20220914031407/https://buffeinstein.github.io/
