### ISSUE TITLE
Practice Quiz Answer Keys

### ISSUE THREAD

**Issue by fjennison22** [mikeizbicki/cmc-csci040#245]
Hi Prof. Mike, 

Is there somewhere we can the find the answer keys to the practice quizzes you handed out in class? Thank you!

**Comment by mikeizbicki** [comment]
I have not provided an answer key, but firefox will tell you the answer.  Using the procedure we followed in class, load the html file into firefox.  Then apply a style using the selector and count how many tags are affected.
