### ISSUE TITLE
Fibonacci recursion error

### ISSUE THREAD

**Issue by jacksonaldrich** [mikeizbicki/cmc-csci040#248]
Hello  @mikeizbicki,

I keep getting only 1 failed test for the fibonacci code. It passes each one besides the "fibonacci(1000)", and displays the following error: 

RecursionError: maximum recursion depth exceeded in comparison

Should I set a higher recursion depth, or re-write the code to not have this issue? 

Thanks!

**Comment by mikeizbicki** [comment]
Recursion is not something that we've covered in class, and not something that you need to use on this problem.  (And actually, if you do use it, your code will likely take *millions of years* to compute `fibonacci(1000)`.)  Instead, use a for loop following the pseudocode in the docstring.

**Comment by jacksonaldrich** [comment]
Thank you! I will take a look and make the adjustments
