### ISSUE TITLE
Green Button won't turn green on VSCode

### ISSUE THREAD

**Issue by maguizler** [mikeizbicki/cmc-csci040#252]
Hi! I re-downloaded everything onto my new computer, but now I can't get python to work. The little arrow on the top right is not turning green, when I write click on the code and press "run" nothing happens, the terminal doesn't show up. 

<img width="1512" alt="Screen Shot 2022-09-20 at 8 33 11 PM" src="https://user-images.githubusercontent.com/112537518/191408711-0b4f98df-c87f-4678-93b4-334c3ba4e9a7.png">

(not sure if the image will show, but it's a screenshot of what my screen looks like)

**Comment by mikeizbicki** [comment]
Fixing this is going to be different for everyone's computer, so there's no way to help over github issues.  I recommend going to the QCL (which I believe is still open right now) for help diagnosing this problem.
