### ISSUE TITLE
Doctest not running

### ISSUE THREAD

**Issue by Hamadalq181** [mikeizbicki/cmc-csci040#26]
My doctests are not running when I input the command into the terminal, not sure why though.
Could have something to do with my operating system.

C:\Users\hamad\PycharmProjects\notes>

This is what I get when I'm in the terminal, I can't see the $ sign.

I had 45 problems detected when I copy pasted the lab script as well, I'm using pycharm.

**Comment by Hamadalq181** [comment]
python3 -m doctest --verbose lab.py

This is what I type in to get the doctest.

**Comment by mikeizbicki** [comment]
We should meet during office hours so I can see what's going on.

Also, I've granted everyone a 48 hour grace period to resubmit (#27), so you can submit without a late penalty if you get this fixed.
