### ISSUE TITLE
Extra credit Error 

### ISSUE THREAD

**Issue by PArellano02** [mikeizbicki/cmc-csci040#262]
I am trying to call GoogleTranslator.get_supported_languages() for the lab's extra credit  but I get the following error 

File "/Users/pedroarellano/Documents/GitHub/PArellano02/lab_5.py", line 172, in <module>
    print (GoogleTranslator.get_supported_languages())
TypeError: BaseTranslator.get_supported_languages() missing 1 required positional argument: 'self'

**Comment by mikeizbicki** [comment]
Hmmm... I'll have to look at this in person to help you out, sorry.
