### ISSUE TITLE
questiosns about project 1

### ISSUE THREAD

**Issue by Raymond6688** [mikeizbicki/cmc-csci040#264]
Hi mike:
After I finish "def convert markdown to html", my doctest fail to work and says error in library and cannot import name 'F_SEAL_SEAL' from 'fcntl'.

**Comment by Raymond6688** [comment]
![WechatIMG294](https://user-images.githubusercontent.com/112432316/195175968-986cb8e7-9529-4c42-af1c-122f5d735ad6.jpeg)

**Comment by mikeizbicki** [comment]
The error message says it's happening on line 33, and you haven't shown me line 33, so I can't help from just this screenshot.

**Comment by Raymond6688** [comment]
<img width="1254" alt="Screen Shot 2022-10-11 at 12 02 14 PM" src="https://user-images.githubusercontent.com/112432316/195177022-ec580f3c-35ec-41ee-9cd3-2c7dfb70474d.png">

**Comment by Raymond6688** [comment]
hi mike
I took another screenshot

**Comment by xristinazogopoulou** [comment]
Hey Mike, 

Even though all my tests passed for the project, the links do not show up properly, how can I fix that?
![Screenshot (566)](https://user-images.githubusercontent.com/112522590/195215268-fb6019b7-7cd5-42ca-adb9-057ed1cd5853.png)
