### ISSUE TITLE
project_02 Multiple Data Sources in a Single Plot

### ISSUE THREAD

**Issue by henrylong612** [mikeizbicki/cmc-csci040#267]
Hi Mike,

In project_02, when you say "At least one of your plots must contain two different data sources," can these data sources be from the same dataset (e.g. one data source is from City A and the other data source is from City B, but both data sources are from the same json file)?

Thanks,
Henry

**Comment by mikeizbicki** [comment]
Yes, it's fine if they're from the same file, as long as it's two different things plotted on the same plot.  Your example of city A and city B would be perfect.
