### ISSUE TITLE
Where can we upload our repository for project02?

### ISSUE THREAD

**Issue by fjennison22** [mikeizbicki/cmc-csci040#268]
I wasn't able to find a place to upload our submissions for project_02, should that be done through sakai?

**Comment by mikeizbicki** [comment]
Eeek... this should be fixed now.  I accidentally didn't make the assignment "visible" in sakai until after it was due for you all.

> **Aside:** As a programmer, I find sakai's interface incredibly frustrating... I know they store all of the assignment info as a JSON file under the hood, and I with they would just give me direct access to that JSON file. Then I could easily edit it using standard tools and automatically copy the outline from previous classes, but because sakai has a "user friendly" interface that hides the underlying JSON, I am forced to manually do everything and that leads to dumb mistakes like this... ughh....

I certainly don't want anyone to be penalized for my mistake here, so I'll give everyone an extension until Tuesday at midnight regardless of whether you collaborated or not.
