### ISSUE TITLE
Graph with 2 plots

### ISSUE THREAD

**Issue by PArellano02** [mikeizbicki/cmc-csci040#269]
I was reading the instructions for the project and it was not clear to me weather out graph or chart with 2 sources meant that we had to have the data come from two different files or if it is okay to have them be from the same file. currently what I have is both lines are from data from a single file but one looks at emissions from China and the other one is Emissions from the U.S. over the years 
Is it okay that these both come from the same file

**Comment by mikeizbicki** [comment]
One file is okay, and your example of emissions from two different countries is great.
