### ISSUE TITLE
Firefox Problems

### ISSUE THREAD

**Issue by JackPotter7** [mikeizbicki/cmc-csci040#272]
Hi @mikeizbicki, just today my Firefox will not open anymore. I've tried restarting my computer, and deleting and re-downloading the application multiple times. Every time, it gives me the following message, but I've ensured that no other Firefox exists or is open on my computer. Give we need to use Firefox for this class I'd like to figure this out. 
<img width="434" alt="Screen Shot 2022-11-02 at 5 23 39 PM" src="https://user-images.githubusercontent.com/112518435/199626590-b4d85a80-df5a-461f-8688-03f571ed258a.png">

**Comment by mikeizbicki** [comment]
Hmmm.... since I'm not a Mac user, I don't think I'm going to be able to help out with this.  I would try either the QCL or IT.
