### ISSUE TITLE
Project 03 Questions

### ISSUE THREAD

**Issue by JackPotter7** [mikeizbicki/cmc-csci040#274]
Hi  @mikeizbicki, I'm about finished up with my webscraping project and I have a couple of questions. 

1)  The first data entry in my webscraper is always of the title 'Shop on Ebay', which obviously isn't an actual item that is being listed, so I am wondering if it is appropriate to delete this entry or just leave it in. 

2) My webscraper seems to catch all of the entries on a given  page, but doesn't enter them into the `items` list in order. I'm wondering if this is a problem, or merely a product of how the requests/BeautifulSoup libraries read the data.   

3) In the video you talked about that it is okay if ebay recognizes our bot and stops us from scraping our data. I'm wondering if there are any ways (that I can reasonably do) to trick ebay into not recognizing the bot. If there are I'd love to try and add them into my code.

**Comment by mikeizbicki** [comment]
Great questions!

1. I recommend deleting this entry with a slice that looks something like `xs[1:]`
2. It's fine whether your items are in order or not.
3. I haven't looked into what ebay does to limit bot activity.  Most of the methods for detecting bots vs humans get pretty technical and require a deep understanding of how everything works under the hood.  So you'd probably need to do quite a bit of research to try to evade them.

**Comment by ben-smith23** [comment]
Hey @JackPotter7

I also had the same issue regarding 'Shop on eBay.' Originally I deleted this entry with a slice, but noticed that this item would come up each time I scraped a new eBay results page, meaning it appeared throughout my scraped items.

I was able to fix it like this:

```
if 'Shop on eBay' in item['name']:
                continue
else:
            items.append(item)
```

This works as far as I can tell, but if you or anyone else sees any problems with this code, let me know!
