### ISSUE TITLE
Submitted Wardial File Problems

### ISSUE THREAD

**Issue by JackPotter7** [mikeizbicki/cmc-csci040#278]
Hi @mikeizbicki, I submitted my wardial.py file, and accidentally commented out my code lines 189-208 (scanning the servers and printing them out). I was doing some troubleshooting with Henry Long and commented the bottom part out to do some stuff. I'm not sure if you have an autograder for this assignment, so should I go ahead and submit another way or is this okay?

**Comment by mikeizbicki** [comment]
You can email me an updated file and I'll grade the emailed submission.
