### ISSUE TITLE
Madlibs lab issue

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#280]
After you complete the required reading for the [madlibs lab](https://github.com/mikeizbicki/cmc-csci040/tree/2022fall/project_04/lab-madlibs), reply to this issue with the statement

> I have completed the required reading for the madlibs lab.

**Comment by JackPotter7** [comment]
I have completed the required reading for the madlibs lab.

**Comment by ben-smith23** [comment]
I have completed the readings for the lab.

**Comment by taylordaetz** [comment]
I have completed the required reading for the madlibs lab.

**Comment by davidhlee625** [comment]
I have completed the required reading for the madlibs lab.

**Comment by xristinazogopoulou** [comment]
I have completed the required reading for the madlibs lab.

**Comment by buffeinstein** [comment]
I have completed the required reading for the madlibs lab.

**Comment by kpark1226** [comment]
I have completed the readings for the madlibs lab.

**Comment by justin-is-away** [comment]
I have completed the required reading for the madlibs lab.

**Comment by JustinOngchin** [comment]
I have completed the required reading for the madlibs lab.

**Comment by jadersaunders** [comment]
I have completed the required readings for the madlibs lab.

**Comment by adamzterenyi** [comment]
I have completed the required reading for the madlibs lab.

**Comment by xutimon** [comment]
I have completed the required reading for the madlibs lab.

**Comment by henrylong612** [comment]
I have completed the required reading for the madlibs lab.

**Comment by fjennison22** [comment]
I have completed the required reading for the madlibs lab.

**Comment by AjaiKBan** [comment]
I have completed the readings.

**Comment by Kal2025** [comment]
I have completed the required reading for the madlibs lab.

**Comment by Kevinl0378** [comment]
I have completed the required reading for the madlibs lab.

**Comment by dwalker25** [comment]
I have completed the required readings for the madlibs lab.

**Comment by jacksonaldrich** [comment]
I have completed the required reading for the madlibs lab.

**Comment by chasekeir** [comment]
I have completed the required reading for the madlib lab

**Comment by cyrusg645** [comment]
I have completed the required readings for the madlibs lab.

**Comment by Stephanie-Espinoza** [comment]
I completed the readings.

**Comment by chlol3912** [comment]
I have completed the readings for the lab.
