### ISSUE TITLE
lab questions 

### ISSUE THREAD

**Issue by PArellano02** [mikeizbicki/cmc-csci040#283]
I was wondering if the madlibs had to have a coherent theme between them or if they could all be independent. and I was also wondering if we had to have 5 different replacement words or if we could replaced the same 3 words multiple times

**Comment by mikeizbicki** [comment]
The madlibs should have a coherent theme, but I don't care what the theme is.  

You can reuse the same words in multiple madlibs as long as the resulting messages are different.

I'm not going to be spending much effort grading the messages, so you don't need to put too much thought into it.  It shouldn't take you more than 10 minutes or so to come up with a set of messages.
