### ISSUE TITLE
Project 04 Q

### ISSUE THREAD

**Issue by JackPotter7** [mikeizbicki/cmc-csci040#285]
Hi Mike, in regard to `FIXME (task 0): get a list of all of the comments in the submission` should we return a list with all of top-level comments, or *all* of the comments (including replies to other comments)? 

Thanks and hope you feel better!

**Comment by mikeizbicki** [comment]
This should be all comments, including replies, and not just top level comments.

**Comment by JackPotter7** [comment]
Hi @mikeizbicki another Q: regarding `FIXME (task 3): filter the not_my_comments list to also remove comments that you've already replied to`. Does this mean we should only filter the list to comment without ANY replies, or just comments that don't have any replies from our bot...

**Comment by mikeizbicki** [comment]
Keep all comments that don't have any replies from your bot.  The lists you are creating in these first tasks are going to contain the comments that you will eventually reply to, and you need to be able to reply to a comment if someone else has replied to it, just not if you have replied to it.

**Comment by JackPotter7** [comment]
@mikeizbicki great. One more further clarification (maybe this comes from my inexperience with reddit). Taking a look at the code below (my bot is masterfulcoolbot), would this mean I would also need to reply to the "hello hello" comment, or does the reply to the "hello hello hello" comment count? 
<img width="866" alt="Screen Shot 2022-11-16 at 7 52 51 PM" src="https://user-images.githubusercontent.com/112518435/202351009-ccb48245-6fe6-4519-9569-b5f83f8bd5b1.png">

**Comment by mikeizbicki** [comment]
You don't need to reply to the "hello hello" comment, but you need to *be able* to reply to that comment.
