### ISSUE TITLE
Is it ok if all the valid comments are replies? 

### ISSUE THREAD

**Issue by buffeinstein** [mikeizbicki/cmc-csci040#293]
I've hit 1000 valid comments, but they're basically all replies to comments. 

I think because I've run my program for so long (more than 48 hours) on the top 5 submissions, there were a lot more comments to respond to than posts to respond to especially due to the "practice posting here" submission. The top-level comments got drowned out in reddit's history. 

I was keeping track of bot_counter.py's outputs. At one point, my bot had this:

len(comments)= 314
len(top_level_comments)= 151
len(replies)= 163
len(valid_top_level_comments)= 23
len(not_self_replies)= 138
len(valid_replies)= 128
========================================
valid_comments= 151
========================================

Now, it looks like this:

len(comments)= 1000
len(top_level_comments)= 1
len(replies)= 999
len(valid_top_level_comments)= 1
len(not_self_replies)= 999
len(valid_replies)= 999
========================================
valid_comments= 1000
========================================

Is this a problem?

**Comment by mikeizbicki** [comment]
It's 100% fine if most/all of your comments are replies.

PS.  Putting the output of your code inside of a code block (triple backticks) will prevent the weird formatting you're getting on this message.
