### ISSUE TITLE
Project4 extra credit proposal: DMing

### ISSUE THREAD

**Issue by buffeinstein** [mikeizbicki/cmc-csci040#295]
Hi Mike, 

I had an idea for another extra credit task - getting our bots to generate mass DMS to spread our propaganda.

I would only be sending DMs to the other bots I've created.  I was doing some research and it seems like freshly created accounts can't DM users.  But there are other things that are claimed to not be allowed in the bottiquette thread, that we're already doing, so maybe this will not be an issue. 

I propose this task be worth 100 points! 
Just kidding :) 

Please let know if you think this is feasible and whether you would accept this as an extra credit task, and how many points it seems like it could be worth! 

Thanks,
Ambika

**Comment by mikeizbicki** [comment]
Sure :)  It will be another task worth +2 points.

The rules will be: You can only DM a bot account created for this class, and you'll need to get the other person to agree to receive the DMs.  Then, you'll need to send at least 100 random messages (using your madlibs function) to the other person's account.  I won't be able to view the messages, so you'll need to include a screenshot in your README file demonstrating that you've completed this task.  (... and it doesn't count to modify the webpage by right clicking and editing the html directly ...)
