### ISSUE TITLE
Hello World!

### ISSUE THREAD

**Issue by adien43** [mikeizbicki/cmc-csci040#3]
Hello fellow coders, 

It would be appreciated if I can get some likes and ratings on my repository. 
https://adien43.github.io/
Will make sure to return the favor. 

Have a great weekend!

-Jun

**Comment by NilsSkattum** [comment]
Hey all, 

Would appreciate some likes and ratings on my repository. Thanks!
https://nilsskattum.github.io/ 
Will make sure to like back!

-Nils

**Comment by tkapoor22** [comment]
Hi everyone, 

I'd really appreciate some likes and ratings on my webpage and repository :) 

[https://tkapoor22.github.io/ ](https://tkapoor22.github.io/)

Thank you! 

-Tanya

**Comment by mariagerges** [comment]
Hi everyone! 

I'd appreciate some likes and ratings on my webpage and repository, Thank you so much!! :)
https://mariagerges.github.io/
-Maria

**Comment by sophiedecastro** [comment]
Hey everyone,

Would appreciate some likes and ratings on my webpage and repository!

[https://sophiedecastro.github.io/](url)

Thanks so much
- Sophie

**Comment by TuckHarris** [comment]
Hi everyone,

I'd really appreciate some likes and ratings on my webpage and repository :)

https://tuckharris.github.io/

Thank you!
Tucker Harris

**Comment by ktzchen** [comment]
Hey ya'll

I need 3 more likes on my webpage, would really appreciate it if you guys showed it some love! 
https://ktzchen.github.io/

(Also wouldn't hurt if you starred my repository: https://github.com/ktzchen/ktzchen.github.io)

Thank you!
Katie

**Comment by valerialoria** [comment]
Hey guys! I need one more like on my webpage https://valerialoria.github.io/

and would really appreciate a star on my repository!!! https://github.com/valerialoria/valerialoria.github.io

**Comment by refe22** [comment]
Hey guys! Please like my webpage: https://refe22.github.io./
and star my repository. Thanks! : https://github.com/refe22/refe22.github.io

**Comment by mel088** [comment]
Hi! I think my webpage like button is broken, only cool people can like it ;) https://mel088.github.io/
and please star my repository. Thank you! https://github.com/mel088/mel088.github.io

**Comment by dorcassaka** [comment]
Hi everyone! If you could like and star my webpage that would be awesome!
Star: https://github.com/dorcassaka/dorcassaka.github.io
Like: https://dorcassaka.github.io

Have a great weekend :)

**Comment by Skyler-Bradley** [comment]
Hello everybody! If you can like my webpage and/or star my repository, thank you!
https://skyler-bradley.github.io
https://github.com/Skyler-Bradley/Skyler-Bradley.github.io

**Comment by saneenkhan** [comment]
Hey everyone! I'd really appreciate it if you'd star my repository/like my webpage! Thanks :) 

https://github.com/saneenkhan/saneenkhan.github.io
https://saneenkhan.github.io/

**Comment by willwaaang** [comment]
Hi guys, I'd really appreciate it if you could like my webpage and star my repository! :)

I'll be sure to return the favor. Thanks!

https://github.com/willwaaang/willwaaang.github.io


https://willwaaang.github.io/

**Comment by sarahfreeman-star** [comment]
Hi guys! I would appreciate it if you could like my webpage and star my repository! Thanks! 

https://sarahfreeman-star.github.io/
https://github.com/sarahfreeman-star/sarahfreeman-star.github.io

**Comment by dorcassaka** [comment]
Hi! I still need two likes on my webpage: https://dorcassaka.github.io and two stars on my repository https://github.com/dorcassaka/dorcassaka.github.io I would really appreciate if y'all could do so and I will definitely return the favor! Thank you!

**Comment by smccann11** [comment]
Hi all, I’d appreciate if you like/star my webpage and repository, I’ll return the favor for those who still need!

https://smccann11.github.io/

https://github.com/smccann11/smccann11.github.io

Thanks!

**Comment by nickwilson3** [comment]
Hi everyone,

Would appreciate it if y'all liked my webpage and starred by repository.
https://nickwilson3.github.io/
https://github.com/nickwilson3/nickwilson3.github.io

Thanks

**Comment by flancast90** [comment]
Wow! A bit late to the party it seems, but I'd love for some people to look at any of my projects at https://github.com/flancast90 and star them!
