### ISSUE TITLE
Terminal Problem

### ISSUE THREAD

**Issue by mariagerges** [mikeizbicki/cmc-csci040#30]
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A 

When I try to run my doctests in the terminal this is what appears instead of running the test. I have a MAC if that helps.

**Comment by mikeizbicki** [comment]
I'll need to take a look at the computer with you to see what's going on.  Can you come to office hours this afternoon?
