### ISSUE TITLE
Revisiting Monday's Lecture on YouTube 

### ISSUE THREAD

**Issue by taylordaetz** [mikeizbicki/cmc-csci040#301]
Hi Mike, 

There were a couple steps from Monday's lecture that I wanted to revisit but was unable to access the uploaded lecture on YouTube. I was curious if the lecture would be uploaded today so I can work through the issues before class tomorrow. 

Thanks!

**Comment by mikeizbicki** [comment]
Hmmm... the video is working for me on youtube.  Here's a direct link: <https://www.youtube.com/watch?v=YdE-Rmwld5I&list=PLSNWQVdrBwobVmLdv8zKEO1TVJHZBjPxU&index=26>
