### ISSUE TITLE
Checkerboard Question

### ISSUE THREAD

**Issue by mel088** [mikeizbicki/cmc-csci040#35]
Hi @mikeizbicki ,
I have a question about the checkerboard problem on this week’s lab. I think I nearly got it to work, however the output is twice as wide as I need it to be. Please let me know what you think! I posted my results below:

<img width="376" alt="Screen Shot 2020-09-18 at 6 00 28 PM" src="https://user-images.githubusercontent.com/66801534/93706556-4e33fb00-fadc-11ea-96ed-beba73894d15.png">

Thanks!

**Comment by HoangChu-Claremont** [comment]
I'm no expert here, but I think you should reconsider the pattern, and to decrease the number of stars each line by 2 times, you can decrease n by 2 times in each time printing.

**Comment by mel088** [comment]
@HoangChu-Claremont Thanks for the response. I was thinking that too. I'm not sure how to write the code for that though. Please let me know, thanks!

**Comment by mikeizbicki** [comment]
In my solution, instead of using `print('x *' * n)` to print each line, I use a for loop that looks like
```
for j in range(n):
    if j%2==0:
        # do something here
    else:
        # do something else
```
Using the `' *' * n` approach was a good idea, but you have a little bit more control with the loop.

**Comment by mel088** [comment]
@mikeizbicki Thank you for the response. I tried this, but my results are still too wide as it is only printing two lines of asterisks for each checkerboard. 

```
for i in range(n):
        if i%2==0:
            print ('* ' * n)
        else:
            for j in range(n):
                if j%2==0:
                    print (' *' * n)
                else:
                    return None
```
Let me know what you think, thanks!

**Comment by mikeizbicki** [comment]
Right now, you're printing 2 characters (`* `) per iteration, you need to print
only a single character (either `*` or ` `) on each iteration.

**Comment by mel088** [comment]
Okay, I am getting this as a result now. Where should I go from here?
```

checkers(5)
Expected:
    * * *
     * * 
    * * *
     * * 
    * * *
Got:
    *****
    *****
```

**Comment by mikeizbicki** [comment]
You need to think about how to use an `if` statement to sometimes print `*` and
sometimes print ` `.

**Comment by mel088** [comment]
Oh, okay. Thanks!
