### ISSUE TITLE
[Solved] Facebook Like Button Issue

### ISSUE THREAD

**Issue by ZacDavis0-159910538** [mikeizbicki/cmc-csci040#4]
Hi for everyone like me who was having issues with the Facebook like button. For me the issue was the. after .io in the link. https://zacdavis0-159910538.github.io./ doesn't have the facebook like button but still links to the site, https://zacdavis0-159910538.github.io/ does.
Hope this helps!

**Comment by dorcassaka** [comment]
Thanks for sharing this! It seems like that is the issue for me as well. Did you have to get a new code for Facebook like button on the github.io/ page or is your code still the same as long as you are sending people to the github.io/ link? I have been asking people to like mine but I still only have 3 likes on the page so I am wondering if I need to get a new code.

**Comment by mikeizbicki** [comment]
Great job debugging @ZacDavis0-159910538 !
