### ISSUE TITLE
Part I of lab: creating issues with markdown

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#41]
For Part I of today's lab, you have to practice using markdown with github issues.  This will ensure that you know all of the syntax that you'll have to implement in your homework assignment.  You can find the full guide to the syntax at https://guides.github.com/features/mastering-markdown/

To complete Part I, reply to this issue with a message that contains all of the markdown syntax.

Your message should contain the following "inline" elements: **bold** text, *italic* text, ~~strikethrough~~ text, a [link to your favorite webpage](https://izbicki.me), some `<code>inline code</code>` and an image: ![the octocat](https://avatars1.githubusercontent.com/u/583231?s=460&u=a59fef2a493e2b67dd13754231daf220c82ba84d&v=4).

And your message should contain the following "block" elements:

An ordered list:
1. the first item
1. the second item
1. the last item

An unordered list:
* the first item
* the second item
* the last item

A code block:
```
<html>
<body>
<b>Hello World!</b>
</body>
</html>
```

And a little table:
| Name of family member | Role in the family |
| --- | --- |
| Homer | Dad/Husband |
| Marge | Mom/Wife |
| Bart | Son/Brother |
| Lisa | Daughter/Sister |
| Maggie | Daughter/Sister |

**Important:** Notice that the code blocks contain HTML, but that the HTML inside of a code block is not getting rendered as HTML. You will have to ensure that this happens correctly in your homework, and there is a hint in the `compile_code` function about how to accomplish this task.

**Comment by iamclassycain** [comment]
![Canon Camera](https://lh3.googleusercontent.com/proxy/-46yRHl9yTn6NaUlVwss34zz2HbVqVbuWSdW10KctpJoH2CjW3hzUzQiAQELdPSsvVJVk01EupjBpQ0cRUrmRfv8PVUfgIUfjpAt-0O9eKak2drfGnHZVGPV9l_71c2yEvOi1bauvSMn)

## Photographers
1. **Kwaku** Alston
2. _Tyler_ Mitchell
3.  Dario Calmese

## Fashion Designers
* Marc Jacobs
* Coco Chanel
* Donna Karren

Photographers | Fashion Designer
------------ | -------------
Kwaku Alston | Marc Jacobs
~~Coco Chanel~~ | ~~Tyler Mitchell~~
Dario Calmese | Donna Karren

The website of one of my favorite photographers:
[Kwaku Alston](https://kwakualston.com/)

The HTML code for the above link is the following:

<code>
&lt;html&gt; 
&lt;body&gt; 
&lt;a href = https://kwakualston.com/&gt;&lt;p&gt;Kwaku Alston&lt;/p&gt;&lt;/a&gt; 
&lt;/body&gt; 
&lt;/html&gt;
</code>

**Comment by NilsSkattum** [comment]
Hello my name **Nils** and I like ~~school~~ *sports.* Don't believe me, here is my 
favourite team, the [The Flint Michigan Tropics](https://en.wikipedia.org/wiki/Semi-Pro). 

This is what they look like:

![Flint Michigan Tropics](https://www.mlive.com/resizer/JHbXQCl2Bpw-ZUBpNUvAwn5dryo=/1280x0/smart/advancelocal-adapter-image-uploads.s3.amazonaws.com/image.mlive.com/home/mlive-media/width2048/img/newsnow_impact/photo/large-20080228-willferrell-semiprojpg-9af92cc9a24dea8f.jpg)

I like them for the following ordered reasons:
*They are funny
*They demonstrate strong teamwork and love
*Jackie Moon wrestles a freakin' bear

And for the following unordered reasons:
*Jackie Moon's silky voice 
*Father Pat is a referee
*Jackie Moon's free throw style 

Here is the HTML code for what I really like. 
```
<html>{
    <body>
        <b> Nils Skattum REALLY likes sports</b>
    </body>
</html>
}
```

Also, here is a table of the Flint Michigan Tropics' best players

First Name | Last name
---------- | ---------
Jackie | Moon 
Ed | Monix
Clarence | Withers

**Comment by NilsSkattum** [comment]
Hello my name **Nils** and I like ~~school~~ *sports.* Don't believe me, here is my 
favourite team, the [The Flint Michigan Tropics](https://en.wikipedia.org/wiki/Semi-Pro). 

This is what they look like:

![Flint Michigan Tropics](https://www.mlive.com/resizer/JHbXQCl2Bpw-ZUBpNUvAwn5dryo=/1280x0/smart/advancelocal-adapter-image-uploads.s3.amazonaws.com/image.mlive.com/home/mlive-media/width2048/img/newsnow_impact/photo/large-20080228-willferrell-semiprojpg-9af92cc9a24dea8f.jpg)

I like them for the following ordered reasons:
1. They are funny
2. They demonstrate strong teamwork and love
3. Jackie Moon wrestles a freakin' bear

And for the following unordered reasons:
* Jackie Moon's silky voice 
* Father Pat is a referee
* Jackie Moon's free throw style 

Here is the HTML code for what I really like. 
```
<html>{
    <body>
        <b> Nils Skattum REALLY likes sports</b>
    </body>
</html>
}
```
Here is the `<addr>` element for page ownership. 


Also, here is a table of the Flint Michigan Tropics' best players

First Name | Last name
---------- | ---------
Jackie | Moon 
Ed | Monix
Clarence | Withers









Also, here is a table of the Flint Michigan Tropics' best players

First Name | Last name
---------- | ---------
Jackie | Moon 
Ed | Monix
Clarence | Withers

**Comment by mariagerges** [comment]
# Egyptian Pyramids 

![Egyptian Pyramids](https://d3rr2gvhjw0wwy.cloudfront.net/uploads/mandators/49581/file-manager/egyptian-pyramid,-egyptian-pyramids-facts,-egyptian-pyramid-inside.jpg)

**The Egyptian pyramids** are ancient pyramid-shaped masonry structures located in *Egypt.* As of November 2008, sources cite either 118 or 138 as the number of identified Egyptian pyramids. Most were built as tombs for the country's pharaohs and their consorts during the Old and Middle Kingdom periods.

* Historical Development 
* Pyramid symbolism 
* Construction techniques
* Locations 
1. Abu Rawash
1. ~~Giza~~
1. Zawyet el-Aryan
1. Abusir

## Historical development

The design of the Egyptian pyramid seems to have been a progression from the Sumerian ziggurat, a stepped pyramidal structure with a temple on top, which dated to as early as 4000-3500 BC.
From the time of the Early Dynastic Period (c. 3150–2686 BC), Egyptians with sufficient means were buried in bench-like structures known as mastabas. At Saqqara, Mastaba 3808, dating from the latter part of the 1st Dynasty, was discovered to contain a large, independently-built step-pyramid-like structure enclosed within the outer palace facade mastaba. Archaeological remains and inscriptions suggest there may have been other similar structures dating to this period.

## Pyramid symbolism

The shape of Egyptian pyramids is thought to represent the primordial mound from which the Egyptians believed the earth was created. The shape of a pyramid is also thought to be representative of the descending rays of the sun, and most pyramids were faced with polished, highly reflective white limestone, in order to give them a brilliant appearance when viewed from a distance. Pyramids were often also named in ways that referred to solar luminescence. For example, the formal name of the Bent Pyramid at Dahshur was The Southern Shining Pyramid, and that of Senwosret at el-Lahun was Senwosret is Shining.

## Construction techniques

Constructing the pyramids involved moving huge quantities of stone. Papyri discovered at the Egyptian desert near the Red Sea, in 2013 by archaeologist Pierre Tallet, revealed the journal of Merer, an official of Egypt involved in transporting limestone along the Nile River. These papyri reveal processes in the building of the Great Pyramid at Giza, the tomb of the Pharaoh Khufu, just outside modern Cairo. Rather than overland transport of the limestone used in building the pyramid, there is evidence that limestone blocks were transported along the Nile River, in the journal of Merer, preserved remnants of ancient canals, and transport boats discovered.

Name of the pyramid | info
------------ | -------------
Giza Pyramids | The Giza pyramid complex has been a popular tourist destination since antiquity and was popularized in Hellenistic times when the Great Pyramid was listed by Antipater of Sidon as one of the Seven Wonders of the Ancient World. 
Zawyet el-Aryan pyramid | This site, halfway between Giza and Abusir, is the location for two unfinished Old Kingdom pyramids

Here's a link for more info: https://www.si.edu/spotlight/ancient-egypt/pyramid

<html>
<body>
<b>Come Visit Egypt!</b>
</body>
</html>

**Comment by ktzchen** [comment]
Hi! My name is ~~Katherine~~ Katie Chen, and I am taking this **CS40** class because I am *very* interested in computer science. This is the [website](https://ktzchen.github.io/) that I created for this class earlier in the course.  

I really like reading. One of my favorite authors is Fitzgerald:
![Fitzgerald](https://upload.wikimedia.org/wikipedia/commons/5/5c/F_Scott_Fitzgerald_1921.jpg)

Here are the rest of my favorite authors in order:
1. Oscar Wilde
1. John Steinbeck
1. George Orwell

There are lots of books and authors I want to read, but have not read yet. Some of these authors include:
* H.G. Wells
* David Foster Wallace
* Albert Camus

I hope to get more into international literature as well. For example, I am interested in:
Country | Author
------------ | -------------
Russia | Dostoevsky
Japan | Dazai
China | Lu Xun

```
<html>
<body>
<b>Hello World!</b>
</body>
</html>
```

**Comment by sophiedecastro** [comment]
![Image of Ube](https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=%5B1000%2C571%5D&w=2000&h=1047&url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F23%2F2019%2F07%2F16%2Fwhat-is-ube-1.jpg)

# Ube (Purple Yam)

(In an HTML file, this header would use `<h1>` tags!)

## Recipes for ube
* ube pan de sal
* ube ice cream
* ube cheesecake

## Can be mistaken for
1. taro
1. Japanese sweet potato
1. sweet potato

**ube** (purple yam) is *not* ~~taro~~

Recipes for ube | Commonly mistaken for
------------ | -------------
ube pan de sal | taro
ube ice cream | Japanese sweet potato
ube cheesecake | sweet potato

One of my favorite websites for recipes: 
[smitten kitchen](http://smittenkitchen.com)

Random code block!
```
<html>
<body>
<b>Hello World!</b>
</body>
</html>
```

**Comment by mel088** [comment]
**What I made for Dinner Yesterday:**
*Tri-Tip Salad*
![It looked like this!](http://www.peanutbutterandpeppers.com/wp-content/uploads/2014/02/Grilled-Tri-Tip-and-Vegetable-Salad-020a.jpg)
[Check out recipes on Food Network!](https://www.foodnetwork.com/)

Ingredients:
1. Tri-Tip
1. Arugula
1. Spinach
1. Balsamic Vinaigrette

Salad Toppings:
* Pomegranate Seeds
* Corn
* Sliced Avocado
* Sliced Bell Pepper
* ~~Onions~~

```
<html>
<body>
<b>yum</b>
</body>
</html>
```
Victim of my cooking | Their rating of my cooking
------------ | -------------
Mom | 10/10
Dad | 10/10

**Comment by tkapoor22** [comment]
# Doggos!!

![Golden Retriever](https://media1.popsugar-assets.com/files/thumbor/uiZBUSl5UNskxObP13Yd-3X30QY/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2019/12/18/763/n/46902966/4759e2855dfa5f7c857892.88399573_/i/what-kind-health-problems-do-golden-retrievers-have.jpg)

## Favorite Dog Breeds
1. **Golden** Retriever
1. Labrador
1. Bulldog **Mastiff**

## Potential Names
* Wally
* Bali
* ~~Lily~~
* ~~Max~~
* Blue

## *Dogs I Know*
Name | Breed
------------ | -------------
Leo | Samoyed
Orion | Labradoodle
Stella | Shih Tzu 

[Here's a link to a website that's about to become my favorite website](https://www.petfinder.com/dog-breeds/collections/cutest-dog-breeds/ )

Now here's the code to another website:
```
<html>
<body>
<a href= https://www.mydomaine.com/cutest-dogs-in-the-world>Cutest-dogs-in-the-world</a>
</body>
</html>
```

I think `<i>everyone</i>` should have a dog! I can't wait to get my own :)

**Comment by brandonsrho57** [comment]
![1200px-Los_Angeles_Dodgers_logo_(low_res) svg](https://user-images.githubusercontent.com/70169482/94215419-6ff10180-fe91-11ea-9b27-30211356dfe3.png)


# Los Angeles Dodgers

### Core Players
* Cody Bellinger
* Mookie Betts
* Clayton Kershaw

*Strengths*
1. Bats
2. Starting Pitching
3. Relief Pitching

Biggest Rivals | Easy Wins
------------ | -------------
**Giants** | Rockies
Cardinals | Orioles
~~Yankees~~ | Diamondbacks

[Visit the Dodgers](https://www.mlb.com/dodgers/)

<strong> Some code </strong>

    <html>
        <head>
        </head>
        <body>
            <h1>The Giants kind of suck</h1>
        </body>
    </html>

**Comment by valerialoria** [comment]
# Hey Guys!

I am **Valeria** and I was born in *Costa Rica*. Often confused with ~~Puerto Rico~~. I usually spend my vacation time at the beach in a place called [Hacienda Pinilla](https://www.haciendapinilla.com/). It's ***beautiful***. 

![Hacienda Pinilla](https://www.stayintamarindo.com/wp-content/uploads/2017/07/beach-club-areal-1030x687.jpg)

These are my top favorite beaches in CR
1. Playa Langosta 
1. Playa Avellanas 
3. Playa Bonita

My top activities to do there are: 
* Lay in the sun and read a good book
* Sip on watermelon juice
* Go for a dip in the ocean

Beach | Activity I like to do there
------ | ---------
Playa Langosta | Lay in the sun and read a good book
Playa Avellanas | Sip on watermelon juice
Playa Bonita | Go for a dip in the ocean

Random code and code block check ! 
For the big header I would use an
`<h1>` tag! 

    <html>
        <head>
        </head>
            <body>
                  <h1>Go to the playa</h1>
           </body>
    </html>

**Comment by yilinli22** [comment]
## **Dialectics Behavioral Therapy**

![DBT](https://images.unsplash.com/photo-1506126613408-eca07ce68773?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=731&q=80)

## Clinical Therapies
1. DBT :smile_cat:
2. CBT
3. ~~Others~~

## DBT
* Traditional in-person psychotherapies are proving incapable of addressing mental health needs globally.
* Fundamentally new approaches are needed to increase access to effective mental health care in a way that is affordable, feasible, scalable and culturally appropriate.
* Dialectics Behavioral Therapy: visit **my favorite :smiley: ** webpage [Global Mental Health Lab](https://www.globalmentalhealthlab.com)

## This is a Code Block
```<html>
<body>
<b>I love DBT!</b>
</body>
</html>
```

## Current Project
*Project Leads* | *Project Content*
-------------- | ----------------
Li | Peer-Counseling Using DBT Skills Training in China
Williams | Bio-Social Model of Emotion Dysregulation
Ledbetter | Eating and Wellbeing 

## Inline Code
I think you should use an
`<addr>` element here instead.

**Comment by samcbogen** [comment]
Hey Y'all! I am writing to tell you about my favorite team - the **New York Yankees**! I *love* watching their games, though it has been  ~~somewhat~~ really sad recently as they have lost a bunch of games. 
If you want to check them out, do it [here](https://www.mlb.com/yankees).

If you are curious, here are my favorite players on the Yankees during my lifetime (no order):
*Mariano Rivera
*Derek Jeter
*CC Sabathia
*DJ LeMahieu

If you are still reading this, I used to pitch, so I thought I would give you my current favorite Yankee pitchers in order:
1. Chad Green (don't ask why)
1. Aroldis Chapman
1. Gerrit Cole
1. Masahiro Tanaka
1. Tommy Kahnle

Why are you still reading this? If you're here, Since I need a chart, let me tell you our current Outfield (since you are probably so excited!)
| Position | Name |
| -- | -- |
| Left Field | Clint Frazier | 
| Center Field | Aaron Hicks |
| Right Field | Aaron Judge |



For those of you who are still not bored to death by this, here is their logo!
![Logo](https://www.mlbstatic.com/team-logos/share/147.jpg)


```
<html>
<body>
<b>Thank you for Reading!</b>
</body>
</html>
```

**Comment by HoangChu-Claremont** [comment]
`Robert Lewandowski`, [#1  striker](https://www.transfermarkt.us/robert-lewandowski/profil/spieler/38253) **in the world** with ~~47~~ 55 *goals* last season.


![Image of Yaktocat](https://s.yimg.com/ny/api/res/1.2/cdZkhnv8Je548lJSEqyEmA--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9ODAw/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-images/2019-10/cb48edb0-f805-11e9-bdf3-742bb64756a4)

# Career achievements:
- 1 x Champions League 
- 4 x German Super Cup 
- 8 x Bundesliga 

```
<html>
  <head>
        <b> Personal achievements: </b>
  </head>
</html>
```
1. 9 x Poland Footballer of the year
2. 16 x Top Scorer in Germany
3. $66.00m in value

# Club History:

Year | Club
------------ | -------------
2008–2010 | Lech Poznań
2010–2014 | Borussia Dortmund
2014–present| Bayern Munich

**Comment by nickwilson3** [comment]
# My name is Nick and I like ~~school~~ stocks.
I **love** it when the *stock market* does this: 
![image of bullish stock market](https://user-images.githubusercontent.com/70651858/94216110-65d00280-fe93-11ea-8391-d9c084f1ca35.png)
## My 3 favorite stocks are:
1. Apple
1. FMCI
1. Gamestop (short term)

## Things I look for in a company are:
* potential catalysts
* profit
* future visions

Stock Symbol | Stock Price
-------------- | -----------
AAPL | $109
FMCI | $20
GME | $9

[Click here to read about Apple's 4-1 Stock Split!](https://www.barrons.com/articles/apples-stock-is-about-to-split-heres-what-it-means-for-investors-51598632773)

I think you should use an
`<addr>` element here instead.

## A code block:
     <HTML>
     <body>
     <b>We Love Green!</b>
     </body>
     </html>

**Comment by Yugi00** [comment]
![Modern Warfare Title](https://hb.imgix.net/d9ffbcf4aa5df29167b21484b9aac12507a9deb9.jpg?auto=compress,format&fit=crop&h=353&w=616&s=523a92154bf15e96dc83c5c113f93bcf)
Hey! My name is *Jacob Yep* and I really enjoy ~~making~~ watching YouTube videos about **Modern Warfare**.
Here is a table containing some of my favorite channels to watch:
Content Creators | Competitive Players
------------------- | ---------------------
I AM WILDCAT | NICKMERCS
ImMarksman | Cloakzy
BasicallyIDoWrk | Symfuhny

But my favorite channel to watch can be found [here](https://www.youtube.com/channel/UCXY6EEzaqiKV9W0jbCQepUA/featured?view_as=subscriber).

Here's the HTML `code` for the link above if you're interested:
`<html>`
         ` <body>`
                      `<a href= https://www.youtube.com/channel/UCXY6EEzaqiKV9W0jbCQepUA/featured?view_as=subscriber>here</a>`
          ` </body>`
`</html>`

Top 3 Reasons why I like these channels:
1. They're all really funny.
1. They're all pretty good at the game.
1. They all know how to entertain their audiences.

Some other reasons:
* I learn a little more about the game from them.
* The way they edit their videos is unique and interesting.
* They all just yell at each other.

**Comment by dorcassaka** [comment]
Hello World- I'm *back* to talk about my favorite ~~salads~~ **Desserts**! 
*I actually do love salads, but who wants to see a post about salads?* 

Today's *focus* is going to be: 
# Ice Cream 
![Ice Cream](https://myhubsdotorg.files.wordpress.com/2016/05/013.jpg)
## Favorite Ice Cream Flavors & Locations 
**Flavor** | **Location**
-------- | ----------
Mint Chocolate Chip | Disneyland
Vanilla Sundae | Margie's Candies 
Vanilla Bean | Firecakes 
Cookie Dough | Sloan's 

Why do I like these flavors? 
* Creamy and velvety
* Chocolate *(need I say more?)*
* Cookie dough is just so good 

If I was forced to rank these locations? 
1. Sloan's
1. Firecakes
1. Margie's Candies 
1. Disneyland 

Here's some random inline code `<code>inlinecode</code>` in case you are interested in computer science! 

Here's also an extra special code block because you read this far! 
````
 <html>
 <body>
 <b>Hello World! </b>
 </body>
 </html>
````
*and yes the code actually works - I double checked!* 
If you would like to learn more about some of my favorite desserts check out [my website](https://dorcassaka.github.io/) that I made in Mike's CS 40 class!

**Comment by rmagill22** [comment]
# Taylor Swift # 

![Taylor Swift](https://user-images.githubusercontent.com/70245959/94217304-8cdc0380-fe96-11ea-8ede-d44b3748e4ae.png)

Hi! My name is Rachael and I'm a ~~Swifitie~~ big fan of **Taylor Swift.**
I like her as a person, but I *love* her music. 

Check out her website [here](https://www.taylorswift.com/)!

Here's her (in my controversial opinion) top three albums:
1. folklore
1. 1989
1. Speak Now

Here's a few of my favorite songs by her:
* the 1
* Lover
* Last Kiss

If you want to know a good song to listen to from albums *not* listed above check this out:

Album | Song
-------|-------
Lover | The Man
reputation | Gorgeous
Red | All Too Well

Just a reminder, I love `<Taylor Swift>`

And here's some code!

```
<html>
<body>
<b>Stop hating Taylor Swift for no reason!</b>
</body>
</html>
```

**Comment by marielacenteno** [comment]
### Caffeine
The most common forms of caffeine consumption are **coffee** and _tea_. I prefer ~tea~ coffee. Blog on coffee news and developments: [https://sprudge.com/](url)

![Coffee](https://club.atlascoffeeclub.com/wp-content/uploads/2019/05/nathan-dumlao-264380-unsplash.jpg)

Best time to drink caffeine:

1. Morning
2. Evening
3. Night

How to drink coffee:

- With friends
- Alone
- With sugar and cream
- Without sugar or cream

```Favorites```:

Coffee         | Tea
------------|-------------
Americano  | Yerba Mate
Cold Brew   | Black Tea
Iced Coffee | Green Tea

```
<html>
<body>
<b>Stay Caffeinated!</b>
</body>
</html>
```

**Comment by refe22** [comment]
# Favorite Animals!

<addrs> Hi guys! My name is Ruth and I ~~like~~ love koalas! To learn **more** about them, visit their *National Geographics* page: [Koalas on National Geographic](https://www.nationalgeographic.com/animals/mammals/k/koala/) 
</addrs>

![ Koala ](https://api.time.com/wp-content/uploads/2020/02/GettyImages-942148352.jpg)

#### Other Cool Animals: 
* Dolphins
* Tigers
* Mountain Goats

#### Favorite Domesticated Animals:
1.  Cats
1.  Dogs
1.  Fish 

<addrs> Below is how long each of the following wild animals lives:

Name | Lifespan
------ | ----------- 
Koalas  | 13 - 18 years
Stripped Dolphins | 55 - 60 years
Tigers | 10 - 15 years 
Mountain Goats| 12 - 18 years 

<addrs> Here's some fun ```<i>code</i>``` that's about koalas too! 
```
<html>
 <body>
 <b> Koalas are cool </b>
 </body>
</html>
```

**Comment by ymacias-1** [comment]
![Image of horchata](https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2020/04/Horchata-9.jpg)

Hello. My name is Yvonne. My ~~favorite~~ **absolute** favorite agua fresca is horchata. Sadly, I can not have traditional horchata that usually contains things like condensed milk. *Curse* lactose intolerance. So, I found a vegan recipe online. 

# What ingredients do I use to make horchata? 
> * Rice
> * water
> * almond milk 
> * cinnamon sticks
> * sugar
> * vanilla extract

How would headers look like in html: 

```
<html>
  <h1>What ingredients do I use to make horchata? </h1>
</html>
```



# Steps to make horchata(without measurements)
>1. Soak rice overnight in water 
>2. Drain the rice and put in a blender 
>3. Add water, cinnamon, and vanilla to the blender. Blend. 
>4. Strain the mixture
>5. Add almond milk and sugar 
>6. Enjoy 

Random: I could have used different header tags besides <code> h1 </code> tags. 
The website that has the horchata recipe. I also like other recipes shared here! 
[Minimalist Baker](https://minimalistbaker.com/date-sweetened-horchata/) 
Ingredients I usually have ready at home | Ingredients I have had to go buy mid-process 
---------------------------------------- | ----------------------------------------------
Rice | Almond milk 
Water | Sugar 
Vanilla extract | 
Cinnamon sticks |

**Comment by sarahfreeman-star** [comment]
![piano aesthetic](https://user-images.githubusercontent.com/70239824/94318952-7d17fa00-ff3e-11ea-93ad-1cd32416c76f.png)

**My Favorite Songs and Artists**
Hello, my name is Sarah, and I _love_ music! 
[Classical Music Website](https://www.classical-music.com/)

**My Favorite Classical Pieces**
1. Piano Concerto No. 2 in C Minor, Op. 18: 1. Moderato by Sergei Rachmaninoff
2. Vremena goda, Op. 67: L'Automne: Petit Adagio by Alexander Glazunov 
3. Rêverie by Claude Debussy 

**My Favorite Classical Composers** 
- Sergei Rachmaninoff 
- Frédéric Chopin 
- Jean-Yves Thibaudet 

| My Favorite Songs | ~~My Favorite~~ Artists | 
| ------------------ | --------------- | 
| Viva La Vida | Coldplay | 
| Stayin Alive | Bee Gees | 
| Dark Paradise | Lana Del Rey |
| Bohemian Rhapsody | Queen |
| everything I wanted | Billie Elish | 
| Miss Jackson | Panic! At the Disco | 
| Can't Take My Eyes Off You | Frankie Valli |

```
<html>
    <body>
        <b> “Without music, life would be a blank to me.” - Jane Austen </b>
    </body>
</html>
```

**Comment by ohorban** [comment]
[Twitter](https://twitter.com/aristotle?lang=en)
![philopsophy meme](https://user-images.githubusercontent.com/70180882/94327289-c710d800-ff5e-11ea-809c-60eb86257125.png)
**Rene Descartes was in a restaurant when the waiter asked if he wanted another drink. He said, “I think not!”, and disappeared.**

*A man goes into a library and asks for a book about Pavlov’s dogs and Schrodinger’s cat. The librarian says, “It rings a bell, but I don’t know whether it’s there or ~~not~~”*

- Why are pacifists bad at jokes? They don’t believe in punchlines.
- Nihilism means nothing to me.
- I have no more puns to put here


1. A philosopher tells a friend she’s recently had a baby. The friend says “Congratulations, is it a boy or a girl?” The philosopher says “yes”.
1. My local philosophy club has free why-fi
1. I would like to make a pun about philosophy but I Kant

Philosopher | Idea
------------ | -------------
Aristotle (384–322 BCE) | Asserted the use of logic as a method of argument and offered the basic methodological template for analytical discourse
Confucius (551–479 BCE) | Developed a belief system focused on both personal and governmental morality through qualities such as justice, sincerity, and positive relationships with others
René Descartes (1596–1650) | Discards belief in all things that are not absolutely certain, emphasizing the understanding of that which can be known for sure

<code>this looks nice</code>
that's how I made it:
`<code>inline code</code>`

some code block:
```
<html>
    <body>
        <b>Philosophy is fun sometimes!</b>
    </body>
</html> 
```

**Comment by saneenkhan** [comment]
# Visit UAE! 
Hi everyone! My name is **_Saneen_** and I grew up in _Dubai, UAE_. Check out [this](https://www.holidify.com/pages/facts-about-uae-2675.html) cool website for 55 fun facts about the country  :star_struck: 

![dubai-(getty)](https://user-images.githubusercontent.com/70279041/94345722-71a0fd80-0028-11eb-808c-18d31aa090bc.jpg)

## The UAE is made up of ~~8~~ 7 Emirates:

1. Abu Dhabi
2. Dubai
3. Sharjah 
4. Umm al-Qaiwain
5. Fujairah
6. Ajman
7. Ra's al-Khaimah 

## Here are some places you can visit in the UAE:

- The Sheikh Zayed Mosque in Abu Dhabi
- The Burj Khalifa (tallest building in the world!)
- Dubai Mall
- The Louvre Abu Dhabi
- Jebel Jais
- The desert

## Museums in each Emirate: 
Emirates | Museum 
------------ | -------------
Abu Dhabi | The Louvre
Dubai | Dubai Museum
Sharjah | Sharjah Museum of Islamic Civilization
Umm al-Qaiwain | UAQ National Museum
Fujairah | Fujairah Museum
Ajman | Ajman Museum
Ra's al-Khaimah | National Museum of Ras Al Khaimah​​​

Some code!

    <html>
    <body>
    <b> Visit Soon! </b>
    </body>
    </html>

**Comment by adien43** [comment]
Hi Everyone, this is my dog **Hiro**! If you want to learn more about the *shiba inu* breed click on <a  rel="follow" href="https://www.akc.org/dog-breeds/shiba-inu/#:~:text=The%20Shiba%20is%20the%20smallest,compact%20with%20well%2Ddeveloped%20muscles.">this page!</a>
![IMG_4872](https://user-images.githubusercontent.com/70254408/94357551-bf733f80-00d4-11eb-9a90-71a0043af067.jpg)
* Hiro Loves to:
  * Chase the neighborhood cat 
  * Chase his own tail
1. Hiro's favorite places to sleep
   1. On the couch where he is forbidden. 
   2. On my <code>bed</code>
   3. My parent's bed
```
<html>
<body>
<b> Bark! </b>
</body>
</html>
```
Time of day | What is Hiro ~~doing~~?
------------ | -------------
Morning | Asleep 
Afternoon | Asleep 
Night | When he usually goes wild

**Comment by willwaaang** [comment]
# Hong Kong
Hi everyone! My name is **Will**, I'm from _Hong Kong_. 
You can **bold** phrases or words by using this code: `<b>word</b>`

You can visit [this page](https://www.discoverhongkong.com/eng/index.html) to learn more about my country.

![Image of Hong Kong](https://images.unsplash.com/photo-1532455935509-eb76842cee50?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1951&q=80)

## Hong Kong has ~~eighteen~~ three distinct areas:
1. Hong Kong Island
2. Kowloon
3. New Territories

## My favorite places in Hong Kong:
* Repulse Bay
* Causeway Bay
* Stanley

## What my favorite places are known for:

<table style="width:100%">
  <tr>
    <th>Location</th>
    <th>Known For</th>
  </tr>
  <tr>
    <td>Repulse Bay</td>
    <td>Having the nicest beach in Hong Kong!</td>
  </tr>
  <tr>
    <td>Causeway Bay</td>
    <td>Being the best place to go shopping!</td>
  </tr>
  <tr>
    <td>Stanley</td>
    <td>The Stanley Waterfront!</td>
  </tr>
</table>

    <html>
    <body> 
    <p> Come visit sometime! </p>
    </body>
    </html>

**Comment by ZacDavis0-159910538** [comment]
**Hi**
I'm *Zac* my webpage is https://zacdavis0-159910538.github.io/
I like using `<while>` loops in python
* I write sci-fi
* I write fantasy
* I sing
1. "Dear Theodosia" - ~~Hamilton~~
2. "I'll sleep when I'm dead" set it off
3. "Love you anymore" Michael Buble


```
<html>
<body>
<p> Here is a picture of Sqortle. </p>
</body>
</html>
```
![squirtlepicture](https://user-images.githubusercontent.com/70255063/94378857-5ba34380-00e1-11eb-9f92-dac7da7d70bc.jpg)

Cats | Dogs
------------ | -------------
Oliver | Einstein
Ben| 
Stella|

**Comment by Hamadalq181** [comment]
Hi, I'm ~~Hamed~~ ~~Hamaad~~ ~~Ahmed~~ **Hamad**?

`<html>Pronouncing is hard</html>`
Best [website](https://hamadalq181.github.io/) ever made

![Cat](https://cdn.britannica.com/24/212324-050-076731DA/Persian-cat-sleeping.jpg)

An unordered list of reasons why:
* Cats
* Cats
* ~~Cats~~

An ordered list of reasons why:
1. There's more than one cat
2. They're very *cute*
3. ?

    ```
    <html>
        <body>
            <b>?</b>
        </body>
    </html>
    ```
Cat | Rating
------------ | -------------
Cat next door | 7
Enzo | 10

**Comment by TuckHarris** [comment]
# Hi, my name is Tucker Harris.
My **_favorite_** food is <s> sushi</s> ice-cream.
I love `<b>football</b>`
My favorite website is [Eel Slap](http://eelslap.com/)
 
`<HTML>`
`<body>`
`<p> Here is a picture of a random goldfish I found. </p>`
`</body>`
`</html>`

![Goldfish](https://cdn.shopify.com/s/files/1/2549/2660/products/Sarasa.jpg?v=1552081944)

Different Fruits:
* Banana
* Apple
* Orange

Favorite Pets:
1. Dog
1. Cat
1. Turtle

Let's Figure This Out | What is this?
---------------|-------------------
Is this a chair? | Is this a couch?
No. | It's a table.

**Comment by smccann11** [comment]
Hi I'm Spencer, and this is my *favorite* hockey team, **The New York Rangers**.

I do not like our rivals, ~~The New Jersey Devils~~

# The New York Rangers

![rangers](https://user-images.githubusercontent.com/70291882/94602330-90caa580-0249-11eb-98e7-8499e2b35cfc.jpg)

Stanley Cups:
* 1928
* 1933
* 1940
* 1994

Best Players on the 2020 roster:
1. Artemi Panarin
1. Mika Zibanejad
1. Chris Kreider

Name | Position
------------ | -------------
David Quinn | Head Coach
Jacques Martin | Assistant Coach
Jeff Gorton | General Manager

    <html>
    <body>
    <h1>Go Rangers!</h1>
    </body>
    </html>

Learn more about the Rangers [here](https://www.nhl.com/rangers).

**Comment by joellemin** [comment]
Hi I am *Joelle* and I like to take care of **plants**
Here is a [link](http://originallaflowermarket.com/vendor/jays-plants/) to my favorite plant shop in ~~Los Angeles~~ LA! Read <code>below</code>
![Pothos](https://www.gardeningknowhow.com/wp-content/uploads/2019/11/prune-pothos.jpg)
# My favorites
1. Spider Plant
1. Fiddle Leaf Fig
1. Pothos
   1. Golden Pothos
   1. Jessenia Pothos
## Best plant purchases
* Plant rope hangers
* Terracotta pot
* Fertilizer stakes
```
<html>
<body>
<h1>Go Green</h1>
</body>
</html>
```
Easy | Hard
------------ | -------------
Snake Plant| String of Hearts
Monstera | Fiddle leaf fig
