### ISSUE TITLE
[hw1] Getting trouble with README.md

### ISSUE THREAD

**Issue by HoangChu-Claremont** [mikeizbicki/cmc-csci040#42]
I aced all the doctests, however when I ran ```python3 markdown_compiler.py --input_file=README.md```, the terminal wrote there is no such file in directory. 

So I created a README.md file in that directory. But unless I directly **copy** and **paste** the code from ```markdown_compiler.py``` to ```README.md``` file, that code won't be in the ```README.md``` and thus ```README.html``` file. 

Should I just **copy** and **paste** the code from ```markdown_compiler.py``` to ```README.md``` file then run the ```README.html``` file?

**Comment by mikeizbicki** [comment]
The `README.md` file I used is the same `README.md` file that describes the homework assignment: https://github.com/mikeizbicki/cmc-csci040/blob/2020fall/hw_01/README.md

In order for you to run the code on that file, you will have to download it and place it in the same folder as your `markdown_compiler.py` file.

**Comment by willwaaang** [comment]
Having the same issue. I downloaded the `README.md` file and placed it in the same folder as the `markdown_compiler.py file`. However, I keep running into the same error: that the file doesn't exist.

**Comment by adien43** [comment]
I also have the same problem.

**Comment by mel088** [comment]
Hi I think I had the same problem and I got it to work by right-clicking on the <code>README.md</code> file (while it was in the same folder as my <code>markdown_compiler.py</code> file) and selecting “Copy Path”. Then I pasted the path where the README.md would be in the command line so it looks like ....<code>$ python3 markdown_compiler.py —input_file=pasted path</code>

**Comment by willwaaang** [comment]
@mikeizbicki could we set up an appointment for later today?

**Comment by mikeizbicki** [comment]
The only time I'll be available today is during office hours after class.

**Comment by adien43** [comment]
mel008's solution worked, tyty! Though the command is not able to execute as "ValueError: substring not found", does anybody have ideas on why this would be happening?

**Comment by mikeizbicki** [comment]
@adien43  This error means that you have a bug in your python code at whatever line it indicates.  There's lots of possible things that could cause this error, and I'd have to look at your code with you on zoom to help you figure out exactly what it is.

**Comment by mariagerges** [comment]
Did anyone manage to solve this problem? I have the exact same problem.
