### ISSUE TITLE
Where to find my CS40 Office Hours

### ISSUE THREAD

**Issue by benfig1127** [mikeizbicki/cmc-csci040#43]
I have gotten several emails expressing difficulties with finding my office hours, thus I am pasting a link goes to the office hours webpage, where you will find live links for all of our mentors. To find me simply scroll down in the list and my name will appear in certain timeslots. Let me know if anyone has any questions about this:

https://www.cmc.edu/qcl/walk-in-hours

**Comment by gPlacide** [comment]
I've switched to a zoom pro account. Please use this link for tutoring hours instead [https://cmc-its.zoom.us/j/88644872376]
