### ISSUE TITLE
[hw2] Give stars megathread

### ISSUE THREAD

**Issue by HoangChu-Claremont** [mikeizbicki/cmc-csci040#45]
Our hw2 requirements include each repository having at least 5 stars, so I made this megathread for us to give stars!

https://github.com/HoangChu-Claremont/CS40

**Comment by sophiedecastro** [comment]
> Our hw2 requirements include each repository having at least 5 stars, so I made this megathread for us to give stars!
> 
> https://github.com/HoangChu-Claremont/CS40

Hey, I just starred your repository! Would appreciate if you would give mine a star, thanks :) Linked here: https://github.com/sophiedecastro/sophie-matplotlib

**Comment by sophiedecastro** [comment]
Hi all! Here's my repository for the HW if you have a second to give it a star--Thank you! Will be giving stars back :) 

Linked here: https://github.com/sophiedecastro/sophie-matplotlib

**Comment by HoangChu-Claremont** [comment]
> Hey, I just starred your repository! Would appreciate if you would give mine a star, thanks :) Linked here: https://github.com/sophiedecastro/sophie-matplotlib

Done!

**Comment by willwaaang** [comment]
Star 4 star.
https://github.com/willwaaang/Homework-02-CS40

**Comment by sophiedecastro** [comment]
> > Hey, I just starred your repository! Would appreciate if you would give mine a star, thanks :) Linked here: https://github.com/sophiedecastro/sophie-matplotlib
> 
> Sorry your github says "Page not found" when I click it.

Sorry about that! It should be public now.

**Comment by sophiedecastro** [comment]
> Star 4 star.
> https://github.com/willwaaang/Homework-02-CS40

Hey, I just starred your repository! Would appreciate if you would give mine a star, thanks :) Linked here: https://github.com/sophiedecastro/sophie-matplotlib

**Comment by saneenkhan** [comment]
Hey guys! Please star my repository :) 

[](https://github.com/saneenkhan/homework02 )

**Comment by sophiedecastro** [comment]
> Hey guys! Please star my repository :) 
> 
> 
> 
> [https://github.com/saneenkhan/homework02](https://github.com/saneenkhan/homework02 )

Hey, I just starred your repository! Would appreciate if you would give mine a star, thanks :) Linked here: https://github.com/sophiedecastro/sophie-matplotlib

**Comment by mariagerges** [comment]
Hello!! 

I just starred all of your respirators.  I would appreciate it if you do the same for mine. 

here's the link: https://github.com/mariagerges/MariaGergesHW

**Comment by sophiedecastro** [comment]
> Hello!!
> 
> I just starred all of your respirators. I would appreciate it if you do the same for mine.
> 
> here's the link: https://github.com/mariagerges/MariaGergesHW

Hey, I just starred your repository! Would appreciate if you would give mine a star, thanks :) Linked here: https://github.com/sophiedecastro/sophie-matplotlib

**Comment by tkapoor22** [comment]
Hi guys! 

I just starred all of your repositories, would love if you could do the same for mine :) 

Thanks! 

Link: https://github.com/tkapoor22/Matplotlib

**Comment by ohorban** [comment]
Heyyoo friends. I already stared all of urs respos, please star mine: https://github.com/ohorban/dataPlots

**Comment by valerialoria** [comment]
Hey guys! I stared all your repos and would really appreciate if you would star mine! Thank you <3 https://github.com/valerialoria/homework2

**Comment by samcbogen** [comment]
Hey y'all, I just starred all of your repositories, and I would appreciate if you starred mine. Thanks!

https://github.com/samcbogen/matplotlib

**Comment by ymacias-1** [comment]
Hello! I just starred all of your repositories. Would appreciate if you starred mine: 

https://github.com/ymacias-1/hw02

Thank you!

**Comment by HoangChu-Claremont** [comment]
> Hey guys! I stared all your repos and would really appreciate if you would star mine! Thank you <3 https://github.com/valerialoria/homework2

> Hey y'all, I just starred all of your repositories, and I would appreciate if you starred mine. Thanks!
> 
> https://github.com/samcbogen/matplotlib

> Hello! I just starred all of your repositories. Would appreciate if you starred mine:
> 
> https://github.com/ymacias-1/hw02
> 
> Thank you!

Done!

**Comment by brandonsrho57** [comment]
# Hey everyone! 

I would appreciate if you all starred [my repository](https://github.com/brandonsrho57/matplotliblab)! 

Of course, *I'll also be starring yours*! Thank you!

**Comment by smccann11** [comment]
Would appreciate if everyone can like my repo, ill return the favor of course.

https://github.com/smccann11/HW02--Spencer

**Comment by HoangChu-Claremont** [comment]
> Would appreciate if everyone can like my repo, ill return the favor of course.
> 
> https://github.com/smccann11/HW02--Spencer

I think your repo is still in private mode. I can't access yours.

**Comment by smccann11** [comment]
Yep is was, thanks Hoang

**Comment by marielacenteno** [comment]
Hi everyone! I would really appreciate it if you liked my repo. I'll star back!
Link : https://github.com/marielacenteno/data.github.io

**Comment by HoangChu-Claremont** [comment]
> Would appreciate if everyone can like my repo, ill return the favor of course.
> 
> https://github.com/smccann11/HW02--Spencer



> Hi everyone! I would really appreciate it if you liked my repo. I'll star back!
> Link : https://github.com/marielacenteno/data.github.io

Done!

**Comment by refe22** [comment]
Hi Everyone! I would really appreciate if you could **star my repo**: https://github.com/refe22/refe22.hw2
I am going through the thread to star other people's repos now. Thank you!

**Comment by refe22** [comment]
> Star 4 star.
> https://github.com/willwaaang/Homework-02-CS40

Done. Please star mine: https://github.com/refe22/refe22.hw2

**Comment by refe22** [comment]
> Hello! I just starred all of your repositories. Would appreciate if you starred mine:
> 
> https://github.com/ymacias-1/hw02
> 
> Thank you!

Done. Please star mine: https://github.com/refe22/refe22.hw2

**Comment by refe22** [comment]
> Hey guys! I stared all your repos and would really appreciate if you would star mine! Thank you <3 https://github.com/valerialoria/homework2

Done. Please star mine! : https://github.com/refe22/refe22.hw2

**Comment by Yugi00** [comment]
Hey guys! Would be great if you could star my repository: https://github.com/Yugi00/data
I'll being starring all of yours as well!

**Comment by refe22** [comment]
> Hey guys! Would be great if you could star my repository: https://github.com/Yugi00/data
> I'll being starring all of yours as well!

Done!

**Comment by nickwilson3** [comment]
Hey all!
It would be great if you could star my repository: https://github.com/nickwilson3/hw02
I will definitely do so as well, thanks!

**Comment by Hamadalq181** [comment]
Hi everyone! Would really appreciate it if you could star my repository: https://github.com/Hamadalq181/hw02-project
Thank you!

**Comment by yilinli22** [comment]
Hi friends!
It would be great if you could star my repository: https://github.com/yilinli22/HM02
I will definitely do so as well, thanks!

**Comment by NilsSkattum** [comment]
Hey everyone! Would appreciate a star! I have starred everyone here so far!

Repository = https://github.com/NilsSkattum/CS40

**Comment by NilsSkattum** [comment]
> Hi friends!
> It would be great if you could star my repository: https://github.com/yilinli22/HM02
> I will definitely do so as well, thanks!

Done! Please star mine!

**Comment by NilsSkattum** [comment]
> Hi everyone! Would really appreciate it if you could star my repository: https://github.com/Hamadalq181/hw02-project
> Thank you!

Done! Please star mine: https://github.com/NilsSkattum/CS40

**Comment by NilsSkattum** [comment]
> Hey all!
> It would be great if you could star my repository: https://github.com/nickwilson3/hw02
> I will definitely do so as well, thanks!

Done! Please star mine: https://github.com/NilsSkattum/CS40 !

**Comment by NilsSkattum** [comment]
> Hey guys! Would be great if you could star my repository: https://github.com/Yugi00/data
> I'll being starring all of yours as well!

Done! Please star mine: https://github.com/NilsSkattum/CS40

Also did @HoangChu-Claremont @brandonsrho57 @ohorban @refe22 @smccann11 @sophiedecastro @tkapoor22  ! please star mine! 

Repository = https://github.com/NilsSkattum/CS40

**Comment by refe22** [comment]
> > Hey guys! Would be great if you could star my repository: https://github.com/Yugi00/data
> > I'll being starring all of yours as well!
> 
> Done! Please star mine: https://github.com/NilsSkattum/CS40
> 
> Also did @HoangChu-Claremont @brandonsrho57 @ohorban @refe22 @smccann11 @sophiedecastro @tkapoor22 ! please star mine!
> 
> Repository = https://github.com/NilsSkattum/CS40

Done!

**Comment by iamclassycain** [comment]
Hey, would appreciate some stars :)) thanks!! 
https://github.com/iamclassycain/hw2_data_visualization

**Comment by rmagill22** [comment]
Hey y'all, I would really love if I could get some stars on my repository! Will definitely being giving stars as well! Have a great day(: 
https://github.com/rmagill22/HW02

**Comment by ZacDavis0-159910538** [comment]
Stars please! 
https://github.com/ZacDavis0-159910538/hw_02-Pokemon

**Comment by dorcassaka** [comment]
If y'all could please star my repository (https://github.com/dorcassaka/hw_02) that would be great! I have starred all of yours!

**Comment by NilsSkattum** [comment]
Starred @dorcassaka but think it is in private!

**Comment by dorcassaka** [comment]
> Starred @dorcassaka but think it is in private!

@NilsSkattum thank you! I think I fixed it!

**Comment by adien43** [comment]
Hi guys I know its late but some stars would be appreciated. 
(https://github.com/adien43/hw_02)
Thank you!
