### ISSUE TITLE
Submitting 10k comments to Sakai

### ISSUE THREAD

**Issue by nickwilson3** [mikeizbicki/cmc-csci040#47]
What is the best way to submit the 10k comments for the lab to Sakai?

At least for me, the terminal in vscode can not display more than 1k comments and there is a 1 million character limit on sakai.

**Comment by HoangChu-Claremont** [comment]
> the terminal in vscode can not display more than 1k comments
Have you tried pressing the triangle button in the top right of VS Code?

> there is a 1 million character limit on sakai.
Regarding Sakai limit, I think there's no other way than writing as concise as possible.

**Comment by nickwilson3** [comment]
@HoangChu-Claremont, yea i am able to run the code and the output is listed in the terminal, but then at a certain point the terminal cant scroll anymore

**Comment by mikeizbicki** [comment]
Just copy and paste as much as will fit.  I'm not going to actually count the number of lines.
