### ISSUE TITLE
Temporary Subreddit

### ISSUE THREAD

**Issue by brandonsrho57** [mikeizbicki/cmc-csci040#49]
Hey everyone! Since the sub was banned, I just created a new temporary subreddit that ya'll can use to test the bots [here](https://www.reddit.com/r/csci040temp/). I'll add a few articles, but feel free to spam the bots there until a new one is created by Mike or the old one is unbanned!

**Comment by sophiedecastro** [comment]
> Hey everyone! Since the sub was banned, I just created a new temporary subreddit that ya'll can use to test the bots [here](https://www.reddit.com/r/csci040temp/). I'll add a few articles, but feel free to spam the bots there until a new one is created by Mike or the old one is unbanned!

Thanks for making this @brandonsrho57 !

**Comment by refe22** [comment]
> Hey everyone! Since the sub was banned, I just created a new temporary subreddit that ya'll can use to test the bots [here](https://www.reddit.com/r/csci040temp/). I'll add a few articles, but feel free to spam the bots there until a new one is created by Mike or the old one is unbanned!

Thank you!!!

**Comment by mikeizbicki** [comment]
Great job @brandonsrho57 .  /r/csci40temp is the new official subreddit for the homework :)
