### ISSUE TITLE
DMCA takedown notice of youtube-dl

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#50]
Several weeks ago, we used  the youtube-dl python library to download videos from youtube.  There were some questions at the time about the legality of youtube-dl, and the library has recently been under attack for facilitating piracy.  Specifically, the RIAA issued what's called a DMCA takedown notice, so the code is no longer available on github.  See:

https://github.com/ytdl-org/youtube-dl/

Except that one of the advantages of open source software is that anyone can host and contribute to the software.  So thousands of new repos have popped up on the internet with the software.  See for example:

https://github.com/l1ving/youtube-dl

You can read the hacker community's response to the DMCA takedown on Hacker News at:

https://news.ycombinator.com/item?id=24872911

There's also a handfull of subreddits with interesting discussions about the takedown:

https://www.reddit.com/r/programming/comments/jgub36/youtubedl_just_received_a_dmca_takedown_from_riaa/
https://www.reddit.com/r/youtubedl/comments/jgttnc/youtubedl_github_repository_disabled_due_to_a/
https://www.reddit.com/r/DataHoarder/comments/jgtzum/youtubedl_repo_had_been_dmcad/

**Comment by mikeizbicki** [comment]
Today, the youtube-dl repository has been put back online.

The Electronic Freedom Foundation (EFF) [1] provided legal support for the youtube-dl authors and sent [this letter](https://github.com/github/dmca/blob/master/2020/11/2020-11-16-RIAA-reversal-effletter.pdf) to github arguing that the youtube-dl library was perfectly legal, and removing the library was actually an illegal application of the DMCA.  Github agreed that they made a mistake and returned the repository online.  You can find discussions from the hacker perspective here: https://news.ycombinator.com/item?id=25113132

[1] The EFF is like the ACLU for computers.  They provide legal support for people who are wrongly accused of committing computer crimes, and they lobby congress in order to ensure that the laws guarantee that computer users are allowed to do what they want with their own devices.

**Comment by HoangChu-Claremont** [comment]
Am I thinking correctly: the key here is that the software "sends that['signature'] value back to Youtube" and gets automatic allowance or "expressly authorized by the Service" since that value is the same value in URL to perform the next step. Furthermore, the value is public without any encryption. Therefore, the software does not violate 1st and 2nd Permissions and Restrictions in its Use of Service policy.

**Comment by mikeizbicki** [comment]
@HoangChu-Claremont That's essentially correct, although I don't know what your referring to by "1st and 2nd Permissions and Restrictions in its Use of Service policy".  The legality of software like youtube-dl (in the US) does not depend in any way on youtube's terms of use, it depends only on the federal law defined by the DMCA.
