### ISSUE TITLE
Counting the number of comments

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#51]
I've created a file `bot_counter.py` that counts the number of valid comments that a bot has created.  You can download the file at: https://github.com/mikeizbicki/cmc-csci040/blob/2020fall/hw_03/bot_counter.py .  In order to use the file, you will have to follow the instructions in the file's `FIXME` annotations in order to specify the user account details.

The file may take up to about 10 minutes to completely run, and the output of the file contains a lot of information about the types of comments you've posted.   The most important number is the vary last section, that will look something like
```
========================================
valid_comments= 213
========================================
```
This is the number that I will use to determine your credit for how many posts your bot has created.

**Important:** I've modified the submission instructions for your bot so that you must include the output of the `bot_counter.py` script in the `README.md` file of your github repo.

**Comment by sophiedecastro** [comment]
I'm getting the following output and error when I try to run the ```bot_counter.py``` file:

```
Sophies-MacBook-Air:cs40bot SophieD$ /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 /Users/SophieD/Documents/GitHub/cs40bot/bot_counter_copy.py
len(comments)= 1000
len(top_level_comments)= 328
len(replies)= 672
len(valid_top_level_comments)= 0
Traceback (most recent call last):
  File "/Users/SophieD/Documents/GitHub/cs40bot/bot_counter_copy.py", line 41, in <module>
    if reply.parent().author.name!=username:
AttributeError: 'NoneType' object has no attribute 'name'
Sophies-MacBook-Air:cs40bot SophieD$ 
```

I didn't make any changes to the file other than changing the username to that of my bot, and the file was working earlier today, so I'm not sure what happened.

Thanks for any help!

**Comment by mel088** [comment]
I had the same problem. It was working last night, but this morning it wasn't working anymore giving me that same error.

**Comment by HoangChu-Claremont** [comment]
> I'm getting the following output and error when I try to run the `bot_counter.py` file:
> 
> ```
> Sophies-MacBook-Air:cs40bot SophieD$ /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 /Users/SophieD/Documents/GitHub/cs40bot/bot_counter_copy.py
> len(comments)= 1000
> len(top_level_comments)= 328
> len(replies)= 672
> len(valid_top_level_comments)= 0
> Traceback (most recent call last):
>   File "/Users/SophieD/Documents/GitHub/cs40bot/bot_counter_copy.py", line 41, in <module>
>     if reply.parent().author.name!=username:
> AttributeError: 'NoneType' object has no attribute 'name'
> Sophies-MacBook-Air:cs40bot SophieD$ 
> ```
> 
> I didn't make any changes to the file other than changing the username to that of my bot, and the file was working earlier today, so I'm not sure what happened.
> 
> Thanks for any help!

I think reply.parent().author gives you the **username** of reply's parent comment. Therefore, .name is **redundant**.

**Comment by mel088** [comment]
@HoangChu-Claremont That worked for me, thank you!!

**Comment by sophiedecastro** [comment]
> > I'm getting the following output and error when I try to run the `bot_counter.py` file:
> > ```
> > Sophies-MacBook-Air:cs40bot SophieD$ /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 /Users/SophieD/Documents/GitHub/cs40bot/bot_counter_copy.py
> > len(comments)= 1000
> > len(top_level_comments)= 328
> > len(replies)= 672
> > len(valid_top_level_comments)= 0
> > Traceback (most recent call last):
> >   File "/Users/SophieD/Documents/GitHub/cs40bot/bot_counter_copy.py", line 41, in <module>
> >     if reply.parent().author.name!=username:
> > AttributeError: 'NoneType' object has no attribute 'name'
> > Sophies-MacBook-Air:cs40bot SophieD$ 
> > ```
> > 
> > 
> > I didn't make any changes to the file other than changing the username to that of my bot, and the file was working earlier today, so I'm not sure what happened.
> > Thanks for any help!
> 
> I think reply.parent().author gives you the **username** of reply's parent comment. Therefore, .name is **redundant**.

Works for me, too! Thanks so much

**Comment by mikeizbicki** [comment]
@HoangChu-Claremont @mel088 @sophiedecastro The suggesteed change of removing the `.name` will fix the error but will not lead to the correct numbers being calculated in some situations.  I've uploaded a new version of the `bot_counter.py` fille to github that you should use instead.
