### ISSUE TITLE
[HW3] Why it took 13 hours running bot.py but still nothing turned out

### ISSUE THREAD

**Issue by yilinli22** [mikeizbicki/cmc-csci040#54]
I know there are MANY comments now so it take time. But it took 13 hours and still nothing turned out in the terminal. My code just stuck here : 
new iteration at: 2020-10-26 23:02:49.299651
submission.title= 2020 Debate Thread
submission.url= https://www.reddit.com/r/csci040temp/comments/jhb20w/2020_debate_thread/

Can anyone help me out?

**Comment by saneenkhan** [comment]
I am having the same problem right now. Does anyone have any suggestions?

**Comment by dorcassaka** [comment]
I would suggest changing the url to this / any subbredit with very few comments: https://www.reddit.com/r/csci040temp/comments/jhmggg/from_hoangs_bot_1_how_sexist_abuse_of_women_in/ 

Also have you double checked in your code that you have csci040temp?

**Comment by yilinli22** [comment]
Now I'm having this error here: AssertionError: Unexpected status code: 429

I added try and except statement, but I don't know how long should I set for time.sleep. I tried 5 seconds but it is still showing this error. Can anyone help me with this? Thank you so much!

**Comment by dorcassaka** [comment]
Where are your try and except statements?

**Comment by yilinli22** [comment]
I put my try statement right after while true, and except after the entire code.

**Comment by dorcassaka** [comment]
What worked for me was putting the try statement after while true and putting the except statement after task 4. The time exception was also attached to the except statement

**Comment by yilinli22** [comment]
Do you know how long should we set for waiting?

**Comment by dorcassaka** [comment]
I did 60 seconds but I think some people did 5 secs

**Comment by yilinli22** [comment]
Thank you so much!
