### ISSUE TITLE
API Exception (HW 3)

### ISSUE THREAD

**Issue by tkapoor22** [mikeizbicki/cmc-csci040#55]
Hey guys! 

I tried using an except API error statement to stop the rate limit error, but as soon as I started using the code it stopped my bot from posting comments in other submissions/ ignores task 5. Has anyone else faced this error? I put my try statement after while True and the except statement right after task 5. Maybe the locations of my try and except statements are incorrect?

Thanks!!

**Comment by dorcassaka** [comment]
I think you need to change the location of your expect statement. I put it between task 4 and task 5 and I haven't gotten any errors and task 5 still works.

**Comment by tkapoor22** [comment]
Thanks Dorcas!

**Comment by mikeizbicki** [comment]
To be a bit more concrete, the function that can cause the rate limit error is the `.reply()` function.  So the try/except block should go around that.  Something like:
```
try:
    comment.reply('your reply here')
    print('replied')
except Exception as e:
    print('rate limit exception',e)
    time.sleep(60*10)
```
