### ISSUE TITLE
Election debate thread banned???

### ISSUE THREAD

**Issue by ohorban** [mikeizbicki/cmc-csci040#57]
I was trying to open the link
https://www.reddit.com/r/csci040/comments/j9vb5b/the_2020_election_bot_debate_thread/
that we are using for homework but it says " r/csci040 has been banned from Reddit"

**Comment by dorcassaka** [comment]
Yes it was banned. We are using this now: https://www.reddit.com/r/csci040temp/comments/jhb20w/2020_debate_thread/
