### ISSUE TITLE
[Week 9 lab] About lab submission

### ISSUE THREAD

**Issue by HoangChu-Claremont** [mikeizbicki/cmc-csci040#58]
@mikeizbicki I have 2 questions:

1. Are the expected outputs in lab.py correct / up-to-date?
2. I can see only the lab_ec.py submission page on Sakai. Can we submit both lab.py and lab_ec.py results in that page?

Thanks a lot!

**Comment by mikeizbicki** [comment]
1. The expected outputs were correct as of Thursday 8pm PT.

2. There is a separate submission page for both the extra credit and the regular lab.  They must be submitted separately.
