### ISSUE TITLE
Issue with Task 2 (NO_TEXT:) PRAW API Exception

### ISSUE THREAD

**Issue by classycain** [mikeizbicki/cmc-csci040#59]
I am running the following code to post a top level comment for task two, and it keeps returning an error of 
**"praw.exceptions.RedditAPIException: NO_TEXT: 'we need something here' on field 'text'".** 

I am assuming that this means it is not registering any text to post to Reddit. My generate_comment() function is working fine. I am running the code below to post a top level comment to the submission.  Has anyone run into this issue?

submission.reply(generate_comment())

**Comment by mikeizbicki** [comment]
Without seeing your full code, I can't say exactly what's going on.  My thought is that either:

1. that's not actually the line generating the error message

2. your `submission` variable is not actually a reddit submission, but has been changed to something else; you should double check that it is in fact a submission

**Comment by iamclassycain** [comment]
@mikeizbicki Thank you! I resolved the issue. All of the functions within generate_comment() were being printed instead of returned...
