### ISSUE TITLE
Quiz extension due to typo

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#66]
There was a typo in the quiz for week 11 where the order of `CREATE` and `INSERT` statements was reversed.  I've uploaded a fixed version of the quiz to https://github.com/mikeizbicki/cmc-csci040/blob/2020fall/week_11/quiz.pdf and I'm granting an extension on the quiz until Wednesday this week due to this typo.

Thanks to everyone who pointed out the mistake.

**Comment by mariagerges** [comment]
If we already submitted the quiz, do we have to re-submit the updated version?

**Comment by mikeizbicki** [comment]
Great question.  There's no need to resubmit if you think your answers are still correct.  But if you'd like to, you have the option of resubmitting.

**Comment by refe22** [comment]
How do we resubmit the quiz? The Sakai page currently doesn't allow for resubmissions. Do we need to email it instead?
