### ISSUE TITLE
HW5 submission details

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#69]
HW 5 must be demoed live over zoom.

I will be available during the following times for demos:

Mon, Nov 30 at 1pm
Wed, Dec 2 at 8am
Fri, Dec 4 at 1pm
Mon, Dec 7 at 8am (but if you choose this time, you will be considered 1 day late and receive a -10% penalty)

For each day, I will stay as long as there are students waiting to demo your projects.  Each demo should take about 5 minutes, and I'll give you your grade on the spot.

If all of those times do not work for you for some reason (e.g. they all conflict with your other finals),
then email me and we will work out another arrangement.

If you demo early, and do not like your grade, you can also attend one of the later sessions for a regrade.  (The regrade will have a -3 penalty, so you'll have to fix a lot of things to get a net positive score.)

**Important:**
In order to ensure privacy for students being graded, I will not admit you into the room until it is your turn to be graded.  That means that you may be in the weighting room for a long time (potentially 1-2 hours) if there is a large line of students in front of you.

**Comment by sophiedecastro** [comment]
> HW 5 must be demoed live over zoom.
> 
> I will be available during the following times for demos:
> 
> Mon, Nov 30 at 1pm
> Wed, Dec 2 at 8am
> Fri, Dec 4 at 1pm
> Mon, Dec 7 at 8am (but if you choose this time, you will be considered 1 day late and receive a -10% penalty)
> 
> For each day, I will stay as long as there are students waiting to demo your projects. Each demo should take about 5 minutes, and I'll give you your grade on the spot.
> 
> If all of those times do not work for you for some reason (e.g. they all conflict with your other finals),
> then email me and we will work out another arrangement.
> 
> If you demo early, and do not like your grade, you can also attend one of the later sessions for a regrade. (The regrade will have a -3 penalty, so you'll have to fix a lot of things to get a net positive score.)
> 
> **Important:**
> In order to ensure privacy for students being graded, I will not admit you into the room until it is your turn to be graded. That means that you may be in the weighting room for a long time (potentially 1-2 hours) if there is a large line of students in front of you.

Hey Mike! For these demo sessions, should we use the normal Zoom link that we use for class and lab? Thanks!

**Comment by mikeizbicki** [comment]
Yes, we will use the same zoom link as class/office hours.
