### ISSUE TITLE
Yesterday's lecture upload

### ISSUE THREAD

**Issue by mariagerges** [mikeizbicki/cmc-csci040#71]
Hey mike, 
Can you upload yesterday's lecture to the youtube channel? 
Thanks!

**Comment by mikeizbicki** [comment]
Thanks for letting me know.  They should be uploaded now.

**Comment by mariagerges** [comment]
Hey mike, 

Will you upload yesterday's lecture before today's lab? 

Thanks!

**Comment by mikeizbicki** [comment]
The lecture video should have finished uploading now.
