### ISSUE TITLE
Not class related

### ISSUE THREAD

**Issue by ohorban** [mikeizbicki/cmc-csci040#72]
Hi Mike. I got tired of refreshing a course schedule page to register for my classes, so I wrote a program using ```pyautogui``` library to do it for me. Then I thought it would be nice if the program notified me as soon as there was an open seat in the class, which we can do easily by looking at html code for that page. However, I could not use ```requests``` because the http link for course selection does not lead straight to the page I need. Do you know if there is a way to get html contents of a page not based on a link, but based on the tab that is currently opened at your browser?

**Comment by HoangChu-Claremont** [comment]
I think you need to create an automatic bot and a virtual browser to simulate your mouse move and typing. I suggest looking at Selenium.

**Comment by HoangChu-Claremont** [comment]
One more thing though: the portal might be unstable if a third-party intervenes. Hyperschedule has face a problem with increased concurrent users this semester (https://github.com/MuddCreates/hyperschedule/issues/158). I would suggest you read the link first before moving on.

**Comment by mikeizbicki** [comment]
I'll second the suggestion to use selenium.  It let's you control an existing firefox/chrome window that's already been opened, and is in general the go to solution for complicated web scraping applications.
