### ISSUE TITLE
Another unrelated question

### ISSUE THREAD

**Issue by HoangChu-Claremont** [mikeizbicki/cmc-csci040#73]
Can anyone please recommend a (free) website or book or recommendation to learn professional / comprehensive Powerpoint?

**Comment by brandonsrho57** [comment]
If you want a free course, YouTube always has tons of playlists, but comprehensiveness is variable.. You can always check different websites that have professionals that teach courses such as [Udemy](https://www.udemy.com/courses/search/?src=ukw&q=powerpoint) or [Coursera](https://www.coursera.org/search?query=powerpoint&), although it's not free. Coupons are sometimes available on other sites like [reddit](https://www.reddit.com/r/udemyfreebies/).
