### ISSUE TITLE
Check out my super useful website! (still under production though)

### ISSUE THREAD

**Issue by HoangChu-Claremont** [mikeizbicki/cmc-csci040#76]
Hi everyone,

In the past 2 months I have been doing a integrated courses website that will help you tremendously in course selection as well as planning:

http://claremontcourses.herokuapp.com/

While the website is still in production, I have incorporated many useful utilities, in my opinion. The website now is only 85-95% of what I expected right now. I hope you can visit my website, check out courses you interested, and report errors / suggestions. I am looking forward to deploying a complete app before Fall 2021 course registration. The goal is to forget clinging on the portal to find courses in hassle (for example, checking a course's prerequisite and perm-required or no will be much faster with my website). 

Current features right now:
- Search courses:
+ School-specific
+ Keyword-specific
+ (possibly) multiple keyword-specific
- Filtering: all can checkbox multiple values concurrently except for yes/no boxes:
+ major/subject
+ (possibly) fulfill general education
+ has off-campus equivalents (school-specific or multiple schools concurrently)
+ number of prerequisites
+ (possibly) perm: yes ONLY if all profs require, will update to show specific profs NOT requiring perm.
+ has concurrent, for example labs: yes/no
+ number of corequisites
+ (possible but remains doubtful) semesters offered including past years.
- Upload syllabus: one/multiple files. Syllabus will be uploaded directly to a specific course folder in Drive.
-(Possibly) See syllabus via Gg drive link so you can choose to download all uploaded syllabus or specific ones.

And many more to come. User experience is key and top priority, so please report anything you find troublesome in my website. Literally anything, including curse words. 

The final special thing 95% of this app components are based on my knowledge learned in CS40 from knowing nothing: HTML, CSS, Flask, Jinja, SQLite, Python, JSON, etc. The remaining 5% is some bootstrap, which is easy with CSS background, and Javascript.

**Comment by refe22** [comment]
Hi Hoang,

This is so cool! Thanks for doing this. I will definitely check this out
this week to report any issues/comments.

Best,
Ruth Efe

**Comment by HoangChu-Claremont** [comment]
UPDATE: YOU CAN NOW UPLOAD / SEE UPLOADED SYLLABUS FOR EACH COURSE. Check out: 

http://claremontcourses.herokuapp.com/

There are 2 ways:
1. Click on syllabus -> upload via Drive.
Pros: secured, file wont got to my computer
Cons: risk of rate limit from google and web shutdown

2. Click on upload -> upload like normal:
Pros: the file will go to my system, which has a sleep time enough to not getting rate limit, BUT NOT STAY in my computer as far as I concern.
Cons: currently don't see any. Looking forward to find some errors.

PLEASE name your file carefully, as each drive folder is accessible by everyone having the link. DONT SHARE THIS WEBSITE OUTSIDE OF 5Cers.

Finally, I NEED YOUR FEEDBACK MORE THAN EVER, since I suddenly have a boost in timeline (earlier than expect), I think I will public my web to our community to upload/download syllabi and check courses. Plus you now know where to find syllabi!

WHAT's NEXT? Still a lot of work: (mainly) optimizing search engine, styling, Login system, multiple keyword search, etc. I will do them later if I got busy with research.

**Comment by HoangChu-Claremont** [comment]
FINAL_UPDATE: it's completed!
