### ISSUE TITLE
Meet and Greet Thread

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#78]
Hi everyone!

Your first tasks in this class are to:

1. sign up for github (if you don't already have an account)
1. press the "watch" button at the top of this page
1. reply to this post telling us what tv show you've been binge watching over summer or what books you've been reading

All class communication will go through github, and watching this repo will cause you to get email notifications about everything.

**Comment by mikeizbicki** [comment]
Hey everyone, Mike Izbicki here :)

Like I mentioned in class, I have 3 year old and 5 month old sons.  The 3 year old is super into the TV show *Blaze and the Monster Machines*, so we've been watching that with breakfast every morning.  Then before bed we read *Blaze* books.

My main rule for us with TV is that the kids can watch as much TV as they want in the morning with breakfast, as long as it's in a foreign language.  I'm trying to teach them both Spanish and Korean, and this is their main exposure to native speakers, especially during pandemic times.  (I'm decent at Spanish but really need to improve my own Korean, and **definitely** not native in either.)

**Comment by HiyabAbraha** [comment]
Hello! My name is Hiyab and I'm a sophomore at CMC this year.

This summer I completely binged all 12 seasons of the Big Bang Theory and rewatched Derry Girls too many times to count. I also watched a few movies for the first time (There Will Be Blood was definitely the most......unique). I noticed that I read fewer books this summer than I have in previous years but I did read Mikhail Bulgakov's "The Master and Margarita". It's a super funny read and I really recommend it!

**Comment by louiseanne** [comment]
Hi all! My name is Louise and I'm a sophomore at Scripps.

This summer I didn't watch a ton of TV but loved seeing the Summer of Soul documentary. Got back into reading a bit as well - my favorite was Kafka on the Shore by Haruki Murakami (amazingly weird and unlike any other novel you'll ever read), but I also re-read All About Love by bell hooks and have been recommending it to basically everyone I meet!

**Comment by Eddie-Shi** [comment]
Greetings, people! My name is Edward Shi and I am a sophomore at Pitzer.

As the summer was quite boring, I've watched a decent amount of shows, whether it'd be animated or real action. In particular, I would strongly recommend a Japanese comedy called "LegalHigh" (a comedy regarding the affair among attornies) and both seasons of "LOVE DEATH + ROBOTS". I would recommend you to watch either of these two disregarding your genre preference as the prior one offers a great touch in the special kind of Japanese humour and the latter one presents you with a series of imaginative sci-fi worlds created by numerous creatively talented artists.

**Comment by abroegger8** [comment]
Hey everyone! My name is Alex and I'm a sophomore at CMC studying econ and data science. 

This summer I gained a deep appreciation for Korean film. Some honorable mentions include Parasite, Gonjiam Haunted Asylum, and #Alive. On the other hand, I enjoyed re-reading Outliers by Malcom Gladwell (one of my favorite books), as well as recently starting The Intelligent Investor by Benjamin Graham and Thinking Fast and Slow by Daniel Khaneman.

**Comment by NACB** [comment]
Hi everyone! My name is Nathanael Baumann and I am a sophomore at CMC. Embarrassingly, I did not read a single whole book this summer. I kept saying I would, but just didn't get started. That being said, I watched lots of TV. I finally caught up on South Park (felt obligated to watch as a Coloradan), watched White Lotus, Chernobyl, a large portion of The Wire, and re watched my favorite seasons of Fargo, to name a few of the most recent ones.

**Comment by NHendelman** [comment]
Hello! My name is Noah Hendelman, and I'm a first year.

I've mainly watched the Olympics this summer, and reading anything by John Green. I'm really excited for the class this year!

**Comment by jennifersjlim** [comment]
Hey everyone! I'm Jen and I am a freshman at CMC studying econ-accounting and data science.
Over the summer, I haven't been able to read much but did finish a few really good books that are worth recommending: When Breath Becomes Air by Paul Kalanithi, Every Last Secret by A.R.Torre, and The Four Winds by Kristin Hannah. As for movies or TV shows, I've re-binge watched Suits and Stranger Things.

**Comment by arijmoore** [comment]
My name is AJ, I'm a senior studying IR and Human Rights. Over the summer, I enjoyed watching It's Such a Beautiful Day by Don Hertzfeldt and reading Gender Trouble by Judith Butler.

**Comment by zealotwithcharge** [comment]
Hi everyone! My name is Charlette Hwang and I'm a sophomore at CMC.
Over the summer I've binged Friends, Bojack Horseman, So Not Worth it, The Office, How I Met Your Mother.
I didn't really read much other than webtoons.

**Comment by KaranGoel1** [comment]
Hello! I am Karan Goel, a sophomore at CMC. Over the summer I didn't watch any TV shows, but I did watch a lot of sports, namely: Formula 1, Cricket, and Tennis. I'm excited to do some programming this semester!

**Comment by KCKiani** [comment]
Hey everyone! I'm Catherine (Cat for short), and I'm a senior Gov/Legal Studies major at CMC. Over the summer, I binged the Netflix Comedy "Never Have I Ever" and became obsessed with "Suits" -- 100% understand now why Harry fell for Meghan. I spent the summer with my sister Nessa -- a junior at CMC -- staying with friends in Geneva, Switzerland while working remotely. This is the first time in 3 years I am in a non-politics/writing based class so for that reason alone I am very excited to learn CS!

**Comment by janetcen** [comment]
Hey guys! I'm Janet and I'm a freshman at CMC majoring in psych.
This summer, I became super obsessed with the Netflix series, The Crown, about the British royal family. It was definitely a little different than the other TV shows I usually watch, but I just loved the drama. Other than that, I've been binging New Girl and catching up with the new season of Schitt's Creek.

**Comment by anikakimme** [comment]
Hey everyone! I'm Anika and I'm a junior at CMC majoring in public policy with a data science sequence. 

I watched a lot of Olympics this summer, mostly track, swimming, and gymnastics, but also some of the new sports like surfing and rock climbing. I also read a few books including Win at All Costs, Let Your Mind Run, and Malibu Rising.

**Comment by nikhilagarwal1111** [comment]
Hey guys, I'm Nikhil, and I'm a sophomore at CMC hoping to major in PPE. I spent most of my summer watching the Euros, F1 grand prix, and tennis Grand Slams, but I did manage to binge Outer Banks on Netflix just before the semester started. In terms of books, I read Inglorious Empire by Shashi Tharoor, 12 Rules to Life by Jordan Peterson, and Discrimination and Disparities by Thomas Sowell

**Comment by sophiahuangg** [comment]
Hi everyone! I'm Sophia, and I'm a sophomore at CMC majoring in data science and psychology. This summer, I've watched a lot of Designated Survivor, Suits, and The Mandalorian. I also started reading a few books such as Crying in H Mart and The Color of Law!

**Comment by derikkk** [comment]
> Hi everyone!
> 
> Your first tasks in this class are to:
> 
> 1. sign up for github (if you don't already have an account)
> 2. press the "watch" button at the top of this page
> 3. reply to this post telling us what tv show you've been binge watching over summer or what books you've been reading
> 
> All class communication will go through github, and watching this repo will cause you to get email notifications about everything.

Hi everyone! 

I'm Derik and I'm a sophomore at CMC majoring in Economics and Data Science. The past summer I watched and finished Queen's Gambit alongside a couple of other documentaries (Icarus, Athlete A). In terms of books, I've partially finished the craft and science of coffee and Modulating the flavor profile of coffee!

**Comment by nrj-demello** [comment]
Hi guys, I'm Nic and I am a Junior at CMC studying Econ and History, with a Data Science Sequence. Over the summer I started watching the Wire as well as rewatching Arrested Development and Brooklynn Nine-Nine. I've also been reading Prisoners of Geography.

**Comment by jaceycarter** [comment]
Hi everyone! My name is Jacey and I'm a junior at CMC majoring in Public Policy and pursuing a data science sequence. Over the summer, I enjoyed watching Love Island every night and the Bachelorette weekly. I guess you could say I enjoy reality TV. I also binge watched Schitt's Creek and Outer Banks. I am really looking forward to the new season of La Casa de Papel (aka Money Heist). I'll be in my dorm room binge watching that this weekend (on Netflix Sept. 3rd)!

I didn't read much this summer; however, I was introduced to data science while doing policy research and fell in love with it! With that being said, I'm excited to learn CS!

**Comment by evankim08** [comment]
Hey guys, I'm Evan and I'm a junior studying Economics and Engineering at CMC. One of the books I read over the summer is 48 Laws of Power by Robert Greene, and now I am looking to re-read Something Deeply Hidden by Sean Carroll. Over the summer, I mostly watched the Euros, and now am finishing the new season of Rick and Morty. I'm excited for this semester!

**Comment by nathanarimilli** [comment]
Hey everyone, I'm Nathan and I'm a freshman studying Data Science and Economics at CMC. Two books that I really enjoyed reading this summer are Shoe Dog by Phil Knight and Station Eleven by Emily St. John Mandel. Also, over the summer, I binge watched Breaking Bad and Top Boy. Super excited for this semester with y'all!

**Comment by xutimon** [comment]
What's up guys my name is Timon (Tim) and I am a prospective PPE major at CMC. I am currently a sophomore, and during the summer I have binged both seasons of Love, Death, Robots on Netflix as well as Ozark. I also finished all the Matrix movies, and am more than excited to be in this class!

**Comment by xutimon** [comment]
What's up guys my name is Timon (Tim) and I am a prospective PPE major at CMC. I am currently a sophomore, and during the summer I have binged both seasons of Love, Death, Robots on Netflix as well as Ozark. I also finished all the Matrix movies, and am more than excited to be in this class!

**Comment by emellestottele** [comment]
Hi Everyone, my name is Emelle and I am a Junior at CMC majoring in Economics and Data Science. Over the summer I didn't watch a lot of TV because I was traveling a lot but I did watch my favorite reality tv show Love Island UK with my sister!

**Comment by Jblachman23** [comment]
Hi everyone, I'm Justin Blachman

I spent a lot of the summer in the outdoors.  I got to do some summer skiing, backpacking, and day hiking up in the Pacific Northwest. I'm from Seattle, so enjoy all the lakes and mountains that are up there. Hopefully can get involved in some outdoorsy activities down here! 

Didn't watch many TV shows or movies this summer, but maybe that will change over the semester.  I spent some time binge watching Manifest, but I think it got a little too mythical for me.  Still giving it a change though!

**Comment by BrianKenyon** [comment]
Hi everyone, my name is Brian Kenyon and I am a Junior at CMC. Over the summer I spent a lot of time binging The Wire, a TV series about drug and crime that takes place in Baltimore, Maryland. I definitely recommend it to anyone who has not watched the show yet.

**Comment by nataliephillips** [comment]
Hi! My name is Natalie, and I am a freshman at CMC. I binged Ted Lasso this summer with my sister, which is arguably one of the best feel good shows out there (I have not watched season two yet). I also read a few books this summer including Beach Read, People We Meet on Vacation, and Where the Crawdads Sing. My favorite book of those three was Where the Crawdads Sing.

**Comment by laurenleadbetter** [comment]
Hi everyone! I'm Lauren, I'm a junior at CMC majoring in History and pursuing the CS Sequence. Over the summer, I loved binge watching Full Bloom, and Upload. And I really enjoyed reading Wilderness by Rockwell Kent - the artist's journal from his time living on Fox Island, Alaska, nearby where I'm from :) 

Looking forward to some cool projects this semester!

**Comment by keirkeenan** [comment]
Hey everyone! I'm Keir, and I'm a Junior at CMC in the Economics & Engineering (3+2) program. Over the summer I loved watching Criminal Minds, Ted Lasso, Wanda Vision, and Loki. :) 

*Also, if anyone from section 1 is willing to swap sections with me, that would be a huge help!

**Comment by ltgoldberg** [comment]
Hi everyone! My name is Lucy but everyone calls me LT. I'm a freshman hoping to study film, and this summer I watched a lot of Shameless, and the marvel series' that came out with my dad. I'm also trying to get through the classics and read The Bell Jar and The Great Gatsby.

**Comment by nilavenkat** [comment]
Hi everyone! I'm Nila, and I'm a senior at CMC studying Science Management. This summer I binge watched Arrested Development and Criminal Minds.

**Comment by josiahtarrant** [comment]
Hey everyone! My name is Josiah and I am a senior at CMC studying Economics with a leadership sequence. Over the summer I watched a lot of Ted Lasso with my family (rewatched season 1 and kept up with season 2). I love to cook, so I also spent a lot of time reading Salt, Fat, Acid, Heat to learn more about different cooking techniques!

**Comment by qchen2323** [comment]
Hi everyone! My name is Qiaoling and I am a Junior studying Economics-Accounting and Data Science. Over the summer, I watched Criminal Minds, Ted Lasso, and Brooklyn Nine-Nine.

**Comment by DienAlex** [comment]
Hello, my name is Alex Dien and I am a first year from CMC.

Over the summer, I watched a lot of Marvel shows and movies like Loki and binged watched a couple other series like Jack Ryan, Schitt's Creek, and most recently, Manifest.

**Comment by chatch166** [comment]
Hello all! I'm Charlie Hatcher, and I'm a first-year here at CMC.

Over the summer, my main binging media was Breaking Bad, and I rewatched a bit of Ozark as well. For books, I went on a little Michael Crichton spree (The Andromeda Strain, Sphere, and Airframe) which were all excellent. I'm excited to be in this class with you all!

**Comment by wgalbreath** [comment]
Hi, my name is William and I'm studying Psych and Leadership.

Over the summer, I watched Survivor, Dead to Me, and Money Heist - all shows I recommend! Really excited for the semester and this class!

**Comment by jhwang22** [comment]
Hi everyone! I’m Joanna, and I’m a senior at CMC. I don’t watch TV shows, so I’ll just list some books I enjoyed reading this summer: _The Plague_ by Albert Camus, _The Unthinkable: _ by Amanda Ripley, and _Lost Boy_ by Christina Henry.

**Comment by TjFournier** [comment]
Hey everyone! My name is TJ, and I'm a junior at CMC studying Economics and Engineering. Over the summer I binged the Amazing Race, since that's as close to traveling as I was going to get for the year.

**Comment by herbertlohmus** [comment]
Tere! 

My name is Herbert and I am studying public policy and economics at CMC. 

Fun fact: I don't think I watched any TV-shows this summer, with the infrequent exception of Mock the Week. I read some Damodaran as well as "The Man, State and War."

**Comment by kyrilus** [comment]
Hi there! 
My name is Kyril. I'm a Senior at CMC majoring in science management. 
As I purchased a fixer upper car this summer, I spent a couple of weeks watching youtube videos on how to replace the radiator, struts, breaks and much more!

**Comment by yeswetran** [comment]
Hi! My name is Nathan Tran. I'm a Pomona junior majoring in Politics. _Community_, _The Thick of It_, and _Crash Landing On You_ were my favorite summer binges!

**Comment by shreyachatterjee22** [comment]
Hi everyone! My name is Shreya and I'm a senior at CMC studying PPE and Literature. This summer I lived and worked in Washington DC with some friends. My favorite read of the last month was _This Is How You Lose The Time War_ by Amal El-Mohtar & Max Gladstone. Right now I'm in the middle of _The Starless Sea_ by Erin Morgenstern. Looking forward to a great class!

**Comment by svmanthamartin** [comment]
Hi everyone!

My name is Samantha, but most people call me Sammi or Sam. I'm a sophomore at Claremont McKenna studying Economics and pursuing a CS sequence. 

I didn't watch much TV this summer, but I finally finished <i>Schitt's Creek</i>. I'm in between shows at the moment, but I'm currently reading <i>On Earth We're Briefly Gorgeous</i>, a novel by Ocean Vuong. 

Looking forward to some fun projects this semester!

**Comment by milesba4** [comment]
Hi everyone! 

My name is Miles. I am from Arlington, Virginia, and am a sophomore at CMC majoring in Economics with a computer science sequence.

This summer I spent most of my time working, but when I had time available I would watch _The Walking Dead_

I am excited to expand my knowledge of HTML, Python, CSS, and Java and am looking forward to a great semester!

**Comment by aaryanb** [comment]
Hey everyone!

My name is Aaryan Batra. I grew up in Tokyo, Japan, and I'm a sophomore at CMC majoring in Economics with a Data Science sequence.

This summer I didn't watch much TV, but I really enjoyed reading the Freakanomics series.

I'm really looking forward to building my Python skills this semester and do cool things like web scraping, data analysis, etc.

**Comment by kevinm126** [comment]
Hi everyone my name is Kevin and I'm a freshman at CMC. Over the summer I binge watched superstore, a show on Hulu that I definitely recommend, and I rewatched money heist on Netflix.

**Comment by AChiu42** [comment]
Hi everyone, my name is Adrian and I'm a sophomore at CMC studying Science Management. I didn't really watch many TV shows over the summer or read any books.

**Comment by jacksonts47** [comment]
Hello,
My name is Jackson. I am from Los Angeles and I am a freshman at CMC. I am not sure what I want to major in, but I am thinking of either data science or mathematics with a sequence in CS. 
Over summer I binge watched modern family and shameless.
For this class, I am excited to get more exposure to the world of computer science.

**Comment by swen7589** [comment]
Hi I'm Swen, I'm from NYC, and I'm a freshman at CMC. Over the summer, I binge watched Outer Banks, which is an amazing show on Netflix. I highly recommend it!

**Comment by Eddie-Shi** [comment]
Hello again, people.
I've  just completed my brief website with somewhat useful info and funny videos (please laugh.) in it. If you'd like to "like" them (if you have a Facebook account, that is). Leave a like!

https://eddie-shi.github.io/week_00_lab_00.html

**Comment by jacksonts47** [comment]
Hello other students,
I finished my website and was wondering if anyone can leave a Facebook like on my webpage and star my repository on github in order to complete the final step of the lab. I will return the favor. 
[https://jacksonts47.github.io/](https://jacksonts47.github.io/)

**Comment by HugoMatousek** [comment]
Hey guys!

Over the Summer, I re-watched Star Gate and Chuck. I also watched all of The Windsors, which is essentially a parody TV show about the British royal family. I also read tons of books, but essentially all of them were Czech.

Also, I would greatly appreciate if  you could like my [webpage ](https://hugomatousek.github.io/lab_01.html) and star my [repo](https://github.com/HugoMatousek/HugoMatousek.github.io). (Yep, I am only doing this now, so I will be super grateful to you who will still do the favor!)

**Comment by leynahong** [comment]
Hi everyone! 

I'm a junior at CMC majoring in Econ and Philosophy. I just recently joined the class, and over the summer, I binge-watched Ted Lasso, Brooklyn 99, and Never Have I Ever — all really great shows that I highly recommend! I'm excited to meet everyone!

**Comment by jsilva22** [comment]
Hi everyone!

I'm a senior at CMC majoring in Math and Psych. I also just recently joined the class and over the summer I binge-watched Criminal Minds. Excited to meet everyone!
