### ISSUE TITLE
2nd section details

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#80]
Good news!

A second section of cs40 has just been approved.  We're still working on the exact timeslots, but it will be MWF sometime.  Hopefully tomorrow we'll have the details finalized for you all, but either way I'll definitely host two in-person lab sessions on Friday.

Thanks for being patient as we're sorting through all of these admin details.

**Comment by kyrilus** [comment]
Thank you Professor Izbicki!

**Comment by nrj-demello** [comment]
Thank you Professor. I also wanted to check whether this section would be in-person or virtual. Thanks again for your help.

**Comment by derikkk** [comment]
Thanks again Professor Izbicki for helping us make this second session!

**Comment by mikeizbicki** [comment]
The second section is now live in the portal.  It will have in person lectures on MW 04:30-05:45PM in Kravis 165, and lab F 09:45-11:00AM in RN12.  If you submit a perm request to it, then I'll let you in.

Unfortunately, there is no more room in the original section.  That means that if these time slots do not work for you for whatever reason, you will have to find somebody currently enrolled in the original section to switch out.  If anyone from the original section would prefer the new timeslots, you are free to switch.

**Comment by TjFournier** [comment]
Hey Mike, 

I just sent you the PERM request, when you get a chance, could you accept?

Thanks,

Theodore (TJ) Fournier

**Comment by xutimon** [comment]
Hey if anyone in the old section is open to switching to the new section please let me know, I would really appreciate it! Thanks! 

Timon (Tim) Xu

**Comment by derikkk** [comment]
Hi Mike, just sent the PERM in looking forward to the class!

Best,
Derik Suria

**Comment by nikhilagarwal1111** [comment]
Hey, similar to Tim, if anyone in the current section is willing to switch to the new section, please let me know. You can email me at nagarwal24@students.claremontmckenna.edu. Thanks!

**Comment by christinakulick** [comment]
Hi! I, unfortunately, cannot make the second section. If anyone plans to drop the course or if they would rather be in the new section please let me know! (ckulick23@cmc.edu). Thank you! 

- Christina

**Comment by kyrilus** [comment]
Hey! 
**If you'd like to take the 2nd section** (MW 4:30-5:45 F 9:45-11am) and **switch with me for the 1st**, Please lmk via email: 
**kvanschendel22@cmc.edu**

**I TA a class from 3-5:45 on Monday, and need CS to complete all my Science Management courses.** You would be a huge help if you switched with me, thanks!

**Comment by HugoMatousek** [comment]
Hello!
Just as other people mentioned here - I also cannot make the second section as I have other commitments and classes during **both** the normal class time AND the labs on Friday. 

I am a 3+2 Economics and Engineering major, and I have been trying to get into a CS5/CS40/CS51 for the fifth semester in a row, so you would be an actual savior if you could switch the sections with me - please email me: [hmatousek23@cmc.edu](mailto:hmatousek23@cmc.edu) 

Also, the people who already found someone to switch, could you let us know so the process is easier? Maybe, we can create a shared spreadsheet or something like that to keep track?

**Comment by derikkk** [comment]
Hi @mikeizbicki, 

Does the section 2 schedule start from tomorrow's lab or next week? Thanks!

**Comment by mikeizbicki** [comment]
@derikkk, Both lab sections will happen in person tomorrow at the scheduled times.

**Comment by HugoMatousek** [comment]
Hey @mikeizbicki,
Could you maybe make an exception and send an email to the class saying that it would be great if those from section one who can switch to section two did so? I (and presumably others) have tried to reach out to some people about maybe switching but it is quite difficult since we have two new classes on campus and don't know each other that much. I know that this thread explains the situation but I am afraid that people from already in section one are likely to ignore it. I think it would be a great help for especially upperclassmen who need to take this class but cannot enroll in section two due to clashes with other major requirements. Thanks for considering this!

//also, is it possible to attend the section's one lab tomorrow in hopes we will be able to solve the problem during the weekend (I have a class during section two's lab)?

**Comment by mikeizbicki** [comment]
@HugoMatousek Only people officially enrolled in section 1's lab can attend that timeslot.  There are not enough seats for anyone else to attend.

I will make announcements in class tomorrow and next week for students willing to switch sections.  Attendance at labs is not required, however, so you can work on this weeks lab on your own time.  If you need help and cannot submit the assignment in time, per #81 there will be no late penalties applied.  You can ask questions next week without it negatively affecting your grade.

**Comment by nikhilagarwal1111** [comment]
Hey Mike, I just submitted the PERM for the second section. Looking forward to taking the class this semester!

**Comment by Jblachman23** [comment]
Hi Mike,

 

I keep getting the error message that prevented me from submitting the last
lab (lab 02) on my own computer.  I know that you said last lab would be the
last time you accepted a lab without my computers signature.  I
troubleshooted for several hours these past days, but I cannot seem to get a
fix.  Below is the error message.  Is there a time we can meet tomorrow to
troubleshoot this? 

 

Best,

Justin

**Comment by mikeizbicki** [comment]
@Jblachman23 There is no error message attached to your post, so I can't help you debug the problem on github.  This problem is likely to be better resolved in person anyways, like you suggest.

I'm available before/after class, during lab, and office hours.  I'd be happy to meet with you at any of those times to resolve the issue.

PS.  In the future, it would be better to post a new github issue rather than replying to an unrelated one.  That will keep the conversations more organized.
