### ISSUE TITLE
No late penalties for the first lab

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#81]
There will be no late penalties applied to the week_00 lab.  The due date is still Sunday 5 Sept at midnight, and you should try to submit it by that time, but if you miss that deadline then your grade will not be penalized in any way.

The purpose of this policy is to ensure that everyone (including people who are not able to make their assigned lab sections Friday) will be able to get whatever help they need next week.

**Comment by KaranGoel1** [comment]
Hi Mike,

I have garnered enough Facebook likes to submit my webpage for the first lab, however I cannot find the assignment on Sakai in which to submit it anymore. How should I submit the webpage link?
