### ISSUE TITLE
Join W-ACM (5C CS club)!

### ISSUE THREAD

**Issue by claires99** [mikeizbicki/cmc-csci040#84]
Interested in hearing about social or professional events in computer science? Join W-ACM, the 5C women in CS club (we're open to students of all gender identities)! We organize social events with professors and other students, informational workshops, company talks, and more. You can join the mailing list by filling out a short form at tinyurl.com/wacm-5c. We'll also be at Turf Dinner, so feel free to stop by then or reach out to wacm-leadership-l@g.hmc.edu with any questions.

**Comment by justinjiang1212** [comment]
how can i join
