### ISSUE TITLE
Post your lab screenshots here

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci040#86]
Reply to this comment with your twitter screenshot. You can include images in your comments by dragging and dropping.

**Comment by Eddie-Shi** [comment]
> Reply to this comment with your twitter screenshot. You can include images in your comments by dragging and dropping.

Professor Mike,

I am tiny bit confused. Are we posting our  website’s screenshot to Twitter, then screenshot it and post it here?

**Comment by jhwang22** [comment]
<img width="599" alt="Screen Shot 2021-09-09 at 8 19 17 AM" src="https://user-images.githubusercontent.com/78510953/132714190-9f14b4ec-af54-4149-b575-318cba5f4fa0.png">

Hope I did it right. (Doing this early since I can't make lab tomorrow.)

**Comment by shreyachatterjee22** [comment]
![Fake Tweet Lab 02](https://user-images.githubusercontent.com/89875799/132730180-b125ebc3-9c04-491f-89cb-8c533e85272b.JPG)

Can't believe this is how we found out unicorns are real...

**Comment by nathanarimilli** [comment]
<img width="1439" alt="Screen Shot 2021-09-09 at 10 08 35 AM" src="https://user-images.githubusercontent.com/89937615/132731617-25a2b8e3-29e0-40b7-aa75-b08267787897.png">

**Comment by nathanarimilli** [comment]
<img width="604" alt="Screen Shot 2021-09-09 at 10 15 33 AM" src="https://user-images.githubusercontent.com/89937615/132732293-a6cff6a2-33f5-49b4-b2b1-c2b3aab290fd.png">

He's a prophet...

**Comment by derikkk** [comment]
<img width="602" alt="Screen Shot 2021-09-09 at 1 38 17 PM" src="https://user-images.githubusercontent.com/89935741/132759273-e806f561-999c-41df-94f6-fb67ee6b9f90.png">

Special offer until 10/9!

**Comment by nilavenkat** [comment]
<img width="603" alt="Screen Shot 2021-09-09 at 5 34 50 PM" src="https://user-images.githubusercontent.com/89933532/132780023-82b971e0-fa29-4631-a0e4-c3e3d7a40656.png">
The Martha Stewart friendship wasn't so unlikely after all...

**Comment by nilavenkat** [comment]
<img width="603" alt="Screen Shot 2021-09-09 at 5 34 50 PM" src="https://user-images.githubusercontent.com/89933532/132780023-82b971e0-fa29-4631-a0e4-c3e3d7a40656.png">
The Martha Stewart friendship wasn't so unlikely after all...

**Comment by jaceycarter** [comment]
<img width="722" alt="Screen Shot 2021-09-09 at 8 21 06 PM" src="https://user-images.githubusercontent.com/89937650/132794256-ae079976-d7a3-4a85-ad88-0160ff75ba94.png">


Special offer for life!!

**Comment by herbertlohmus** [comment]
<img width="604" alt="Screenshot 2021-09-09 at 20 18 54" src="https://user-images.githubusercontent.com/90004892/132794264-5ee2df2f-51a0-482a-9b25-67af956031f1.png">

Since when is Shapiro a democract?

**Comment by NACB** [comment]
![W1_lab](https://user-images.githubusercontent.com/89812923/132794939-ee2af411-4d82-4dbb-b03b-2665b399d306.jpg)

It always seemed suspicious to me...

**Comment by aaryanb** [comment]
<img width="596" alt="Screen Shot 2021-09-09 at 8 54 47 PM" src="https://user-images.githubusercontent.com/16775401/132797260-3535a919-492b-4784-a87d-bfcb111d7965.png">

I knew it!

**Comment by HiyabAbraha** [comment]
<img width="600" alt="Screen Shot 2021-09-09 at 8 51 54 PM" src="https://user-images.githubusercontent.com/89937652/132797221-da1a5be7-64a2-497e-a1a0-c868417197a7.png">

**Comment by christinakulick** [comment]
<img width="602" alt="Screen Shot 2021-09-09 at 9 00 40 PM" src="https://user-images.githubusercontent.com/89888289/132797790-544b4d32-c62a-42e8-a93b-e6ab57d63ac9.png">

**Comment by Eddie-Shi** [comment]
![QQ截图20210909213729](https://user-images.githubusercontent.com/89864760/132800719-7f13a14b-5523-42bf-93a4-d9962472452e.png)

**Comment by chatch166** [comment]
<img width="599" alt="Screen Shot 2021-09-09 at 10 11 49 PM" src="https://user-images.githubusercontent.com/89827896/132803316-3ba1de44-44bc-455b-8ec0-60f123e213ac.png">

**Comment by NHendelman** [comment]
<img width="633" alt="Screen Shot 2021-09-09 at 10 39 36 PM" src="https://user-images.githubusercontent.com/89806493/132805780-f054dcb0-3e72-4552-8cf3-002a149be58d.png">
Kanye is maturing!

**Comment by yeswetran** [comment]
![image](https://user-images.githubusercontent.com/4709565/132817237-77bb8bc9-6e9c-4ec6-b9d2-41a107f810a7.png)

Shocking new evidence, as revealed by One America News Network!

**Comment by laurenleadbetter** [comment]
<img width="609" alt="Screen Shot 2021-09-10 at 9 53 00 AM" src="https://user-images.githubusercontent.com/89829795/132889722-859a84f9-aaff-4600-82af-c82bdd236658.png">

**Comment by milesba4** [comment]
<img width="617" alt="Screen Shot 2021-09-10 at 10 06 37 AM" src="https://user-images.githubusercontent.com/90070112/132891325-1dd4505b-d1a4-4b7f-904b-01409daddec6.png">

**Comment by louiseanne** [comment]
<img width="599" alt="Screen Shot 2021-09-10 at 10 13 32 AM" src="https://user-images.githubusercontent.com/89824785/132892028-feb5482d-b968-4602-a7ab-b2adf9a2fb03.png">

Love to see some personal growth <3

**Comment by anikakimme** [comment]
![Lab01](https://user-images.githubusercontent.com/89879016/132893042-8880f4aa-a406-4218-8d0c-2a32c6eefe0e.png)

**Comment by kyrilus** [comment]
<img width="596" alt="fake elon musk tweet" src="https://user-images.githubusercontent.com/11224124/132893983-50eca134-20a1-45da-945a-92c43ef74b02.png">

**Comment by sophiahuangg** [comment]
<img width="602" alt="Screen Shot 2021-09-10 at 10 27 37 AM" src="https://user-images.githubusercontent.com/89934020/132894037-70ca11ae-1336-40bd-aec3-047714bacda6.png">

**Comment by AChiu42** [comment]
![image](https://user-images.githubusercontent.com/89936649/132894044-cc633910-53a5-4eeb-9672-ae64ad1bc4a7.png)

**Comment by macroanton** [comment]
<img width="613" alt="Screen Shot 2021-09-10 at 12 37 16 PM" src="https://user-images.githubusercontent.com/89937621/132894958-a94c019c-f931-425b-b8e5-4840ccba00a7.png">

**Comment by zealotwithcharge** [comment]
![fakerwhat](https://user-images.githubusercontent.com/89870868/132895007-752f4b6c-f783-4d7a-9c0c-1748a94ca88d.PNG)

**Comment by nikhilagarwal1111** [comment]
<img width="600" alt="Screenshot 2021-09-10 at 10 39 51 AM" src="https://user-images.githubusercontent.com/89827404/132895195-459ff3d1-78a6-4be3-bd9f-a662f8f02e8d.png">

GOAT debate over

**Comment by nrj-demello** [comment]
<img width="599" alt="Screenshot 2021-09-10 at 10 39 49" src="https://user-images.githubusercontent.com/89882983/132895291-1e6eba6f-a594-4d34-b3e5-70af392ab65e.png">

**Comment by armaanac** [comment]
<img width="626" alt="Screenshot 2021-09-10 at 10 40 25 AM" src="https://user-images.githubusercontent.com/90060066/132895378-917f07a8-112a-495e-b9a1-54a2933be4ab.png">

**Comment by wgalbreath** [comment]
![Screen Shot 2021-09-10 at 10 50 28 AM](https://user-images.githubusercontent.com/67754864/132896331-4c8dff3a-cad8-49a6-8950-ff7310955151.png)

**Comment by josiahtarrant** [comment]
<img width="598" alt="Screen Shot 2021-09-10 at 10 54 55 AM" src="https://user-images.githubusercontent.com/89893240/132896872-9b33225b-13d5-4ebc-82ab-067ef5b7896a.png">

**Comment by TjFournier** [comment]
![Twitter](https://user-images.githubusercontent.com/89875492/132896908-b6e08ed1-a520-4dee-8a80-cb17aa64e588.jpg)

**Comment by jennifersjlim** [comment]
![lab01_screenshot](https://user-images.githubusercontent.com/89895193/132897151-64bbd5b8-8a7d-44c4-be23-b93154df8721.jpg)

**Comment by qchen2323** [comment]
![Screenshot 2021-09-10 111820](https://user-images.githubusercontent.com/89935821/132899418-427b7881-de6a-46b3-b50d-69172d5c29dc.jpg)

**Comment by abroegger8** [comment]
<img width="600" alt="Screenshot 2021-09-10 at 11 38 34 AM" src="https://user-images.githubusercontent.com/89806594/132901646-ff629875-6eff-45f5-a1b3-7128af2eeaae.png">

**Comment by kevinm126** [comment]
![Screen Shot 2021-09-10 at 11 55 18 AM](https://user-images.githubusercontent.com/89937271/132903610-8b51a63b-d9ce-4b5f-9e84-688835aa3952.png)

**Comment by jacksonts47** [comment]
![Screenshot 2021-09-10 at 11-57-24 adidas on Twitter](https://user-images.githubusercontent.com/89806376/132903724-b3e4bebe-e958-48cf-a80f-d502d88bbc3b.png)

**Comment by jacksonts47** [comment]
![Screenshot 2021-09-10 at 11-59-41 adidas on Twitter](https://user-images.githubusercontent.com/89806376/132903939-921ba84a-71a6-4795-bdbe-f77feb846a8d.png)

**Comment by jacksonts47** [comment]
![Screenshot 2021-09-10 at 12-01-26 adidas on Twitter](https://user-images.githubusercontent.com/89806376/132904085-d152c623-c994-43a3-ac4c-664edd0afcc1.png)

**Comment by jacksonts47** [comment]
![Screenshot 2021-09-10 at 12-02-08 adidas on Twitter](https://user-images.githubusercontent.com/89806376/132904198-6c0bb926-c42f-4d2c-8104-b0537c737918.png)

**Comment by HugoMatousek** [comment]
![image](https://user-images.githubusercontent.com/63810577/132904505-e27d0c19-f572-42bc-b850-c72dca31ec3d.png)

**Comment by KaranGoel1** [comment]
<img width="596" alt="Screenshot 2021-09-10 at 12 05 54 PM" src="https://user-images.githubusercontent.com/81438058/132904598-c8536bc4-492f-4669-bce8-f03969f1da2b.png">

**Comment by Vedant11-R** [comment]
<img width="1440" alt="Screenshot 2021-09-10 at 12 00 13 PM" src="https://user-images.githubusercontent.com/89806414/132905035-a9943ee0-0bc2-41de-b984-0ee68b014a5c.png">

**Comment by swen7589** [comment]
<img width="596" alt="first thing i saw trending on twitter" src="https://user-images.githubusercontent.com/89879508/132905562-53682aba-30b3-4b45-b0c6-8370b7175a16.png">

**Comment by janetcen** [comment]
![Image 9-10-21 at 12 20 PM](https://user-images.githubusercontent.com/89937669/132906240-dc01f887-ee0b-4df8-95ac-e1a16e3cf71d.jpg)

**Comment by keirkeenan** [comment]
![image](https://user-images.githubusercontent.com/89931114/132907859-db2ce819-e24b-4b08-8161-7a52dcad8d1f.png)

**Comment by DienAlex** [comment]
<img width="601" alt="Screen Shot 2021-09-10 at 4 40 13 PM" src="https://user-images.githubusercontent.com/89937902/132928132-a256a272-5dcd-44e5-8359-9b462e620e09.png">

**Comment by ltgoldberg** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/89889702/132936204-1935ed8d-f183-4413-85ad-c40bc397527c.png">

**Comment by evankim08** [comment]
![Lab 00 Screenshot](https://user-images.githubusercontent.com/70280666/132966574-f5cadb71-eaec-4c02-bdb9-dbe9697f6fd5.png)

**Comment by Jblachman** [comment]
<img width="520" alt="Twitter Inspect Element Screenshot" src="https://user-images.githubusercontent.com/90061544/132973206-395c5bbc-ea5f-45a8-8b6d-35adc73e9d27.PNG">

**Comment by emellestottele** [comment]
<img width="634" alt="Screen Shot 2021-09-12 at 12 23 38 PM" src="https://user-images.githubusercontent.com/89890221/133000574-c83d03a1-b775-468d-9eda-1e7378c14d14.png">

**Comment by nataliephillips** [comment]
[john mayer.pdf](https://github.com/mikeizbicki/cmc-csci040/files/7150290/john.mayer.pdf)

**Comment by nataliephillips** [comment]
<img width="601" alt="Screen Shot 2021-09-12 at 2 00 16 PM" src="https://user-images.githubusercontent.com/89864023/133002905-c521fa2b-1293-48b4-ad47-e5f22f870493.png">
