### ISSUE TITLE
Students’ contacts for the first project/homework

### ISSUE THREAD

**Issue by Eddie-Shi** [mikeizbicki/cmc-csci040#88]
Hi! Eddie here.

I am creating this issue for people (including me) who are looking for a partner to finish the homework/project and are comfortable putting down a means of contact!

if you want, you are welcome to contact me through my email: eddshi@students.Pitzer.edu

We can work on the project on any platform of your choice: Discord, zoom, or etc.!

**Comment by chatch166** [comment]
Hello all-

If you're looking for someone's website to link on your page, feel free to use mine: [https://chatch166.github.io/](url)

If you link my website, I will link yours! Email me at chatcher25@cmc.edu to let me know you've linked mine, and I'll return the favor. 

Many thanks,

Charlie H.
