### ISSUE TITLE
Post your completed Website's URL here for follow links and likes!

### ISSUE THREAD

**Issue by Eddie-Shi** [mikeizbicki/cmc-csci040#94]
[Come](https://eddie-shi.github.io) and have fun!

**Comment by NACB** [comment]
https://nacb.github.io/

I definitely need both the links and the likes

**Comment by DienAlex** [comment]
A link and a like [ here ](https://dienalex.github.io/DienAlex/)would be greatly appreciated! Email me at Alex.Dien.25@cmc.edu if you've linked so I can link you.

**Comment by yeswetran** [comment]
Hi everyone! I made a website that compares COVID rates across the 5Cs, and though it's a bit ugly, I hope y'all find it at least a lil useful and fun. [](https://yeswetran.github.io/covid-colleges/)

@DienAlex @NACB @Eddie-Shi Gave y'all links and likes -- I would love some reciprocation whenever you get the chance :)

**Comment by wgalbreath** [comment]
@yeswetran I liked your website. Will you please return the favor on my [website](https://wgalbreath.github.io/index.html) and [repository](https://github.com/wgalbreath/wgalbreath.github.io)? Thx!

**Comment by yeswetran** [comment]
> 
> 
> @yeswetran I liked your website. Will you please return the favor on my [website](https://wgalbreath.github.io/index.html) and [repository](https://github.com/wgalbreath/wgalbreath.github.io)? Thx!

it's such a wholesome website!!!

**Comment by NHendelman** [comment]
Hi everyone, here's my [website](https://nhendelman.github.io/CSC/Website%201%20index.html). It's an absolute mess but I had fun making it. Happy to link others/like/collaborate, you can text me at 2063273997 or email nhendelman@cmc.edu.

**Comment by kyrilus** [comment]
Hey Everyone, Here is my website: https://kyrilus.github.io/website/index.html
Its called House Mouse. Down the line this will turn into my real estate blog/website.

check it out!

**Comment by nilavenkat** [comment]
Hi everyone, Here's my [website](https://nilavenkat.github.io/Recipes/). Like it if you get a chance! :)

**Comment by laurenleadbetter** [comment]
Hi everyone, had to re-make my like button. Would appreciate any likes on [my website](https://laurenleadbetter.github.io/) before submitting.

**Comment by sophiahuangg** [comment]
Hi everyone!! Here is my [website](sophiahuangg.github.io). Let me know if you like my webpage, and I'd be happy to give you a like!

**Comment by evankim08** [comment]
hey guys, here is my [website](https://evankim08.github.io/)! 

feel free to check it out if you have the chance :)

**Comment by Jblachman** [comment]
Hi everyone :) Here is my website: https://jblachman.github.io/

Please check it out if you have some extra time :)

**Comment by louiseanne** [comment]
[heres my site! ](https://louiseanne.github.io/)let me know if you like/link and i'm happy to return the favor.

**Comment by louiseanne** [comment]
also @sophiahuangg and @NHendelman i linked your sites! if you have a chance to do the same that would be great :)

**Comment by sophiahuangg** [comment]
> also @sophiahuangg and @NHendelman i linked your sites! if you have a chance to do the same that would be great :)

Done! (:

**Comment by chatch166** [comment]
[Here's my site!](https://chatch166.github.io/) It's not quite done yet, but if you could link it I will link yours! Please reply to this comment or email me at chatcher25@cmc.edu to let me know, and I will reciprocate. Many thanks, Charlie H.

**Comment by nathanarimilli** [comment]
Hey everyone, let me know if anyone can give me a like on my [webpage here](https://nathanarimilli.github.io/index.html)! Much appreciated and I can like back as well!

**Comment by kevinm126** [comment]
Hey everyone please leave a like if you can [here](https://kevinm126.github.io/mywebsite/index.html)

**Comment by christinakulick** [comment]
Hi! [Here](https://christinakulick.github.io) is my completed website about upcoming CMS vs PP games. Check it out and give a like if you can! Thank you!

**Comment by josiahtarrant** [comment]
Hi Everyone! [Here](https://josiahtarrant.github.io/index.html) is my website. Please like it if you get a chance!

**Comment by herbertlohmus** [comment]
Hello everyone, I would also ask for a like [here](https://herbertlohmus.github.io/index.html):)

**Comment by derikkk** [comment]
Hi everyone, enjoy the [chaos](https://derikkk.github.io/) :)

**Comment by nikhilagarwal1111** [comment]
Hey guys, here's my [website](https://nikhilagarwal1111.github.io/) on my favourite athlete Novak Djokovic. Enjoy!

**Comment by TjFournier** [comment]
Hey everyone! Here's my website [https://tjfournier.github.io/index.html]

**Comment by jaceycarter** [comment]
Hi everyone! Here is my [website](https://jaceycarter.github.io/)! I used this opportunity to create a website for my established lifting and plant-based nutrition page on IG (and for personal training inquiries). Enjoy!! :)

**Comment by milesba4** [comment]
Hello everyone! [Here ](https://milesba4.github.io/)is my vegetable catalog. Enjoy!

**Comment by shreyachatterjee22** [comment]
Hi all - though raindrops on roses and whiskers on kittens are both excellent, I invite you to peruse some of my favorite things. Enjoy! 

My website: https://shreyachatterjee22.github.io/week01/index.html

**Comment by armaanac** [comment]
Hi everyone, here's my website - [https://armaanac.github.io/index.html](url)
Please like it if you get a chance!!

**Comment by janetcen** [comment]
Here's my website! [https://janetcen.github.io/]
Please like if you can!

**Comment by abroegger8** [comment]
Check out my [website](https://abroegger8.github.io/index.html) on Hong Kong! 
Please leave a like :)

**Comment by leynahong** [comment]
Hi everyone! Please check out my website [here](https://leynahong.github.io/hw_00/index.html) and feel free to drop a like!

**Comment by jsilva22** [comment]
Hey guys! Joined the class late so here is my website. Check it out here:https://jsilva22.github.io
