### ISSUE TITLE
Question regarding "uploading" the hw

### ISSUE THREAD

**Issue by Eddie-Shi** [mikeizbicki/cmc-csci040#95]
Professor Mike,

I remember that you've mentioned in the class that we won't need to upload it anywhere? Will you be checking them by yourself or should we do something else?

Thanks!

**Comment by mikeizbicki** [comment]
You must submit your homework to sakai.  Details are in the homework instructions at: https://github.com/mikeizbicki/cmc-csci040/tree/2021fall/hw_00#submission
