### ISSUE TITLE
HW00 Questions

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci040#96]
Hi Professor Izbicki! I was wondering if we needed to put our table in on our main HTML file. Can we put it in one of the other HTML files instead for aesthetic purposes on the main file?

**Comment by mikeizbicki** [comment]
Good question.  Yes, that would be fine to get full credit.  I've updated the wording in the rubric from 

> The main HTML file ...
 
to 

> At least one HTML file ...

to reflect this.

**Comment by herbertlohmus** [comment]
Professor, is it okay for some HTML files not to have 3 divs, 3 <p> in the case that for example one of our html files includes only  our CV?

**Comment by herbertlohmus** [comment]
I also feel like an image on every html file is a bit excessive especially if they only contain links and or a pdf viewer. I currently have more than 3 html files.

**Comment by jaceycarter** [comment]
I'd like to clarify something on the rubric. Do we need to receive 5 likes on each HTML files? Or just our main page? I plan on having 4 HTML files, so would I need 20 likes?

**Comment by herbertlohmus** [comment]
Jacey, I think because the facebook like button is going to use the same script for every page it doesn't matter which page you give the like on, it will give carry to each web page.

**Comment by mikeizbicki** [comment]
@herbertlohmus I will need more detail about exactly what you're trying to do in order to waive the requirements like you'ra asking.  See me after class/in office hours to show me your site and I'll let you know.

@jaceycarter I've updated the wording in the rubric to state that only one of the like buttons needs to have more than 5 likes.  Also, if you are creating more than the required 3 HTML files, the other files do not need to satisfy all of the requirements.  You will get full credit as long as any 3 of the files satisfy the requirements.

**Comment by kyrilus** [comment]
Hi Professor Izbicki, 
I uploaded my website earlier, but forgot that I needed to also upload to Sakai. I just uploaded it at 12:01, is that ok in your book as "on time"?

Thanks,
Kyril

**Comment by mikeizbicki** [comment]
@kyrilus You won't receive a late penalty for this assignment.   In the future, however, I'll be more strict.

**Comment by evankim08** [comment]
@mikeizbicki 

I apologize for the trouble. I just submitted my URL and archived URL on Sakai, but forgot to mention that I worked together with Justin Blachman for the extension. 

I wanted to let you know about this. I will take more care next time.

Thank you!

Evan

**Comment by ltgoldberg** [comment]
The Wayback machine is taking an incredibly long time to archive my site, is this normal? 

Thanks, 
LT

**Comment by chatch166** [comment]
I am having the same issue @ltgoldberg is having––the Wayback Machine says it is saving my URL, but after an hour and a half now no URL has appeared. 

Any thoughts?

Many thanks,
Charlie H.

**Comment by zealotwithcharge** [comment]
Same here. Is it okay if we submit the url with a previous version?

Thanks,
Charlette

**Comment by milesba4** [comment]
Having the same issue with  the Wayback Machine, also when I try to submit my website URL to Sakai the text box is not appearing

**Comment by TjFournier** [comment]
Yeah, I'm having issues with Wayback Machine as well.

-TJ

**Comment by aaryanb** [comment]
I've been having the same issues with Wayback Machine for the past few hours too.

**Comment by mikeizbicki** [comment]
For everyone having issues with the Wayback Machine right now: I will waive this requirement for you if you state in your sakai submission:

> I tried using the Wayback Machine but it took too long to archive.

**Comment by sophiahuangg** [comment]
Hi Professor Izbicki, I just submitted my webpage of the Web Archive with Wayback Machine, but when I click on the link, it doesn't load my page. Is there any way that I can edit my Sakai comment to waive the requirement?

**Comment by jaceycarter** [comment]
I also had trouble with the Web Archive! However, I already submitted my website to Sakai already and can't resubmit (like Sophia mentioned above).

**Comment by aaryanb** [comment]
Unfortunately, I am in the same situation. My apologies for the inconvenience.

**Comment by nataliephillips** [comment]
I submitted without the phrase. But the WayBack Machine was not working for me as well. I can add it to the webpage.
Also I did office hours and collaborated with Charlie!

>
