### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by ltgoldberg** [mikeizbicki/cmc-csci040#97]
Hi, Janet and I have been collaborating, is this how we should let you know? 

Thanks so much

**Comment by louiseanne** [comment]
Adding onto this collaboration chain - I attended the QCL hours for this class last Thursday and worked with Eddie!

**Comment by Eddie-Shi** [comment]
Yes. I attended the QCL hours for this class last Thursday and worked with Eddie and Jean

**Comment by KaranGoel1** [comment]
Hi, I have been collaborating with Nikhil on the homework. Looking forward to seeing all your websites!

**Comment by emellestottele** [comment]
Hey, I have been collaborating with Alex Broegger on the HW.

**Comment by derikkk** [comment]
Hi, I have attended the Sunday QCL session and worked with Marco and Nicholas.

**Comment by nathanarimilli** [comment]
Hey Prof. I also attended the Sunday QCL and collaborated with classmates. I also have been working on the HW and webpage with Alex.

**Comment by aaryanb** [comment]
Hi, I've been working on the HW with Jen (Jennifer).

**Comment by nilavenkat** [comment]
Hi, Jacey & I have been working on the hw together.

**Comment by evankim08** [comment]
justin blachman and i have been working on the hw together!

**Comment by abroegger8** [comment]
Hey, I have been working on the homework with Emelle and Nathan.

**Comment by nikhilagarwal1111** [comment]
I have been working on the homework with Karan Goel

**Comment by chatch166** [comment]
I attended the Sunday QCL walk-in hours and collaborated with Natalie

**Comment by wgalbreath** [comment]
Hello, I attended QCL walk-in hours and worked with Herb and Nic.

**Comment by jennifersjlim** [comment]
Hi, I've attended Sunday QCL and worked with Aaryan.

**Comment by mikeizbicki** [comment]
In order to obtain the 48 hour extension for any assignment in this class, you simply state who you collaborated with in the sakai submission.

There is no need to post who you collaborated with to github.

**Comment by jaceycarter** [comment]
If we plan on using the extension, do we need to post a draft of our assignment at the original deadline time? Or can we just wait to submit after using the extension?

**Comment by mikeizbicki** [comment]
Sakai will only allow 1 submission.  So don't submit a draft, only submit the final assignment that you want graded.

**Comment by milesba4** [comment]
Hello, I attended a QCL walk-in yesterday

**Comment by nilavenkat** [comment]
Hi, Jayce, Christina & I have been collaborating on the python lab

**Comment by herbertlohmus** [comment]
Hi, me and Nic collaborated. I forgot to mention that in my submission.

**Comment by mikeizbicki** [comment]
As a reminder, there is no need to post to github if you collaborated with someone on the lab.  Instead, put the information in the sakai submission.

If you make a mistake with the sakai submission, then send me an email with the collaboration information.
